#!/bin/sh
irudia=$(more /root/mota)
diskaosoa=$(lsblk | grep disk | cut -d ' ' -f 1)
rootzarra=$(mount | grep ' / ' | cut -d ' ' -f 1)
if [ "$rootzarra" = "/dev/${diskaosoa}2" ]
  then
    rootberria="/dev/${diskaosoa}3"
  else
    rootberria="/dev/${diskaosoa}2"
    rootzarra="/dev/${diskaosoa}3"
fi
mkdir sda1
mount /dev/${diskaosoa}1 sda1
mkdir sda2
mount $rootberria sda2
echo "irudia kopiatzen..."
pv /erab/irudiak/$irudia/live/filesystem.squashfs > sda2/filesystem.squashfs
cd sda2
echo "diskoan instalatzen..."
unsquashfs filesystem.squashfs
cd ..
mv sda2/squashfs-root/* sda2/
rmdir sda2/squashfs-root
rm sda2/filesystem.squashfs
echo "fstab eguneratzen..."
echo "/dev/${diskaosoa}1	/boot   	vfat    defaults        	0 0" > sda2/etc/fstab
echo "${rootberria}	/   		ext4    defaults        	0 0" >> sda2/etc/fstab
echo "/dev/${diskaosoa}4	swap    	swap    defaults        	0 0" >> sda2/etc/fstab
echo "/dev/${diskaosoa}5	/home   	ext4    defaults        	0 0" >> sda2/etc/fstab
echo "${rootzarra}	/mnt/Hidden1    ext4    noauto,umask=222        0 0" >> sda2/etc/fstab
echo "192.168.0.102:/home/irudiak       /erab/irudiak    nfs     defaults       0 0" >> sda2/etc/fstab
echo "sarea konfiguratzen..."
cp sda2/initrd.img sda1/
cp sda2/vmlinuz sda1/
echo "append root=${rootberria} rw" >> sda1/syslinux.cfg
echo "append root=${rootberria} rw" >> sda1/EFI/boot/syslinux.cfg
umount /dev/${diskaosoa}1
umount $rootberria
rmdir sda1
rmdir sda2
