#!/bin/sh
swapoff --all
diska=`lsblk | grep disk | awk 'FNR == 1 {print $1}'`
mkfs.ext4 /dev/${diska}1 -FL boot
mkfs.ext4 /dev/${diska}5 -FL sistemaA
mkfs.ext4 /dev/${diska}6 -FL sistemaB
mkfs.ext4 /dev/${diska}7 -FL opt
mkswap /dev/${diska}8
mkfs.ext4 /dev/${diska}9 -FL home
dd bs=440 count=1 conv=notrunc if=/usr/lib/syslinux/mbr/mbr.bin of=/dev/$diska
mkdir yo
mount /dev/${diska}1 yo
cp syslinux.cfg yo/
cp ipxe.lkrn yo/
cp /usr/lib/syslinux/modules/bios/libutil.c32 yo/
cp /usr/lib/syslinux/modules/bios/menu.c32 yo/
extlinux --install yo/
umount yo
rmdir yo

