#!/bin/sh
if [ $# -eq 0 ]
  then
    echo "Diska aukeratu behar duzu"
    lsblk | grep disk
    exit
fi
for n in /dev/$1* ; do umount $n ; done
swapoff --all
dd if=/dev/zero of=/dev/$1 bs=10240 count=1
parted -s /dev/$1 mklabel gpt  \
 mkpart primary fat32 0% 200MB  \
 mkpart primary ext4 200MB 10GB  \
 mkpart primary ext4 10GB 20GB  \
 mkpart primary linux-swap 20GB 24GB  \
 mkpart primary ext4 24GB 100%  \
