#!/bin/sh
if [ $# -eq 0 ]
  then
    echo "Diska aukeratu behar duzu"
    lsblk | grep disk
    exit
fi
mkfs.vfat /dev/${1}1 -F 32 -n BOOT
mkfs.ext4 /dev/${1}2 -FL sistemaA
mkfs.ext4 /dev/${1}3 -FL sistemaB
mkswap /dev/${1}4
mkfs.ext4 /dev/${1}5 -FL home
