#!/bin/sh
diskaosoa=$(lsblk | grep disk | cut -d ' ' -f 1)
rootzarra=$(mount | grep ' / ' | cut -d ' ' -f 1)
if [ "$rootzarra" = "/dev/${diskaosoa}2" ]
  then
    rootberria="/dev/${diskaosoa}3"
  else
    rootberria="/dev/${diskaosoa}2"
fi
echo "diskaosoa hau da $diskaosoa"
echo "rootzarra hau da $rootzarra"
echo "rootberria hau da $rootberria"
