---
- name: Install mame
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - mame

- name: Create mame dir in skel
  file:
    path: /etc/skel/mame
    state: directory

- name: Create .mame link
  file:
    src: "mame"
    dest: "/etc/skel/.mame"
    state: link

- name: Copy mame.ini
  copy:
    src: "{{ role_path }}/files/mame.ini"
    dest: /etc/skel/mame/mame.ini
    mode: 0644

- name: Copy vertical.ini
  copy:
    src: "{{ role_path }}/files/vertical.ini"
    dest: /etc/skel/mame/vertical.ini
    mode: 0644

#- name: Copy roms
#  copy:
#    src: /root/groovymame/roms
#    dest: /etc/skel/mame/
