---
- name: Install retroarch to get all the dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - retroarch
    - libqt5concurrent5

- name: Install build dependencies
  command: /usr/bin/mk-build-deps {{ item }} -i -r -t "apt-get -y --no-install-recommends"
  args:
    warn: false
  with_items:
    - retroarch

- name: Download retroarch sources from git
  git:
    repo: 'https://github.com/libretro/RetroArch'
    dest: /home/retroarch

#apt-cache showsrc retroarch | grep Build-Depends
- name: Configure
  command: "./configure"
  args:
    chdir: "/home/retroarch"

- name: Build
  make:
    chdir: /home/retroarch
#    params:
#      NUM_THREADS: 4

- name: Build install
  make:
    chdir: /home/retroarch
    target: install

- name: Copy original retroarch
  copy:
    src: /usr/local/bin/retroarch
    dest: /usr/local/bin/retroarch_original
    mode: 0755
    remote_src: yes

- name: Download my patch from git
  git:
    repo: 'https://github.com/cesetxeberria/retroarchcrt31'
    dest: /home/retroarchcrt31

- name: Apply patch
  patch:
    src: /home/retroarchcrt31/retroarch_crt31_doubled.patch
    basedir: /home/retroarch
    strip: 1
    remote_src: yes

- name: Make uninstall
  make:
    chdir: /home/retroarch
    target: install

- name: Build
  make:
    chdir: /home/retroarch
#    params:
#      NUM_THREADS: 4

- name: Make install
  make:
    chdir: /home/retroarch
    target: install

- name: Copy retroarch120 script to use with normal retroarch
  copy:
    src: "{{ role_path }}/files/usr/local/bin/retroarch120"
    dest: /usr/local/bin/retroarch120
    mode: 0755

- name: Copy retroarch120 config
  copy:
    src: "{{ role_path }}/files/etc/retroarch120.cfg"
    dest: /etc/retroarch120
    mode: 0644

- name: Copy retroarch480 script to use with normal retroarch
  copy:
    src: "{{ role_path }}/files/usr/local/bin/retroarch480"
    dest: /usr/local/bin/retroarch480
    mode: 0755

- name: Copy retroarch120 config
  copy:
    src: "{{ role_path }}/files/etc/retroarch480.cfg"
    dest: /etc/retroarch480
    mode: 0644

- name: clean retroarch sources
  file:
    path: /home/retroarch
    state: absent

- name: clean my patch sources
  file:
    path: /home/retroarchcrt31
    state: absent

- name: Remove retroarch build dependencies
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - retroarch-build-deps
