- name: jaitsi git
  git:
    repo: 'https://github.com/dolphin-emu/dolphin'
    dest: /home/dolphin

- name: Install build dependencies
  command: /usr/bin/mk-build-deps {{ item }} -i -r -t "apt-get -y --no-install-recommends"
  args:
    warn: false
  with_items:
    - dolphin-emu

- name: Install more dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - qtbase5-private-dev
#- name: Build-depends
#  apt:
#    name: "{{ packages }}"
#  vars:
#    packages:
#    - qtbase5-private-dev

- name: ziurtatu build karpeta existitzen dela
  file:
    path: "/home/dolphin/build"
    state: directory

- name: Configure
  command: "cmake .."
  args:
    chdir: "/home/dolphin/build"

- name: Build
  make:
    chdir: /home/dolphin/build
    params:
      NUM_THREADS: 4

- name: Build install
  make:
    chdir: /home/dolphin/build
    target: install

- name: clean dolphin sources
  file:
    path: /home/dolphin
    state: absent

