- name: Download dolphin git
  git:
    repo: 'https://github.com/dolphin-emu/dolphin'
    dest: /home/dolphin

- name: Install dolphin build dependencies
  command: /usr/bin/mk-build-deps {{ item }} -i -r -t "apt-get -y --no-install-recommends"
  args:
    warn: false
  with_items:
    - dolphin-emu

- name: Install more dependencies for dolphin
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - qtbase5-private-dev
    - libmbedtls12
    - libsfml-network2.5
    - libopengl0

#- name: Build-depends
#  apt:
#    name: "{{ packages }}"
#  vars:
#    packages:
#    - qtbase5-private-dev

- name: Create build folder for dolphin
  file:
    path: "/home/dolphin/build"
    state: directory

- name: Configure dolphin
  command: "cmake .."
  args:
    chdir: "/home/dolphin/build"

- name: Build dolphin
  make:
    chdir: /home/dolphin/build
    params:
      NUM_THREADS: 4

- name: Build install dolphin
  make:
    chdir: /home/dolphin/build
    target: install

- name: Clean dolphin sources
  file:
    path: /home/dolphin
    state: absent

