- name: jaitsi git
  git:
    repo: 'https://github.com/dolphin-emu/dolphin'
    dest: /root/dolphin

- name: Install build dependencies
  command: /usr/bin/mk-build-deps {{ item }} --install --root-cmd --remove
  args:
    warn: false
  with_items:
    - dolphin

#- name: Build-depends
#  apt:
#    name: "{{ packages }}"
#  vars:
#    packages:
#    - qtbase5-private-dev

- name: ziurtatu build karpeta existitzen dela
  file:
    path: "/root/dolphin/build"
    state: directory

- name: Configure
  command: "cmake .."
  args:
    chdir: "/root/dolphin/build"

- name: Build
  make:
    chdir: /root/dolphin/build
    params:
      NUM_THREADS: 4

- name: Build install
  make:
    chdir: /root/dolphin/build
    target: install

