- name: Download citra from git
  git:
    repo: 'https://github.com/citra-emu/citra'
    dest: /home/citra

- name: Install build dependencies for citra
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - libsdl2-2.0-0
    - libsdl2-dev
    - qtbase5-dev
    - libqt5opengl5-dev
    - qtmultimedia5-dev
    - libqt5multimedia5-plugins
    - libfdk-aac-dev
    - ffmpeg
    - libswscale-dev
    - libavdevice58
    - libavformat-dev
    - libavcodec-dev
    - libavdevice-dev
    - clang
    - clang-format
    - libc++-dev
    - cmake

- name: Create build folder for citra
  file:
    path: "/home/citra/build"
    state: directory

- name: Configure citra
  command: "cmake .."
  args:
    chdir: "/home/citra/build"

- name: Build citra
  make:
    chdir: /home/citra/build
    params:
      NUM_THREADS: 4

- name: Build install citra
  make:
    chdir: /home/citra/build
    target: install

- name: Uninstall build dependencies for citra
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - libsdl2-dev
    - qtbase5-dev
    - libqt5opengl5-dev
    - qtmultimedia5-dev
    - libfdk-aac-dev
    - libswscale-dev
    - libavformat-dev
    - libavcodec-dev
    - libavdevice-dev
    - clang
    - clang-format
    - libc++-dev
    - cmake
#    - qtbase5-private-dev

- name: Clean citra sources
  file:
    path: /home/citra
    state: absent
