- name: jaitsi git
  git:
    repo: 'https://github.com/PCSX2/pcsx2'
    dest: /root/pcsx2

- name: Install build dependencies
  command: /usr/bin/mk-build-deps {{ item }} --install --root-cmd --remove
  args:
    warn: false
  with_items:
    - pcsx2

- name: ziurtatu build karpeta existitzen dela
  file:
    path: "/root/pcsx2/build"
    state: directory

- name: Configure
  command: "cmake .. -DCMAKE_TOOLCHAIN_FILE=cmake/linux-compiler-i386-multilib.cmake"
  args:
    chdir: "/root/pcsx2/build"

- name: Build install
  make:
    chdir: /root/pcsx2/build
    target: install
