---
  - include: 00-depends.yml

  - include: 01-mameinstall.yml

  - include: 01-groovymame.yml

#  - include: 02-mamecompile.yml

  - include: 03-attractmode.yml

#  - include: 03-emulationstation.yml

  - include: 04-retroarch.yml

  - include: 05-dolphin.yml

#  - include: 06-pcsx2.yml

  - include: 07-citra.yml

  - include: 08-clean.yml

  - include: 09-arcadelive.yml
