#!/bin/bash
if [ $# -eq 0 ]
  then
    echo "You have to choose a disk"
    lsblk | grep disk
    exit
fi
for n in /dev/$1* ; do umount $n ; done
swapoff --all

p=""
if [[ $1 = nvme* || $1 = mmc* ]]
  then
    p="p"
fi

mkfs.ext4 /dev/${1}${p}2 -FL system
mkdir sda2
mount /dev/${1}${p}2 sda2
echo "copying the image..."
pv /lib/live/mount/medium/live/filesystem.squashfs > sda2/filesystem.squashfs
cd sda2
echo "installing on disk..."
unsquashfs filesystem.squashfs
cd ..
mv sda2/squashfs-root/* sda2/
rmdir sda2/squashfs-root
rm sda2/filesystem.squashfs
echo "updating fstab..."
echo "/dev/${1}${p}1        /boot/efi           vfat    defaults                0 0" > sda2/etc/fstab
echo "/dev/${1}${p}2    /                   ext4    defaults                0 0" >> sda2/etc/fstab
echo "/dev/${1}${p}3    swap        swap    defaults                0 0" >> sda2/etc/fstab
echo "#/dev/${1}${p}4    /home       ext4    defaults                0 0" >> sda2/etc/fstab
echo "none    /home       tmpfs    defaults                0 0" >> sda2/etc/fstab
echo "removing unmute"
if test -f "sda2/etc/xdg/autostart/unmute.desktop"; then
    rm sda2/etc/xdg/autostart/unmute.desktop
fi
echo "restoring NetworkManager"
if test -f "sda2/usr/share/applications/nm-applet.desktop"; then
    cp sda2/usr/share/applications/nm-applet.desktop sda2/etc/xdg/autostart/nm-applet.desktop
fi
echo "disabling dchlient"
if test -f "sda2/etc/systemd/system/multi-user.target.wants/dhclient.service"; then
    rm sda2/etc/systemd/system/multi-user.target.wants/dhclient.service
fi
echo "disabling swapiness service"
if test -f "sda2/etc/systemd/system/multi-user.target.wants/swapiness.service"; then
    rm sda2/etc/systemd/system/multi-user.target.wants/swapiness.service
fi
umount /dev/${1}${p}2
rmdir sda2
