#!/bin/sh
if [ $# -eq 0 ]
  then
    echo "You have to choose a disk"
    lsblk | grep disk
    exit
fi
for n in /dev/$1* ; do umount $n ; done
swapoff --all
mkfs.vfat /dev/${1}1 -F 32 -n BOOT
mkfs.ext4 /dev/${1}2 -FL system
mkswap /dev/${1}3
mkfs.ext4 /dev/${1}4 -FL home
