#!/bin/sh
if [ $# -eq 0 ]
  then
    echo "You have to choose a disk"
    lsblk | grep disk
    exit
fi
for n in /dev/$1* ; do umount $n ; done
swapoff --all
dd if=/dev/zero of=/dev/$1 bs=10240 count=1
parted -s /dev/$1 mklabel gpt  \
 mkpart primary fat32 0% 200MB  \
 mkpart primary ext4 200MB 10GB  \
 mkpart primary linux-swap 10GB 14GB  \
 mkpart primary ext4 14GB 100%  \
 set 1 legacy_boot on
