#!/bin/sh
if [ $# -eq 0 ]
  then
    echo "You have to choose a disk"
    lsblk | grep disk
    exit
fi
for n in /dev/$1* ; do umount $n ; done
swapoff --all

p=""

if [[ $1 = nvme* ]]
  then
    p="p"
fi

mkfs.vfat /dev/${1}${p}1 -F 32 -n BOOT
mkfs.ext4 /dev/${1}${p}2 -FL system
mkswap /dev/${1}${p}3
mkfs.ext4 /dev/${1}${p}4 -FL home
dd bs=440 count=1 conv=notrunc if=/usr/lib/syslinux/mbr/gptmbr.bin of=/dev/$1
syslinux --install /dev/${1}${p}1
