#!/bin/sh
if [ $# -eq 0 ]
  then
    echo "You have to choose a disk"
    lsblk | grep disk
    exit
fi
for n in /dev/$1* ; do umount $n ; done
mkdir sda1
mount /dev/${1}1 sda1
mkdir -p sda1/EFI/boot
cp syslinux_local.cfg sda1/EFI/boot/syslinux.cfg
cp /usr/lib/SYSLINUX.EFI/efi64/syslinux.efi sda1/EFI/boot/bootx64.efi
cp /usr/lib/syslinux/modules/efi64/libutil.c32 sda1/EFI/boot/
cp /usr/lib/syslinux/modules/efi64/menu.c32 sda1/EFI/boot/
cp /usr/lib/syslinux/modules/efi64/ldlinux.e64 sda1/EFI/boot/
mkdir sda2
mount /dev/${1}2 sda2
echo "copying the image..."
pv /lib/live/mount/medium/live/filesystem.squashfs > sda2/filesystem.squashfs
cd sda2
echo "installing on disk..."
unsquashfs filesystem.squashfs
cd ..
mv sda2/squashfs-root/* sda2/
rmdir sda2/squashfs-root
rm sda2/filesystem.squashfs
echo "updating fstab..."
echo "/dev/${1}1        /boot/efi           vfat    defaults                0 0" > sda2/etc/fstab
echo "/dev/${1}2    /                   ext4    defaults                0 0" >> sda2/etc/fstab
echo "/dev/${1}3    swap        swap    defaults                0 0" >> sda2/etc/fstab
echo "#/dev/${1}4    /home       ext4    defaults                0 0" >> sda2/etc/fstab
echo "none    /home       tmpfs    defaults                0 0" >> sda2/etc/fstab
echo "copying kernel and initrd"
if test -f "sda2/initrd.img"; then
    cp sda2/initrd.img sda1/
    cp sda2/vmlinuz sda1/
fi
if test -f "sda2/boot/initrd.img"; then
    cp sda2/boot/initrd.img sda1/
    cp sda2/boot/vmlinuz sda1/
fi
echo "removing unmute"
rm sda2/etc/xdg/autostart/unmute.desktop
echo "restoring NetworkManager"
if test -f "sda2/usr/share/applications/nm-applet.desktop"; then
    cp sda2/usr/share/applications/nm-applet.desktop sda2/etc/xdg/autostart/nm-applet.desktop
fi
echo "disabling dchlient service"
if test -f "sda2/etc/systemd/system/multi-user.target.wants/dhclient.service"; then
    rm sda2/etc/systemd/system/multi-user.target.wants/dhclient.service
fi
sed -e '0,/DNS/ s/DNS/#DNS/' -i sda2/etc/systemd/resolved.conf
sed -e '0,/Domains/ s/Domains/#Domains/' -i sda2/etc/systemd/resolved.conf

echo "append root=/dev/${1}2 rw mitigations=off" >> sda1/EFI/boot/syslinux.cfg
umount /dev/${1}1
umount /dev/${1}2
rmdir sda1
rmdir sda2
#sed -e '0,/DNS/ s/DNS/#DNS/' -i resolved.conf
