#Xfce-ren fitxategiak blokeatzen ditugu, erabiltzaileek aldaketarik ez egiteko. Ikastolako logoa jartzen dugu ere
---
- name: Ikastolako irudia kopiatu.
  copy:
    src: "{{ role_path }}/files/usr/share/backgrounds/xfce/ikastola.png"
    dest: "/usr/share/backgrounds/xfce/ikastola.png"
    mode: 0644

- name: Ikastolako irudia jarri mahaigainean
  copy:
    src: "{{ role_path }}/files/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml"
    dest: "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml"
    mode: 0644

- name: Begiratu lightdm instalatuta dagoen.
  stat:
    path: "/etc/lightdm/lightdm-gtk-greeter.conf"
  register: lightdm

- name: Begiratu sddm instalatuta dagoen.
  stat:
    path: "/usr/share/sddm/themes/sddm-theme-dialog-main/theme.conf"
  register: sddm

- name: Ikastolako irudia jarri lightdm-n.
  replace:
    dest: "/etc/lightdm/lightdm-gtk-greeter.conf"
    regexp: '^(.*)background=(.*)$'
    replace: 'background=/usr/share/backgrounds/xfce/ikastola.png'
  when: lightdm.stat.exists == True

- name: Ikastolako irudia jarri sddm-n.
  replace:
    dest: "/usr/share/sddm/themes/sddm-theme-dialog-main/theme.conf"
    regexp: '^(.*)backgroundImage=(.*)$'
    replace: 'backgroundImage=/usr/share/backgrounds/xfce/ikastola.png'
  when: sddm.stat.exists == True

- name: Xfce blokeatu.
  replace:
    dest: "{{ item }}"
    regexp: 'version="1.0">'
    replace: 'version="1.0" locked="*" unlocked="root;@sudo">'
  with_items:
    - "/etc/xdg/xfce4/panel/default.xml"
    - "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml"
    - "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml"
    - "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml"
    - "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/keyboards.xml"
    - "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml"
    - "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml"
    - "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/thunar.xml"
    - "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml"
