#Xfce-ren fitxategiak blokeatzen ditugu, erabiltzaileek aldaketarik ez egiteko. Ikastolako logoa jartzen dugu ere
---
- name: Ikastolako irudia kopiatu.
  copy:
    src: "{{ role_path }}/files/usr/share/backgrounds/xfce/ikastola.png"
    dest: "/usr/share/backgrounds/xfce/ikastola.png"
    mode: 0644

- name: Ikusi mahaigaineko irudi orijinala existitzen den
  stat:
    path: "/usr/share/backgrounds/xfce/xfce-verticals.png"
  register: xfce_verticals

- name: Ikusi mahaigaineko irudi orijinala existitzen den bookworm
  stat:
    path: "/usr/share/backgrounds/xfce/xfce-shapes.svg"
  register: xfce_shapes

- name: Mahaigaineko jatorrizko irudia gorde.
  copy:
    src: "/usr/share/backgrounds/xfce/xfce-verticals.png"
    dest: "/usr/share/backgrounds/xfce/xfce-verticals.png.back"
    remote_src: yes
    mode: 0644
  when: xfce_verticals.stat.exists

- name: Mahaigaineko jatorrizko irudia gorde. Bookworm
  copy:
    src: "/usr/share/backgrounds/xfce/xfce-shapes.svg"
    dest: "/usr/share/backgrounds/xfce/xfce-shapes.svg.back"
    remote_src: yes
    mode: 0644
  when: xfce_shapes.stat.exists

- name: Mahaigaineko jatorrizko irudia kendu.
  file:
    path: "/usr/share/backgrounds/xfce/xfce-verticals.png"
    state: absent
  when: xfce_verticals.stat.exists

- name: Mahaigaineko jatorrizko irudia kendu. Bookworm
  file:
    path: "/usr/share/backgrounds/xfce/xfce-shapes.svg"
    state: absent
  when: xfce_shapes.stat.exists

- name: Ikastolako irudia jarri mahaigainean eta sddm-n
  file:
    src: ikastola.png
    dest: /usr/share/backgrounds/xfce/xfce-verticals.png
    state: link
  when: xfce_verticals.stat.exists

- name: Ikastolako irudia jarri mahaigainean eta sddm-n bookworm
  file:
    src: ikastola.png
    dest: /usr/share/backgrounds/xfce/xfce-shapes.svg
    state: link
  when: xfce_shapes.stat.exists

#- name: Ikastolako irudia jarri sddm-n.
#  replace:
#    dest: "/usr/share/sddm/themes/maldives/theme.conf"
#    regexp: '^(.*)background=(.*)$'
#    replace: 'background=/usr/share/backgrounds/xfce/ikastola.png'

#- name: Xfce blokeatu.
#  replace:
#    dest: "{{ item }}"
#    regexp: 'version="1.0">'
#    replace: 'version="1.0" locked="*" unlocked="root;@sudo">'
#  with_items:
#    - "/etc/xdg/xfce4/panel/default.xml"
#    - "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml"
#    - "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml"
#    - "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml"
#    - "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/keyboards.xml"
#    - "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml"
#    - "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml"
#    - "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/thunar.xml"
#    - "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml"
