#firefox eta chromeren politikak ezarri. Debian eta Ubuntu
---
- name: Firefox-en politikak ezarri.
  copy:
    src: "{{ role_path }}/files/etc/firefox/policies/policies.json"
    dest: "/etc/firefox/policies/policies.json"
    mode: 0644

- name: Chromium politikak ezarri.
  copy:
    src: "{{ role_path }}/files/etc/chromium/policies/managed/policies.json"
    dest: "/etc/chromium/policies/managed/policies.json"
    mode: 0644
  when: ansible_architecture == 'i386'

- name: Chrome politikak ezarri.
  copy:
    src: "{{ role_path }}/files/etc/chromium/policies/managed/policies.json"
    dest: "/etc/opt/chrome/policies/managed/policies.json"
    mode: 0644
  when: ansible_architecture == 'x86_64'
