#firefox eta chromeren politikak ezarri. Debian eta Ubuntu
---
- name: Firefox-en politikak ezarri. Debian.
  copy:
    src: "{{ role_path }}/files/policies.json.firefox"
    dest: "/usr/share/firefox-esr/distribution/policies.json"
    mode: 0644
  when: ansible_distribution == 'Debian'

- name: Firefox-en politikak ezarri. Ubuntu.
  copy:
    src: "{{ role_path }}/files/policies.json.firefox"
    dest: "/usr/lib/firefox/distribution/policies.json"
    mode: 0644
  when: ansible_distribution == 'Ubuntu'

- name: Chrome politikak ezarri.
  copy:
    src: "{{ role_path }}/files/policies.json.chromium"
    dest: "/etc/opt/chrome/policies/managed/policies.json"
    mode: 0644
  when: ansible_distribution == 'Ubuntu'

- name: Chromium politikak ezarri.
  copy:
    src: "{{ role_path }}/files/policies.json.chromium"
    dest: "/etc/chromium/policies/managed/policies.json"
    mode: 0644
  when: ansible_distribution == 'Debian'

