#smart arbela digitalarentzako erabiltzailea sortu. besteek bere izenean irekiko dute programa.
---
- name: '"smart" erabiltzailea sortu.'
  user:
    name: smart
    shell: /bin/bash
    createhome: yes
    home: /opt/smartuser

- name: Smart arbela erabili dezaketenak.
  template:
    src: "{{ role_path }}/templates/smart.j2"
    dest: "/etc/sudoers.d/smart"
    mode: 0440

- name: smartsudo scripta kopiatu.
  copy:
    src: "{{ role_path }}/files/smartsudo"
    dest: "/usr/local/bin/smartsudo"
    mode: 0755

- name: smart abiarazlea kopiatu.
  copy:
    src: "{{ role_path }}/files/smartboard.desktop"
    dest: "/usr/share/applications/smartboard.desktop"
    mode: 0644

- name: whiskermenu aldatu.
  copy:
    src: "{{ role_path }}/files/whiskermenu-1.rc"
    dest: "/etc/xdg/xfce4/panel/whiskermenu-1.rc"
    mode: 0644

