#smart arbela digitalarentzako erabiltzailea sortu. besteek bere izenean irekiko dute programa.
---
- name: '"smart" erabiltzailea sortu.'
  user:
    name: smart
    shell: /bin/bash
    createhome: yes
    home: /opt/smartuser

- name: Smart arbela erabili dezaketenak.
  template:
    src: "{{ role_path }}/templates/smart.j2"
    dest: "/etc/sudoers.d/smart"
    mode: 0440

- name: smartsudo scriptak kopiatu.
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
  with_items:
     - "smartsudo"

- name: smartsudo abiarazleak kopiatu.
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/usr/share/applications/{{ item }}"
    mode: 0644
  with_items:
     - "smartboard.desktop"

- name: whiskermenu aldatu.
  copy:
    src: "{{ role_path }}/files/whiskermenu-1.rc"
    dest: "/etc/xdg/xfce4/panel/whiskermenu-1.rc"
    mode: 0644
