#smart arbela digitalarentzako erabiltzailea sortu. besteek bere izenean irekiko dute programa
---
- name: winezdabil scripta kopiatu.
  copy:
    src: "{{ role_path }}/files/usr/local/bin/winezdabil"
    dest: "/usr/local/bin/winezdabil"
    mode: 0755

- name: winezdabil abiarazlea kopiatu.
  copy:
    src: "{{ role_path }}/files/usr/share/applications/winezdabil.desktop"
    dest: "/usr/share/applications/winezdabil.desktop"
    mode: 0644
