#smart arbela digitalarentzako erabiltzailea sortu. besteek bere izenean irekiko dute programa
---
- name: '"wine" erabiltzailea sortu.'
  user:
    name: wine
    shell: /bin/bash
    createhome: yes
    home: /opt/wine

- name: wine erabili dezaketenak.
  template:
    src: "{{ role_path }}/templates/wine.j2"
    dest: "/etc/sudoers.d/wine"
    mode: 0440

- name: winesudo scripta kopiatu.
  copy:
    src: "{{ role_path }}/files/winesudo"
    dest: "/usr/local/bin/winesudo"
    mode: 0755

- name: winezdabil scripta kopiatu.
  copy:
    src: "{{ role_path }}/files/winezdabil"
    dest: "/usr/local/bin/winezdabil"
    mode: 0755

- name: winezdabil abiarazlea kopiatu.
  copy:
    src: "{{ role_path }}/files/winezdabil.desktop"
    dest: "/usr/share/applications/winezdabil.desktop"
    mode: 0644
