#gure inpresorak konfiguratu
---
- name: Gure inpresoren zerbitzaria gehitu.
  lineinfile:
    path: "/etc/cups/cups-browsed.conf"
    insertafter: '# Use BrowsePoll to poll a particular CUPS server'
    line: 'BrowsePoll 10.10.0.21'

- name: Bakarrik gure inpresoren zerbitzaria baimendu.
  replace:
    dest: "/etc/cups/cups-browsed.conf"
    regexp: '# BrowseAllow All'
    replace: 'BrowseAllow 10.10.0.21'

- name: Bakarrik izena erakutsi
  replace:
    dest: "/etc/cups/cups-browsed.conf"
    regexp: '# LocalQueueNamingRemoteCUPS RemoteName'
    replace: 'LocalQueueNamingRemoteCUPS RemoteName'

- name: Hasieran defektuzko inpresora konfiguratu.
  copy:
    src: "{{ role_path }}/files/usr/share/applications/inpresora.desktop"
    dest: /etc/xdg/autostart/inpresora.desktop
    mode: 0644

#https://unix.stackexchange.com/questions/496982/restarting-systemd-service-only-as-a-specific-user
