#gure dns zerbitzarira apuntatu
---
- name: Fitxategi zaharraren kopia egin.
  copy:
    src: "/etc/systemd/resolved.conf"
    dest: "/etc/systemd/resolved.conf.backup"
    mode: 0644
    remote_src: yes

- name: gure dns zerbitzaria jarri 
  replace:
    dest: /etc/systemd/resolved.conf
    regexp: '#DNS='
    replace: 'DNS=192.168.0.245'

- name: gure domeinua jarri 
  replace:
    dest: /etc/systemd/resolved.conf
    regexp: '#Domains='
    replace: 'Domains=lizarra-ikastola.org ikastola.local'

- name: kendu dhclient zerbitzua
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/systemd/system/dhclient.service"
    - "/etc/systemd/system/multi-user.target.wants/dhclient.service"
