#internetetik deskargatutako letra batzuk eskuz instalatu
---
- name: Letrentzako karpetak sortu.
  file:
    path: "/usr/local/share/fonts/{{ item }}"
    state: directory
  with_items:
    - "sourcesanspro"
    - "escolar"
    - "gilda"
    - "architect"
    - "Symbol"
    - "BookSymbol"
    - "DFMoFunkyFreshSymbolsLETPlain"
    - "webdings"
    - "wingding"

- name: Letrak erauzi
  unarchive:
    src: "{{ role_path }}/files/usr/local/share/fonts/{{ item }}.zip"
    dest: "/usr/local/share/fonts/{{ item }}"
  with_items:
    - "sourcesanspro"
    - "escolar"
    - "gilda"
    - "architect"
    - "Symbol"
    - "BookSymbol"
    - "DFMoFunkyFreshSymbolsLETPlain"
    - "webdings"
    - "wingding"
