#anydesk remote viewer instalatzeko
---
- name: Dependentziak instalatu
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - libgtkglext1
    - libminizip1 
    - libpangox-1.0-0

- name: Programa instalatu
  apt:
    deb: "https://download.anydesk.com/linux/anydesk_6.1.1-1_amd64.deb"

- name: Zerbitzua kendu
  file:
    path: "/etc/systemd/system/multi-user.target.wants/anydesk.service"
    state: absent
