#txanelako jokoak kargatu
---
- name: jokoen scriptak kopiatu
  copy:
    src: "{{ role_path }}/files/usr/local/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
  with_items:
    - urdintxo
    - berraitona1

- name: jokoen abiarazleak kopiatu
  copy:
    src: "{{ role_path }}/files/usr/local/share/applications/{{ item }}"
    dest: "/usr/local/share/applications/{{ item }}"
    mode: 0644
  with_items:
    - urdintxo.desktop
    - berraitona1.desktop

- name: "sortu jokoentzako karpetak"
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
  with_items:
    - /opt/jokoak/berraitonarenmuseoa1
    - /opt/jokoak/urdintxoetapox
    - /opt/jokoak/wine

#wget -O berraitona1.squashfs "https://drive.google.com/uc?export=download&confirm=t&id=1090sUvbpkfvvUINMrpmjVhyuCaow9LIT"              
#wget -O urdintxo.squashfs "https://drive.google.com/uc?export=download&confirm=t&id=1ZZ85_77Zr5ZHKF1secSqFyLg0f4peFg7"
#wget -O wineberria.squashfs "https://drive.google.com/uc?export=download&confirm=t&id=1CRGRmv37fN3NnB-qQpm1SOre7KpNe-gv"
#- name: Jokoak eta wine karpeta deskargatu
#  get_url:
#    url: "{{ item.src }}"
#    dest: "{{ item.dest }}"
#  with_items:
#     - { src: "https://drive.google.com/uc?export=download&confirm=t&id=1CRGRmv37fN3NnB-qQpm1SOre7KpNe-gv", dest: "/opt/jokoak/wineberria.squashfs" }
#     - { src: "https://drive.google.com/uc?export=download&confirm=t&id=1ZZ85_77Zr5ZHKF1secSqFyLg0f4peFg7", dest: "/opt/jokoak/urdintxo.squashfs" }
#     - { src: "https://drive.google.com/uc?export=download&confirm=t&id=1090sUvbpkfvvUINMrpmjVhyuCaow9LIT", dest: "/opt/jokoak/berraitona1.squashfs" }

- name: jokoen scriptak kopiatu
  copy:
    src: "/home/{{ item }}"
    dest: "/opt/jokoak/{{ item }}"
    mode: 0644
  with_items:
    - urdintxo.squashfs
    - berraitona1.squashfs
    - wineberria.squashfs

- name: "sortu winerentzako karpetak"
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
  with_items:
    - /etc/skel/.wine
    - /etc/skel/.wine-upper
    - /etc/skel/.wine-workdir

- name: pam_mount konfiguratu
  lineinfile:
    path: /etc/security/pam_mount.conf.xml
    insertafter: '<!-- Volume definitions -->'
    line: '{{ item }}'
  with_items:
    - '<volume sgrp="Lizarra Ikastola" path="/home/%(USER)/.wine" mountpoint="/home/%(USER)/.wine" options="lowerdir=/opt/jokoak/wine,upperdir=/home/%(USER)/.wine-upper,workdir=/home/%(USER)/.wine-workdir" fstype="overlay"/>'
    - '<volume sgrp="Lizarra Ikastola" path="/opt/jokoak/wineberria.squashfs" mountpoint="/opt/jokoak/wine" fstype="squashfs"/>'
    - '<volume sgrp="Lizarra Ikastola" path="/opt/jokoak/berraitona1.squashfs" mountpoint="/opt/jokoak/berraitonarenmuseoa1" fstype="squashfs"/>'
    - '<volume sgrp="Lizarra Ikastola" path="/opt/jokoak/urdintxo.squashfs" mountpoint="/opt/jokoak/urdintxoetapox" fstype="squashfs"/>'

- name: home fitxategia tmpfs bezala muntatu
  lineinfile:
    path: /etc/fstab
    line: '{{ item }}'
  with_items:
    - 'none /home tmpfs defaults 0 0'

#https://askubuntu.com/questions/323437/how-to-prevent-wine-from-adding-file-associations
#/home/auto/.wine overlay /home/auto/.wine upperdir=/home/auto/.wine-upper,workdir=/home/auto/.wine-workdir
