#txanelako jokoak kargatu
---
- name: urdintxo eta pox scripta kopiatu
  copy:
    src: "{{ role_path }}/files/usr/local/bin/urdintxo"
    dest: "/usr/local/bin/urdintxo"
    mode: 0755

- name: urdintxo eta pox abiarazlea kopiatu
  copy:
    src: "{{ role_path }}/files/usr/local/share/applications/urdintxo.desktop"
    dest: "/usr/local/share/applications/urdintxo.desktop"
    mode: 0644

- name: "sortu jokoentzako karpeta"
  file:
    path: /opt/jokoak
    state: directory
    mode: 0755

- name: "sortu winerentzako karpetak"
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
  with_items:
    - /etc/skel/.wine
    - /etc/skel/.wine-upper
    - /etc/skel/.wine-workdir

- name: pam_mount konfiguratu
  lineinfile:
    path: /etc/security/pam_mount.conf.xml
    insertafter: '<!-- Volume definitions -->'
    line: '{{ item }}'
  with_items:
    - '<volume sgrp="Lizarra Ikastola" server="192.168.0.117" path="/home/jokoak" mountpoint="/opt/jokoak" fstype="nfs"/>'
#    - '<volume sgrp="Lizarra Ikastola" fstype="overlay" path="/home/%(USER)/.wine" mountpoint="/home/%(USER)/.wine" options="lowerdir=/opt/jokoak/wine,upperdir=/home/%(USER)/.wine-upper,workdir=/home/%(USER)/.wine-workdir"/>'

