#txanelako jokoak kargatu
---
- name: jokoen scriptak kopiatu
  copy:
    src: "{{ role_path }}/files/usr/local/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
  with_items:
    - urdintxo
    - berraitona1

- name: jokoen abiarazleak kopiatu
  copy:
    src: "{{ role_path }}/files/usr/local/share/applications/{{ item }}"
    dest: "/usr/local/share/applications/{{ item }}"
    mode: 0644
  with_items:
    - urdintxo.desktop
    - berraitona1.desktop

- name: "sortu jokoentzako karpeta"
  file:
    path: /opt/jokoak
    state: directory
    mode: 0755

- name: "sortu winerentzako karpetak"
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
  with_items:
    - /etc/skel/.wine
    - /etc/skel/.wine-upper
    - /etc/skel/.wine-workdir

- name: pam_mount konfiguratu
  lineinfile:
    path: /etc/security/pam_mount.conf.xml
    insertafter: '<!-- Volume definitions -->'
    line: '{{ item }}'
  with_items:
    - '<volume sgrp="Lizarra Ikastola" path="/home/%(USER)/.wine" mountpoint="/home/%(USER)/.wine" options="lowerdir=/opt/jokoak/wine,upperdir=/home/%(USER)/.wine-upper,workdir=/home/%(USER)/.wine-workdir" fstype="overlay"/>'
    - '<volume sgrp="Lizarra Ikastola" server="192.168.0.117" path="/home/jokoak" mountpoint="/opt/jokoak" fstype="nfs"/>'

- name: home fitxategia tmpfs bezala muntatu
  lineinfile:
    path: /etc/fstab
    line: '{{ item }}'
  with_items:
    - 'none /home tmpfs defaults 0 0'

#https://askubuntu.com/questions/323437/how-to-prevent-wine-from-adding-file-associations
