#txanelako jokoak kargatu
---
- name: jokoen scriptak kopiatu
  copy:
    src: "{{ role_path }}/files/usr/local/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
  with_items:
    - urdintxo
    - berraitona1

- name: jokoen abiarazleak kopiatu
  copy:
    src: "{{ role_path }}/files/usr/local/share/applications/{{ item }}"
    dest: "/usr/local/share/applications/{{ item }}"
    mode: 0644
  with_items:
    - urdintxo.desktop
    - berraitona1.desktop

- name: "sortu jokoentzako karpeta"
  file:
    path: /opt/jokoak/wine
    state: directory
    mode: 0755

- name: "sortu winerentzako karpetak"
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
  with_items:
    - /etc/skel/.wine
    - /etc/skel/.wine-upper
    - /etc/skel/.wine-workdir

- name: Quicktime instalatzaileak jaitsi
  get_url:
    url: "https://www.dropbox.com/s/p0jaxpwnuxujeh0/QuickTime.msi?dl=1"
    dest: "/opt/jokoak/Quicktime.msi"
    mode: '0644'

- name: Quicktime instalatzaileak jaitsi
  get_url:
    url: "https://www.dropbox.com/s/99u6g4z2unhzo5z/AppleApplicationSupport.msi?dl=1"
    dest: "/opt/jokoak/AppleApplicationSupport.msi"
    mode: '0644'

#- name: Quicktime instalatu
#  command: "/usr/bin/msiexec /i /q {{ item }}"
#  args:
#    chdir: /opt/jokoak
#  with_items:
#    - QuickTime.msi
#    - AppleApplicationSupport.msi

- name: pam_mount konfiguratu
  lineinfile:
    path: /etc/security/pam_mount.conf.xml
    insertafter: '<!-- Volume definitions -->'
    line: '{{ item }}'
  with_items:
    - '<volume sgrp="Lizarra Ikastola" path="/home/%(USER)/.wine" mountpoint="/home/%(USER)/.wine" options="lowerdir=/opt/jokoak/wine,upperdir=/home/%(USER)/.wine-upper,workdir=/home/%(USER)/.wine-workdir" fstype="overlay"/>'
#    - '<volume sgrp="Lizarra Ikastola" server="192.168.0.117" path="/diska/home/jokoak" mountpoint="/opt/jokoak" fstype="nfs"/>'

- name: home fitxategia tmpfs bezala muntatu
  lineinfile:
    path: /etc/fstab
    line: '{{ item }}'
  with_items:
    - 'none /home tmpfs defaults 0 0'

#https://askubuntu.com/questions/323437/how-to-prevent-wine-from-adding-file-associations
