#ikastolako ordenagailuetan konfigurazioa "izoztu" eta sudo konfiguratu
---

  - include: 01-kiosk.yml

  - include: 02-nabigatzaileak.yml

  - include: 03-sudo.yml

  - include: 04-smart.yml
    when: ansible_architecture == 'x86_64'

  - include: 05-wine.yml

  - include: 06-inpresorak.yml

  - include: 08-letrak.yml

  - include: 09-ocs.yml

#  - include: 10-ovirt.yml

  - include: 11-anydesk.yml
    when: ansible_distribution == 'Debian'

  - include: 12-jokoak.yml
