---
- name: Dependentziak instalatu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apache2
    - php
    - php-gd
    - php-ldap
    - php-mbstring
    - smarty3
    - unzip

#https://ltb-project.org/debian/stable/pool/main/l/ltb-project-self-service-password/self-service-password_1.4.3-1_all.deb
- name: SSP deskargatu eta instalatu.
  unarchive:
    src: https://github.com/ltb-project/self-service-password/archive/master.zip
    dest: /usr/share
    remote_src: yes

#- name: Apache konfiguratu.
#  lineinfile:
#    dest: /etc/apache2/sites-available/000-default.conf
#    regexp: 'DocumentRoot /var/www/html'
#    line: 'DocumentRoot /var/www/html/self-service-password-master'
#    backrefs: yes

- name: Apache konfiguratu.
  copy:
    src: "{{ role_path }}/files/self-service-password.conf"
    dest: "/etc/apache2/sites-available/self-service-password.conf"
    mode: 0644

- name: Apache berrabiarazi.
  systemd:
    state: restarted
    daemon_reload: yes
    name: apache2

- name: Konfigurazio zaharra gorde.
  copy:
    src: /usr/share/self-service-password-master/conf/config.inc.php
    dest: /usr/share/self-service-password-master/conf/config.inc.php.bak
    mode: 0644

- name: Gure konfigurazioa jarri.
  template:
    src: "{{ role_path }}/templates/config.j2"
    dest: /usr/share/self-service-password-master/conf/config.inc.php
    owner: root
    mode: '0644'

- name: Smarty-rentzako karpetak sortu.
  file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0755
  with_items:
     - "/var/cache/self-service-password/cache"
     - "/var/cache/self-service-password/templates_c"
