#!/bin/bash
# Script to do numeric comparisons
var1=`date +%y%m%d`
var2=`date +%y%m%d -d yesterday`
if [ $var2 -gt $var1 ]
    then
        echo "$var2 is greater than $var1"
    else
        echo "$var1 is greater than $var2"
fi

