---
- hosts: all
  connection: local
  roles:
    - debootstrap

- hosts: all
  connection: chroot
  vars:
    ansible_host: "{{ inventory_hostname }}/live/squashfs-root"
  tasks:
    - include: prestatu.yml
    - include_role:
        name: zerbitzaria
    - include: irten.yml

- hosts: gelak, tutoretzak, portatilak
  connection: chroot
  vars:
    ansible_host: "{{ inventory_hostname }}/live/squashfs-root"
  tasks:
    - include: prestatu.yml
    - include_role:
        name: idazmaia
    - include_role:
        name: realmd
    - include: irten.yml

- hosts: gelak
  connection: chroot
  vars:
    ansible_host: "{{ inventory_hostname }}/live/squashfs-root"
  tasks:
    - include: prestatu.yml
    - include_role:
        name: smart1
    - include: irten.yml

- hosts: portatilak
  connection: chroot
  vars:
    ansible_host: "{{ inventory_hostname }}/live/squashfs-root"
  tasks:
    - include: prestatu.yml
    - include_role:
        name: portatila
    - include: irten.yml

- hosts: all
  connection: local
  roles:
    - squash
