---
- hosts: all
  connection: chroot
  vars:
    ansible_host: "{{ inventory_hostname }}/live/squashfs-root"
  tasks:
    - include: prestatu.yml
    - include_role:
        name: zerbitzaria
    - include: irten.yml
