---
- hosts: all
  connection: local
  roles:
    - common

- hosts: all
  connection: chroot
  tasks:
    - include: prestatu.yml
    - include_role:
        name: zerbitzaria
    - include_role:
        name: idazmaia
    - include_role:
        name: smart
    - include: irten.yml

- hosts: all
  connection: local
  vars:
    - tftp: "/home/irudiak/tftp"
  roles:
    - squash
