---
- hosts: all
  connection: local
  roles:
    - common

- hosts: all
  connection: chroot
  tasks:
    - include: prestatu.yml
    - include_role:
        name: zerbitzaria
    - include: irten.yml

- hosts: gelak, tutoretzak, portatilak
  connection: chroot
  tasks:
    - include: prestatu.yml
    - include_role:
        name: idazmaia
    - include_role:
        name: realmd
    - include: irten.yml

- hosts: gelak
  connection: chroot
  tasks:
    - include: prestatu.yml
    - include_role:
        name: smart
    - include: irten.yml

- hosts: fitxaje
  connection: chroot
  tasks:
    - include: prestatu.yml
    - include_role:
        name: fitxaje
    - include: irten.yml

- hosts: portatilak, fitxaje
  connection: chroot
  tasks:
    - include: prestatu.yml
    - include_role:
        name: portatila
    - include: irten.yml

- hosts: all
  connection: local
  vars:
    - tftp: "/home/irudiak/tftp/{{ izen_motza }}"
  roles:
    - squash
