#!/bin/sh
#paketeak="live-boot linux-image-amd64 ipxe parted squashfs-tools pv syslinux console-data console-setup extlinux keyboard-configuration acpi-support locales"
standard="apt-listchanges bash-completion bzip2 dbus dnsutils file gettext-base groff-base hdparm libc-l10n libpam-systemd lsof man-db manpages mime-support p
ciutils traceroute ucf xz-utils atool"
passwd 
echo blacklist pcspkr > /etc/modprobe.d/nobeep.conf
prestatu
#dpkg-reconfigure locales
locale-gen es_ES.UTF-8
locale-gen eu_ES.UTF-8
sed -i 's/XKBLAYOUT="us"/XKBLAYOUT="es"/' squashfs-root/etc/default/keyboard
echo "LANGUAGE=eu:es" >> /etc/default/locale
dpkg-reconfigure tzdata
tasksel --new-install install standard
apt-get install $standard
katxe
irten
