---

- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:

  - name: print out the hostname of target
    command: hostname
  
  - name: update the apt package index i.e. apt-get update
    apt: update_cache=yes

  - name: upgrade system packages i.e. apt-get upgrade
    apt: upgrade=yes

  - name: instalatu minimoa
    command: tasksel --new-install install standard

  - name: instalatu xfce
    command: apt-get -y install task-xfce-desktop
