---
- hosts: sortu
  connection: local
  vars:
    - repo: http://mirrors.kernel.org/debian
    - include_packages: locales,lsb-release,openssh-server,python,python-apt,sudo,console-setup,keyboard-configuration

  tasks:
    - name: Instalazio berria sortu deboostrap erabiliz
      command: /usr/sbin/debootstrap
               --arch={{ arch }}
               --include={{ include_packages }}
               {{ suite }} {{ inventory_hostname }}/live/squashfs-root {{ repo }}

