---
- name: Paketeak instalatu
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - dnsmasq
    - nfs-kernel-server
    - python-distutils-extra
    - python3-distutils-extra

- name: dnsmasq konfigurazioa kopiatzen
  template:
    src: "{{ role_path }}/templates/etc/dnsmasq.d/custom.j2"
    dest: "/etc/dnsmasq.d/custom"
    mode: 0644

- name: Sortu irudien karpeta
  file:
    path: "{{ tftp_root }}"
    state: directory
    mode: 0755

- name: Irudien karpeta exportatu
  blockinfile:
    dest: "/etc/exports"
    block: |
     {{ tftp_root }}       *(ro,async,no_subtree_check)

- name: dnsmasq berrabiarazi
  service:
    name: dnsmasq
    state: restarted

- name: nfs berrabiarazi
  service:
    name: nfs-kernel-server
    state: restarted
