---
- name: Paketeak instalatu
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - dnsmasq
    - nfs-kernel-server
    - debootstrap
    - squashfs-tools
    - pxelinux
    - python-distutils-extra
    - python3-distutils-extra

- name: dnsmasq konfigurazioa kopiatzen
  copy:
    src: "{{ role_path }}/files/etc/dnsmasq.d/custom"
    dest: "/etc/dnsmasq.d/custom"
    mode: 0644

- name: Sortu irudien karpeta
  file:
    path: /home/irudiak/tftp/pxelinux.cfg
    state: directory
    mode: 0755

- name: Irudien karpeta exportatu
  blockinfile:
    dest: "/etc/exports"
    block: |
     /home/irudiak       *(ro,async,no_subtree_check)

- name: pxelinux.0 kopiatzen
  copy:
    src: "/usr/lib/PXELINUX/pxelinux.0"
    dest: "/home/irudiak/tftp/pxelinux.0"
    mode: 0644

- name: libutil.c32 kopiatzen
  copy:
    src: "/usr/lib/syslinux/modules/bios/libutil.c32"
    dest: "/home/irudiak/tftp/libutil.c32"
    mode: 0644

- name: ldlinux.c32 kopiatzen
  copy:
    src: "/usr/lib/syslinux/modules/bios/ldlinux.c32"
    dest: "/home/irudiak/tftp/ldlinux.c32"
    mode: 0644

- name: menu.c32 kopiatzen
  copy:
    src: "/usr/lib/syslinux/modules/bios/menu.c32"
    dest: "/home/irudiak/tftp/menu.c32"
    mode: 0644

- name: libcom32.c32 kopiatzen
  copy:
    src: "/usr/lib/syslinux/modules/bios/libcom32.c32"
    dest: "/home/irudiak/tftp/libcom32.c32"
    mode: 0644

- name: syslinux.c32 kopiatzen
  copy:
    src: "/usr/lib/syslinux/modules/bios/syslinux.c32"
    dest: "/home/irudiak/tftp/syslinux.c32"
    mode: 0644

- name: pxelinux default kopiatzen
  copy:
    src: "{{ role_path }}/files/pxelinux.cfg"
    dest: "/home/irudiak/tftp/pxelinux.cfg/default"
    mode: 0644

- name: dnsmasq berrabiarazi
  service:
    name: dnsmasq
    state: restarted

- name: nfs berrabiarazi
  service:
    name: nfs-kernel-server
    state: restarted
