---

  - name: LDAP konexiorako paketeak
    apt:
      name: "{{ packages }}"
    vars:
      packages:
       - realmd
       - libpam-mount 
       - cifs-utils

  - name: Ensure the default Apache port is 8080
    lineinfile:
      path: /etc/sssd/sssd.conf
      regexp: '^Listen '
      insertafter: '[sssd]'
      line: 'default_domain_suffix = USERS.EXAMPLE.COM'

  - name: erabiltzaileak lehen aldiz sartzean home karpeta sortu
    replace:
      dest: /usr/share/pam-configs/mkhomedir
      regexp: 'Default: no'
      replace: 'Default: yes'

  - name: pam_mount konfiguratzen
    copy:
      src: "{{ role_path }}/files/etc/security/pam_mount.conf.xml"
      dest: "/etc/security/pam_mount.conf.xml"
      mode: 0644

  - name: pam-auth-update
    command: pam-auth-update --package --enable mkhomedir
    args:
      warn: no
