#ordenagailua pxe eta nfs zerbitzari gixa konfiguratu
---
- name: dnsmasq eta nfs instalatu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - dnsmasq
    - nfs-kernel-server
    - python-distutils-extra
    - python3-distutils-extra

- name: aptcacher eta avahi instalatu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-cacher-ng
    - avahi-daemon

- name: dnsmasq konfiguratu.
  template:
    src: "{{ role_path }}/templates/etc/dnsmasq.d/custom.j2"
    dest: "/etc/dnsmasq.d/custom"
    mode: 0644

- name: tftp-root karpeta sortu.
  file:
    path: "{{ tftp_root }}"
    state: directory
    mode: 0755

- name: tftp-root nfs-rekin partekatu.
  template:
    src: "{{ role_path }}/templates/etc/exports.j2"
    dest: "/etc/exports"
    mode: 0644

- name: dnsmasq zerbitzua berrabiarazi.
  service:
    name: dnsmasq
    state: restarted

- name: nfs zerbitzua berrabiarazi.
  service:
    name: nfs-kernel-server
    state: restarted
