#ipxe instalatu uefi eta bios bezeroentzat gure menu pertsonalarekin konpilatzen du
---
- name: git eta build-essential instalatu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - git
    - build-essential
    - liblzma-dev

- name: ipxe karpeta sortu.
  file:
    path: "{{ tftp_root }}/ipxe"
    state: directory
    mode: 0755

- name: embed.ipxe fitxategia prestatu.
  template:
    src: "{{ role_path }}/templates/tftproot/ipxe/embed.j2"
    dest: "{{ tftp_root }}/ipxe/embed.ipxe"
    mode: 0644

- name: default.ipxe fitxategia prestatu.
  template:
    src: "{{ role_path }}/templates/tftproot/ipxe/default.j2"
    dest: "{{ tftp_root }}/ipxe/default.ipxe"
    mode: 0644

- name: ipxe deskargatu
  git:
    repo: 'https://github.com/ipxe/ipxe'
    dest: "{{ tftp_root }}/ipxe/git"

- name: undionly.kpxe konpilatu. Denbora behar du.
  shell: cd {{ tftp_root }}/ipxe/git/src && make bin/undionly.kpxe EMBED={{ tftp_root }}/ipxe/embed.ipxe

- name: snponly.efi konpilatu. Denbora behar du.
  shell: cd {{ tftp_root }}/ipxe/git/src && make bin-x86_64-efi/snponly.efi EMBED={{ tftp_root }}/ipxe/embed.ipxe

- name: undionly.kpxe kopiatu.
  copy:
    src: "{{ tftp_root }}/ipxe/git/src/bin/undionly.kpxe"
    dest: "{{ tftp_root }}/ipxe/undionly.kpxe"
    mode: 0644

- name: snponly.efi kopiatu.
  copy:
    src: "{{ tftp_root }}/ipxe/git/src/bin-x86_64-efi/snponly.efi"
    dest: "{{ tftp_root }}/ipxe/snponly.efi"
    mode: 0644

- name: deskargak garbitu
  file:
    path: "{{ tftp_root }}/ipxe/git"
    state: absent
