#debian eta ubuntu instalatzaileak gehitu zerbitzarian
---
- name: amd64 instalatzailearen karpeta sortu. Ubuntu.
  file:
    path: "{{ tftp_root }}/installers/ubuntu/amd64"
    state: directory
    mode: 0755

- name: Jaitsi vmlinuz ubuntu 64
  get_url:
    url: http://archive.ubuntu.com/ubuntu/dists/focal/main/installer-amd64/current/legacy-images/netboot/ubuntu-installer/amd64/linux
    dest: "{{ tftp_root }}/installers/ubuntu/amd64/linux"
    checksum: sha256:dac0de38cc92570aea44cc287d0a525ad9fa7b6aa05c64cc021aac7f6f8b051d
    mode: 0644

- name: Jaitsi initrd ubuntu 64
  get_url:
    url: http://archive.ubuntu.com/ubuntu/dists/focal/main/installer-amd64/current/legacy-images/netboot/ubuntu-installer/amd64/initrd.gz
    dest: "{{ tftp_root }}/installers/ubuntu/amd64/initrd.gz"
    checksum: sha256:6e438d6d431fc36cd39da3ff64a87dae233f5bb5fb28ae5b2d34cde4d13142e8
    mode: 0644

- name: amd64 instalatzailearen karpeta sortu. Debian.
  file:
    path: "{{ tftp_root }}/installers/debian/amd64"
    state: directory
    mode: 0755

- name: Jaitsi vmlinuz debian 64
  get_url:
    url: http://ftp.nl.debian.org/debian/dists/buster/main/installer-amd64/current/images/netboot/debian-installer/amd64/linux
    dest: "{{ tftp_root }}/installers/debian/amd64/linux"
    checksum: sha256:80337fec1c7671d23d15b2a4a37281b23ea99647579739f294edc05912750991
    mode: 0644

- name: Jaitsi initrd debian 64
  get_url:
    url: http://ftp.nl.debian.org/debian/dists/buster/main/installer-amd64/current/images/netboot/debian-installer/amd64/initrd.gz
    dest: "{{ tftp_root }}/installers/debian/amd64/initrd.gz"
    checksum: sha256:d154789c7e63b14d34bffffdd85de253027a4cdea6c05a7e6ced7f22db675dcf
    mode: 0644

- name: i386 instalatzailearen karpeta sortu.
  file:
    path: "{{ tftp_root }}/installers/debian/i386"
    state: directory
    mode: 0755

- name: Jaitsi vmlinuz debian 32
  get_url:
    url: http://ftp.nl.debian.org/debian/dists/buster/main/installer-i386/current/images/netboot/debian-installer/i386/linux
    dest: "{{ tftp_root }}/installers/debian/i386/linux"
    checksum: sha256:7e9ebc83fe6e3a7f6005ec6f04e16c333f16e2f24350d3bc2321c7eebcb4c13b
    mode: 0644

- name: Jaitsi initrd debian 32
  get_url:
    url: http://ftp.nl.debian.org/debian/dists/buster/main/installer-i386/current/images/netboot/debian-installer/i386/initrd.gz
    dest: "{{ tftp_root }}/installers/debian/i386/initrd.gz"
    checksum: sha256:7571762e716a8f3663e749019b410edf68ab292a6d300339883fb59c4ed065ef
    mode: 0644
