#debian eta ubuntu instalatzaileak gehitu zerbitzarian
---
- name: Paketeak instalatu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - debian-installer-11-netboot-amd64
    - debian-installer-11-netboot-i386

- name: Instalatzaileen karpetak sortu.
  file:
    path: "{{ tftp_root }}/installers/debian/{{ item }}"
    state: directory
    mode: 0755
  with_items:
     - amd64
     - i386

- name: Instalatzaileak kopiatu.
  file:
    src: "/usr/lib/debian-installer/images/11/{{ item.arch }}/text/debian-installer/{{ item.arch }}/{{ item.name }}"
    dest: "{{ tftp_root }}/installers/debian/{{ item.arch }}/{{ item.name }}"
    state: link
  with_items:
     - { arch: 'i386', name: 'linux' }
     - { arch: 'i386', name: 'initrd.gz' }
     - { arch: 'amd64', name: 'linux' }
     - { arch: 'amd64', name: 'initrd.gz' }

- name: Firmwareak jaitsi.
  get_url:
    url: "http://cdimage.debian.org/cdimage/unofficial/non-free/firmware/stable/current/firmware.cpio.gz"
    dest: "{{ tftp_root }}/installers/debian/firmware.cpio.gz"
    mode: 0644

- name: Firmwareak dituen instalatzailea prestatu i386
  shell: cd {{ tftp_root }}/installers/debian/i386 && cat initrd.gz ../firmware.cpio.gz > initrdfirm.gz

- name: Firmwareak dituen instalatzailea prestatu amd64
  shell: cd {{ tftp_root }}/installers/debian/amd64 && cat initrd.gz ../firmware.cpio.gz > initrdfirm.gz


