#debian eta ubuntu instalatzaileak gehitu zerbitzarian
---
- name: amd64 instalatzailearen karpeta sortu. Ubuntu.
  file:
    path: "{{ tftp_root }}/installers/ubuntu/amd64"
    state: directory
    mode: 0755

- name: Jaitsi vmlinuz ubuntu 64
  get_url:
    url: http://archive.ubuntu.com/ubuntu/dists/focal/main/installer-amd64/current/legacy-images/netboot/ubuntu-installer/amd64/linux
    dest: "{{ tftp_root }}/installers/ubuntu/amd64/linux"
    checksum: sha256:dac0de38cc92570aea44cc287d0a525ad9fa7b6aa05c64cc021aac7f6f8b051d
    mode: 0644

- name: Jaitsi initrd ubuntu 64
  get_url:
    url: http://archive.ubuntu.com/ubuntu/dists/focal/main/installer-amd64/current/legacy-images/netboot/ubuntu-installer/amd64/initrd.gz
    dest: "{{ tftp_root }}/installers/ubuntu/amd64/initrd.gz"
    checksum: sha256:6e438d6d431fc36cd39da3ff64a87dae233f5bb5fb28ae5b2d34cde4d13142e8
    mode: 0644

- name: amd64 instalatzailearen karpeta sortu. Debian.
  file:
    path: "{{ tftp_root }}/installers/debian/amd64"
    state: directory
    mode: 0755

- name: Jaitsi vmlinuz debian 64
  get_url:
    url: http://ftp.nl.debian.org/debian/dists/bullseye/main/installer-amd64/current/images/netboot/debian-installer/amd64/linux
    dest: "{{ tftp_root }}/installers/debian/amd64/linux"
    checksum: sha256:d15fcd529715a366bb7178cc1b7d864ee8ea1fffd7e23bdf83582cb64e16f92f
    mode: 0644

- name: Jaitsi initrd debian 64
  get_url:
    url: http://ftp.nl.debian.org/debian/dists/bullseye/main/installer-amd64/current/images/netboot/debian-installer/amd64/initrd.gz
    dest: "{{ tftp_root }}/installers/debian/amd64/initrd.gz"
    checksum: sha256:b8186c51ab91436fb21e2a524cb0db339a28ae1ca71bf25d79889e1d3fd4803a
    mode: 0644

- name: i386 instalatzailearen karpeta sortu.
  file:
    path: "{{ tftp_root }}/installers/debian/i386"
    state: directory
    mode: 0755

- name: Jaitsi vmlinuz debian 32
  get_url:
    url: http://ftp.nl.debian.org/debian/dists/bullseye/main/installer-i386/current/images/netboot/debian-installer/i386/linux
    dest: "{{ tftp_root }}/installers/debian/i386/linux"
    checksum: sha256:33db1a39bf72037a7acfc42901a279385f2c66fe788a3ed06d210a6770f6e379
    mode: 0644

- name: Jaitsi initrd debian 32
  get_url:
    url: http://ftp.nl.debian.org/debian/dists/bullseye/main/installer-i386/current/images/netboot/debian-installer/i386/initrd.gz
    dest: "{{ tftp_root }}/installers/debian/i386/initrd.gz"
    checksum: sha256:367531ac5ddd3b6aa9ff53ba0a90ed37272d98594abe2e6da9b79f27f4d6da96
    mode: 0644
