#gure zerbitzaria live bezeroak sortzeko prestatu. debian bada, debootstrap berria jaitsi ubuntu sortzeko
---
- name: Beharrezko programak instalatu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - debootstrap
    - squashfs-tools
    - whois
    - zstd
#whois pasahitzak sortzeko erabiltzen dugu
#zstd debootstrap-ek erabiltzen du deb paketeak erauzteko

- name: customubuntu karpeta sortu.
  file:
    path: "{{ tftp_root }}/livecds/customubuntu"
    state: directory
    mode: 0755

- name: customdebian karpeta sortu.
  file:
    path: "{{ tftp_root }}/livecds/customdebian"
    state: directory
    mode: 0755

#- name: Install newer version of debootstrap
#  apt:
#    deb: "http://mirrors.kernel.org/ubuntu/pool/main/d/debootstrap/debootstrap_1.0.126+nmu1_all.deb"
