#gure zerbitzaria live bezeroak sortzeko prestatu
---
- name: Beharrezko programak instalatu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - debootstrap
    - squashfs-tools
    - whois
#whois pasahitzak sortzeko erabiltzen dugu

- name: customubuntu karpeta sortu.
  file:
    path: "{{ tftp_root }}/livecds/customubuntu"
    state: directory
    mode: 0755

- name: customdebian karpeta sortu.
  file:
    path: "{{ tftp_root }}/livecds/customdebian"
    state: directory
    mode: 0755

- name: focal focus debootstrap instalatu
  apt:
    deb: http://es.archive.ubuntu.com/ubuntu/pool/main/d/debootstrap/debootstrap_1.0.118ubuntu1_all.deb
