#windows instalatzailea gehitu gure zerbitzarian. ISO-a aparte jaitsi behar da
---
- name: wimtools instalatu
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - wimtools
    - cabextract
    - genisoimage

- name: winpe karpeta sortu
  file:
    path: "{{ tftp_root }}/windows"
    state: directory
    mode: 0755

- name: wimboot jaitsi eta erauzi
  unarchive:
    src: http://git.ipxe.org/releases/wimboot/wimboot-latest.tar.gz
    dest: "{{ tftp_root }}/windows"
    remote_src: yes

- name: wimboot kopiatu
  copy:
    src: "{{ tftp_root }}/windows/wimboot-2.6.0-signed/wimboot"
    dest: "{{ tftp_root }}/windows/wimboot"
    mode: 0644

- name: wimboot deskarga ezabatu
  file:
    path: "{{ tftp_root }}/windows/wimboot-2.6.0-signed"
    state: absent

- name: memdisk kopiatu
  copy:
    src: "/usr/lib/syslinux/memdisk"
    dest: "{{ tftp_root }}/windows/memdisk"
    mode: 0644
