#this task modifies original deb packages because they depend on old packages
---
- name: Extract deb packages.
  command: dpkg-deb -R /opt/smart/{{ item.deb }} /opt/smart/{{ item.dir }}
  args:
    warn: no
  with_items:
     - { deb: "smart-common_10.3.2171.1-1_i386.deb", dir: "common" }
     - { deb: "smart-hwr_11.3.2121.1-1_i386.deb", dir: "hwr" }
     - { deb: "smart-languagesetup_2.2.2060.4-1_i386.deb", dir: "language" }
     - { deb: "smart-product-drivers_11.3.2121.1-1_i386.deb", dir: "drivers" }
     - { deb: "smart-activation_1.1.2066.1-1_i386.deb", dir: "activation" }
     - { deb: "smart-gallerysetup_1.3.6235.1-1_i386.deb", dir: "gallery" }
     - { deb: "smart-notebook_11.0.7511.0-1_i386.deb", dir: "notebook" }

- name: Modify libcurl3 dependency
  replace:
    dest: "/opt/smart/{{ item }}/DEBIAN/control"
    regexp: 'libcurl3'
    replace: 'libcurl4'
  with_items:
     - common
     - language
     - drivers
     - activation
     - gallery
     - notebook

- name: Modify libnspr4 dependency
  replace:
    dest: "/opt/smart/{{ item }}/DEBIAN/control"
    regexp: 'libnspr4-0d'
    replace: 'libnspr4'
  with_items:
     - common
     - language
     - drivers
     - activation
     - gallery
     - notebook

- name: Remove smart-hw dependencies (libc6)
  replace:
    dest: /opt/smart/hwr/DEBIAN/control
    regexp: '^(.*)Depends:(.*)$'
    replace: 'Depends:'

- name: Build new deb packages.
  command: dpkg-deb -b /opt/smart/{{ item.dir }} /opt/smart/{{ item.deb }}
  args:
    warn: no
  with_items:
     - { deb: "01-smart-common.deb", dir: "common" }
     - { deb: "02-smart-hwr.deb", dir: "hwr" }
     - { deb: "03-smart-language.deb", dir: "language" }
     - { deb: "04-smart-drivers.deb", dir: "drivers" }
     - { deb: "05-smart-activation.deb", dir: "activation" }
     - { deb: "06-smart-gallery.deb", dir: "gallery" }
     - { deb: "07-smart-notebook.deb", dir: "notebook" }
