#this task installs newly created deb files
---
- name: Install packages
  apt:
    deb: "{{ packages }}"
  vars:
    packages:
    - /opt/smart/smart-common.deb
    - /opt/smart/smart-hwr.deb
    - /opt/smart/smart-language.deb
    - /opt/smart/smart-drivers.deb
    - /opt/smart/smart-activation.deb
    - /opt/smart/smart-gallery.deb
    - /opt/smart/smart-notebook.deb
