#this task installs newly created deb files
---
- name: Install packages
  apt:
    deb: "/opt/smart/{{ item }}"
  with_items:
    - 01-smart-common.deb
    - 02-smart-hwr.deb
    - 03-smart-language.deb
    - 04-smart-drivers.deb
    - 05-smart-activation.deb
    - 06-smart-gallery.deb
    - 07-smart-notebook.deb
