#this task installs newly created deb files
---
- name: Install packages
  apt:
    deb: "/opt/smart/{{ item }}"
  with_items:
    - smart-common.deb
    - smart-hwr.deb
    - smart-language.deb
    - smart-drivers.deb
    - smart-activation.deb
    - smart-gallery.deb
    - smart-notebook.deb
