#this task removes old and new installation deb files
- name: Clean installation files
  file:
    path: "/opt/smart"
    state: absent

- name: Remove official autostart programs
  file:
    path: /etc/xdg/autostart/{{ item }}
    state: absent
  with_items:
    - smart_1-_Service.desktop
    - smart_1-_Tools.desktop 

- name: Remove desktop files.
  file:
    path: "/usr/share/applications/{{ item }}"
    state: absent
  with_items:
    - smarttech-ControlPanel.desktop
    - smarttech-EssentialsForEducators.desktop
    - smarttech-gallery.desktop
    - smarttech-galleryitem.desktop
    - smarttech-GallerySetup.desktop
    - smarttech-LanguageSetup.desktop
    - smarttech-Magnifier.desktop
    - smarttech-notebook.desktop
    - smarttech-Orient.desktop
    - smarttech-Pointer.desktop
    - smarttech-ScreenCapture.desktop
    - smarttech-ScreenShade.desktop
    - smarttech-ScreenSpotlight.desktop
    - smarttech-SMARTBoardTools.desktop
    - smarttech-SMARTKeyboard.desktop

- name: Remove directory files.
  file:
    path: "/usr/share/desktop-directories/{{ item }}"
    state: absent
  with_items:
    - smarttech-software.directory
    - smarttech-software-drivers.directory
    - smarttech-software-notebook.directory
    - smarttech-software-tools.directory
    - smarttech-software-update.directory

- name: Copy my own smart commands.
  copy:
    src: "{{ role_path }}/files/usr/local/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
  with_items:
     - "smarttech-tools"
     - "smarttech-notebook"

- name: Copy my own smart launchers.
  copy:
    src: "{{ role_path }}/files/usr/share/applications/{{ item }}"
    dest: "/usr/share/applications/{{ item }}"
    mode: 0644
  with_items:
     - "smarttech-tools.desktop"
     - "smarttech-notebook.desktop"

