#This role installs smartboard software. It's an old program with old dependencies (all of them i386)
---
  - include: 01-depends.yml

  - include: 02-download.yml 

  - include: 03-modify.yml

#  - include: 04-install.yml 

#  - include: 05-clean.yml
