---
- name: localegen1
  lineinfile:
    dest: /etc/locale.gen
    regexp: '# eu_ES.UTF-8 UTF-8'
    line: 'eu_ES.UTF-8 UTF-8'
- name: localegen2
  lineinfile:
    dest: /etc/locale.gen
    regexp: '# es_ES.UTF-8 UTF-8'
    line: 'es_ES.UTF-8 UTF-8'
- name: update locales
  command: /usr/sbin/dpkg-reconfigure --frontend=noninteractive locales 
- name: set locale
  command: /usr/sbin/update-locale LANG=eu_ES.UTF-8 LANGUAGE=eu:es
