---
- name: Aldatu /etc/default/keyboard
  lineinfile:
    dest: /etc/default/keyboard
    regexp: 'XKBLAYOUT="us"'
    line: 'XKBLAYOUT="es"'
    backrefs: yes
- name: Dpkg-reconfigure keyboard-configuration
  command: /usr/sbin/dpkg-reconfigure --frontend=noninteractive keyboard-configuration
