#labwc lehio kudeatzailea konpilatu
---
- name: Begiratu instalatuta dagoen
  stat:
    path: "/usr/local/bin/labwc"
  register: labwc_bin

- name: Erabiltzeko dependentziak instalatu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - libcairo2
    - libdrm2
    - libegl1
    - libgles2
    - libinput10
    - libpangocairo-1.0-0
    - libpixman-1-0
    - libseat1
    - libvulkan1
    - libwayland-server0
    - libxcb-composite0
    - libxcb-icccm4
    - libxcb-render-util0
    - libxcb-render0
    - libxcb-res0
    - libxcb-xinput0
    - libxkbcommon0
    - xwayland
    - polkitd
  when: not labwc_bin.stat.exists

- name: Konpilatzeko ependentziak instalatu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - git
    - meson
    - libwlroots-dev
    - libvulkan-dev
    - glslang-tools
    - hwdata
    - xwayland
    - gettext
    - scdoc
    - cmake
    - libcairo2-dev
    - libpango1.0-dev
    - libxml2-dev
    - libglib2.0-dev
  when: not labwc_bin.stat.exists

- name: git kodea deskargatu
  git:
    repo: 'https://github.com/labwc/labwc'
    dest: /home/labwc
#    version: 0.6.1
  when: not labwc_bin.stat.exists

#meson setup build
- name: meson build
  command: "meson build"
  args:
    chdir: "/home/labwc"
  when: not labwc_bin.stat.exists

#meson compile -C build
- name: ninja -C build
  command: "ninja -C build"
  args:
    chdir: "/home/labwc"
  when: not labwc_bin.stat.exists

- name: ninja -C build install
  command: "ninja -C build install"
  args:
    chdir: "/home/labwc"
  when: not labwc_bin.stat.exists

- name: Kendu iturburu fitxategiak
  file:
    path: /home/fsearch
    state: absent
  when: not labwc_bin.stat.exists

- name: Konpilatzeko dependentziak kendu
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - git
    - meson
    - libwlroots-dev
    - libvulkan-dev
    - glslang-tools
    - hwdata
    - gettext
    - scdoc
    - cmake
    - libcairo2-dev
    - libpango1.0-dev
    - libxml2-dev
    - libglib2.0-dev
  when: not labwc_bin.stat.exists

- name: Sortu konfigurazioen karpetak.
  file:
    path: "/etc/xdg/labwc"
    state: directory
    mode: 0755
  when: not labwc_bin.stat.exists

- name: Jaitsi konfigurazio fitxategiak
  get_url:
    url: "https://raw.githubusercontent.com/labwc/labwc/master/docs/{{ item }}"
    dest: "/etc/xdg/labwc/{{ item }}"
    mode: 0644
  with_items:
    - "rc.xml.all"
    - "menu.xml"
    - "environment"
    - "autostart"
  when: not labwc_bin.stat.exists

- name: rc.xml izena aldatu
  command: mv /etc/xdg/labwc/rc.xml.all /etc/xdg/labwc/rc.xml
  when: not labwc_bin.stat.exists
