#euskerazko lokala konfiguratzen dugu. programa guztiak ez daudenez euskeratuta, bigarren hizkuntza gaztelera jartzen dugu
---
- name: Euskerako eta gaztelerako lokalak instalatu ubuntun
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - language-pack-es
    - language-pack-eu
  when: ansible_distribution == 'Ubuntu'

- name: Euskerako lokala gehitu.
  locale_gen:
    name: eu_ES.UTF-8
    state: present
#  register: euskara

- name: Gaztelerako lokala gehitu.
  locale_gen:
    name: es_ES.UTF-8
    state: present
#  register: gaztelera

- name: Dpkg-reconfigure locales.
  command: /usr/sbin/dpkg-reconfigure --frontend=noninteractive locales 
#  when: (euskara.changed  == true) or (gaztelera.changed  == true)

- name: Euskera lehen hizkuntza eta gaztelera bigarrena jarri.
  command: /usr/sbin/update-locale LANG=eu_ES.UTF-8 LANGUAGE=eu:es
#  when: (euskara.changed  == true) or (gaztelera.changed  == true)
