#Espainiar teklatua konfiguratu eta kontsolan UTF-8 erabili
---
- name: Espainiar teklatua jarri.
  lineinfile:
    dest: /etc/default/keyboard
    regexp: 'XKBLAYOUT="us"'
    line: 'XKBLAYOUT="es"'
    backrefs: yes

- name: UTF-8 erabili.
  lineinfile:
    dest: /etc/default/console-setup
    regexp: 'CHARMAP="ISO-8859-15"'
    line: 'CHARMAP="UTF-8"'
    backrefs: yes

- name: Dpkg-reconfigure keyboard-configuration
  command: /usr/sbin/dpkg-reconfigure --frontend=noninteractive keyboard-configuration

- name: Dpkg-reconfigure console-setup
  command: /usr/sbin/dpkg-reconfigure --frontend=noninteractive console-setup
