#Espainiar ordua jarri
---
  - name: Espainiar ordua jarri.
    file:
      src: /usr/share/zoneinfo/Europe/Madrid
      dest: /etc/localtime
      state: link

  - name: Dpkg-reconfigure tzdata
    command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata

