#Repositorioak gehitu
---
- name: Repositorio arruntak gehitu.
  apt_repository:
    repo: "{{ item  }} {{ repo }} {{ ansible_distribution_release }} {{ compo }}"
    state: present
  with_items:
    - "deb"
    - "deb-src"

- name: Eguneraketen repoa gehitu.
  apt_repository:
    repo: "{{ item  }} {{ repo }} {{ ansible_distribution_release }}-updates {{ compo }}"
    state: present
  with_items:
    - "deb"
    - "deb-src"

- name: Backports repoa gehitu.
  apt_repository:
    repo: "{{ item  }} {{ repo }} {{ ansible_distribution_release }}-backports {{ compo }}"
    state: present
  with_items:
    - "deb"
    - "deb-src"

- name: Debian security repoa.
  apt_repository:
    repo: "{{ item }} http://security.debian.org/debian-security {{ ansible_distribution_release }}/updates {{ compo }}"
    state: present
  with_items:
    - "deb"
    - "deb-src"
  when: ansible_distribution == 'Debian'

- name: Ubuntu security repoa.
  apt_repository:
    repo: "{{ item }} http://security.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security {{ compo }}"
    state: present
  with_items:
    - "deb"
    - "deb-src"
  when: ansible_distribution == 'Ubuntu'

- name: Sources.list orijinala kendu.
  file: 
    path="/etc/apt/sources.list"
    state=absent

- name: "apt-get update"
  apt:
    update_cache: yes
