#kernela instalatu Debian eta Ubuntu. speaker kentzen du ere (pitidoak)
---
- name: pcspeaker kendu.
  blockinfile:
    create: yes
    dest: "/etc/modprobe.d/nobeep"
    block: |
      blacklist pcspkr

- name: Debian 32 biteko kernela instalatu.
  apt: name=linux-image-5.4.0-0.bpo.4-686-pae
  when:
    - ansible_distribution == 'Debian'
    - ansible_architecture == 'i386'

- name: Debian 64 biteko kernela instalatu.
  apt: name=linux-image-5.4.0-0.bpo.4-amd64
  when:
    - ansible_distribution == 'Debian'
    - ansible_architecture == 'x86_64'

- name: Ubuntu 64 biteko kernela instalatu.
  apt: name=linux-image-generic
  when: ansible_distribution == 'Ubuntu'
