#kernela instalatu Debian eta Ubuntu. speaker kentzen du ere (pitidoak)
---
- name: pcspeaker kendu.
  lineinfile:
    create: yes
    path: "/etc/modprobe.d/nobeep.conf"
    line: "blacklist pcspkr"

- name: Debian 32 biteko kernela instalatu.
  apt: name=linux-image-686-pae
  when:
    - ansible_distribution == 'Debian'
    - ansible_architecture == 'i386'

- name: Debian 64 biteko kernela instalatu.
  apt: name=linux-image-amd64
  when:
    - ansible_distribution == 'Debian'
    - ansible_architecture == 'x86_64'

- name: Debian 32 biteko kernela instalatu BPO.
  apt: name=linux-image-5.9.0-0.bpo.5-686-pae
  when:
    - ansible_architecture == 'i386'
    - ansible_distribution_release == 'buster'

- name: Debian 64 biteko kernela instalatu BPO.
  apt: name=linux-image-5.9.0-0.bpo.5-amd64
  when:
    - ansible_architecture == 'x86_64'
    - ansible_distribution_release == 'buster'

- name: Ubuntu 64 biteko kernela instalatu.
  apt:
    name: "{{ packages }}"
#    install_recommends: no
  vars:
    packages:
    - linux-image-generic
    - lilo
#    - busybox-initramfs
#    - initramfs-tools
  when: ansible_distribution == 'Ubuntu'
