#erabiltzen ditugun programa batzuk gehitzeko
---
- name: "apt-get upgrade"
  apt:
    upgrade: dist

#tasksel --new-install install standard --debconf-apt-progress "--logfile hemen"
#- name: Instalazio minimoko atazak.
#  command: /usr/bin/tasksel --new-install install standard

- name: Tasksel paketea kopiatu
  copy:
    src: "{{ role_path }}/files/{{ tasksel }}"
    dest: "/root/tasksel.deb"
    mode: 0744

- name: Taskel standard instalatu.
  apt:
    deb: "/root/tasksel.deb"

- name: Instalatu programa extra batzuk.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - live-boot
    - screen
    - nfs-common
    - watchdog
    - syslinux
    - syslinux-common
    - syslinux-efi
    - extlinux
    - pv
    - wget
    - squashfs-tools
    - parted
    - atool
    - rar
    - p7zip-full
    - dosfstools
    - ipxe
    - network-manager
    - sudo
    - inxi
    - haveged
    - clonezilla
    - partclone
    - zstd
    - ntfs-3g

#Defektuz Ubuntun Network-manager-ek wifia baino ez du kudeatzen
- name: Network manager ethernet kudeatzeko erabili.
  file:
    path: /usr/lib/NetworkManager/conf.d/10-globally-managed-devices.conf
    state: absent
  when: ansible_distribution == 'Ubuntu'

- name: Firmware batzuk instalatu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - firmware-linux-nonfree
    - firmware-atheros
  when: ansible_distribution == 'Debian'
