#Tasksel standard ataza instalatzeko. Paketeen zerrenda lortzeko...
#tasksel --new-install install standard --debconf-apt-progress "--logfile paketeak"
---
- name: tasksel instalatu.
  apt:
    name: tasksel
    install_recommends: no

- name: Instalazio minimoko atazak.
  command: /usr/bin/tasksel --new-install install standard

#PPA erabiltzeko aukera. Autoupdate ere eskaintzen du.
- name: software-properties-common instalatu.
  apt:
    name: software-properties-common
    install_recommends: no
