#Tasksel standard ataza instalatzeko. Paketeen zerrenda lortzeko...
#tasksel --new-install install standard --debconf-apt-progress "--logfile paketeak"
---
- name: Instalazio minimoko atazak.
  command: /usr/bin/tasksel --new-install install standard
  when: ansible_distribution_release not in ['buster', 'focal']

#PPA erabiltzeko aukera. Autoupdate ere eskaintzen du.
- name: software-properties-common instalatu.
  apt:
    name: software-properties-common

- name: Tasksel standard ataza. Debian.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - apt-listchanges
    - bash-completion
    - bind9-host
    - bzip2
    - ca-certificates
    - dbus
    - debian-faq
    - distro-info-data
    - doc-debian
    - file
    - geoip-database
    - gettext-base
    - groff-base
    - hdparm
    - iso-codes
    - krb5-locales
    - libbind9-161
    - libcurl3-gnutls
    - libdbus-1-3
    - libdns1104
    - libedit2
    - libexpat1
    - libfstrm0
    - libgdbm-compat4
    - libgdbm6
    - libgeoip1
    - libgssapi-krb5-2
    - libicu63
    - libisc1100
    - libisccc161
    - libisccfg163
    - libk5crypto3
    - libkeyutils1
    - libkrb5-3
    - libkrb5support0
    - libldap-2.4-2
    - libldap-common
    - liblmdb0
    - liblockfile-bin
    - liblwres161
    - libmagic-mgc
    - libmagic1
    - libmpdec2
    - libnghttp2-14
    - libnss-systemd
    - libpam-systemd
    - libpci3
    - libpcre2-8-0
    - libperl5.28
    - libpipeline1
    - libprotobuf-c1
    - libpsl5
    - libpython-stdlib
    - libpython2-stdlib
    - libpython2.7-minimal
    - libpython2.7-stdlib
    - libpython3-stdlib
    - libpython3.7-minimal
    - libpython3.7-stdlib
    - libreadline7
    - librtmp1
    - libsasl2-2
    - libsasl2-modules
    - libsasl2-modules-db
    - libsqlite3-0
    - libssh2-1
    - libuchardet0
    - libx11-6
    - libx11-data
    - libxau6
    - libxcb1
    - libxdmcp6
    - libxext6
    - libxml2
    - libxmuu1
    - lsb-release
    - lsof
    - man-db
    - manpages
    - mime-support
    - ncurses-term
    - netcat-traditional
    - openssh-client
    - openssl
    - pciutils
    - perl
    - perl-modules-5.28
    - powermgmt-base
    - publicsuffix
    - python
    - python-apt-common
    - python-minimal
    - python2
    - python2-minimal
    - python2.7
    - python2.7-minimal
    - python3
    - python3-apt
    - python3-certifi
    - python3-chardet
    - python3-debconf
    - python3-debian
    - python3-debianbts
    - python3-httplib2
    - python3-idna
    - python3-minimal
    - python3-pkg-resources
    - python3-pycurl
    - python3-pysimplesoap
    - python3-reportbug
    - python3-requests
    - python3-six
    - python3-urllib3
    - python3.7
    - python3.7-minimal
    - reportbug
    - telnet
    - traceroute
    - ucf
    - wamerican
    - wget
    - xauth
    - xz-utils
  when: ansible_distribution_release == 'buster'

- name: Tasksel standard ataza. Ubuntu.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - accountsservice
    - apparmor
    - bash-completion
    - bind9-dnsutils
    - bind9-host
    - bind9-libs
    - bsdmainutils
    - busybox-static
    - command-not-found
    - cpio
    - dosfstools
    - ed
    - friendly-recovery
    - ftp
    - fuse
    - gettext-base
    - groff-base
    - hdparm
    - info
    - install-info
    - iptables
    - iputils-tracepath
    - irqbalance
    - iso-codes
    - krb5-locales
    - language-selector-common
    - libaccountsservice0
    - libcbor0.6
    - libdrm-common
    - libdrm2
    - libedit2
    - libfido2-1
    - libfuse2
    - libgdbm6
    - libgssapi-krb5-2
    - libip6tc2
    - libk5crypto3
    - libkeyutils1
    - libkrb5-3
    - libkrb5support0
    - liblmdb0
    - libmaxminddb0
    - libnetfilter-conntrack3
    - libnfnetlink0
    - libnftnl11
    - libntfs-3g883
    - libnuma1
    - libparted2
    - libpcap0.8
    - libpci3
    - libpipeline1
    - libplymouth5
    - libpng16-16
    - libpolkit-gobject-1-0
    - libpsl5
    - libuchardet0
    - libunwind8
    - libusb-1.0-0
    - libuv1
    - libx11-6
    - libx11-data
    - libxau6
    - libxcb1
    - libxdmcp6
    - libxext6
    - libxmuu1
    - lshw
    - lsof
    - ltrace
    - man-db
    - manpages
    - mtr-tiny
    - nano
    - ntfs-3g
    - openssh-client
    - parted
    - pci.ids
    - pciutils
    - plymouth
    - plymouth-theme-ubuntu-text
    - popularity-contest
    - powermgmt-base
    - psmisc
    - publicsuffix
    - python-apt-common
    - python3-apt
    - python3-commandnotfound
    - python3-distro-info
    - python3-distupgrade
    - python3-gdbm
    - python3-update-manager
    - rsync
    - strace
    - tcpdump
    - telnet
    - time
    - ubuntu-release-upgrader-core
    - ubuntu-standard
    - ufw
    - update-manager-core
    - usb.ids
    - usbutils
    - uuid-runtime
    - wget
    - xauth
  when: ansible_distribution_release == 'focal'
