#erabiltzen ditugun programa batzuk gehitzeko
---
- name: "apt-get upgrade"
  apt:
    upgrade: dist

- name: Instalatu programa extra batzuk.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - live-boot
    - screen
    - nfs-common
    - watchdog
    - syslinux
    - syslinux-common
    - syslinux-efi
    - extlinux
    - pv
    - wget
    - squashfs-tools
    - parted
    - atool
    - zip
    - unzip
    - rar
    - p7zip-full
    - dosfstools
    - ipxe
    - network-manager
    - sudo
    - inxi
    - haveged
    - clonezilla
    - partclone
    - zstd
    - ntfs-3g
    - cifs-utils
    - btrfs-progs
    - libncurses-dev
    - rsync

#Defektuz Ubuntun Network-manager-ek wifia baino ez du kudeatzen
- name: Network manager ethernet kudeatzeko erabili.
  file:
    path: /usr/lib/NetworkManager/conf.d/10-globally-managed-devices.conf
    state: absent
  when: ansible_distribution == 'Ubuntu'

- name: Firmware batzuk instalatu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - firmware-linux
    - firmware-linux-nonfree
  when: ansible_distribution == 'Debian'

- name: "sortu clonezilla-rentzako karpeta"
  file:
    path: /home/partimag
    state: directory
    mode: 0755

- name: Grub instalatu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - grub-pc

- name: Grub instalatu EFI
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - grub-efi-amd64-signed
  when: ansible_architecture == 'amd64'

