#erabiltzen ditugun programa batzuk gehitzeko
---
- name: "apt-get upgrade"
  apt:
    upgrade: dist

- name: Instalatu programa extra batzuk.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - rsync
    - screen
    - nfs-common
    - watchdog
    - wget
    - atool
    - zip
    - unzip
    - rar
    - p7zip-full
    - dosfstools
    - ipxe
    - network-manager
    - sudo
    - inxi
    - ntfs-3g
    - cifs-utils

- name: Firmware batzuk instalatu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - firmware-linux
    - firmware-linux-nonfree
  when: ansible_distribution == 'Debian'

- name: Grub instalatu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - grub-pc

- name: Grub instalatu EFI
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - grub-efi-amd64-signed
  when: ansible_architecture == 'x86_64'

- name: Chrome Recovery script-a instalatu
  get_url:
    url: https://dl.google.com/dl/edgedl/chromeos/recovery/linux_recovery.sh
    dest: /usr/local/bin/chromebook_recovery
    mode: 0755

