#Gure konfigurazio batzuk
---
- name: Begiratu grub konfigurazioa existitzen den.
  stat:
    path: "/etc/default/grub"
  register: grub

- name: plymouth desaktibatu.
  replace:
    dest: "/etc/default/grub"
    regexp: 'GRUB_CMDLINE_LINUX_DEFAULT="splash quiet"'
    replace: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet"'
  register: grub2
  when: grub.stat.exists == True

- name: grub eguneratu.
  command: /usr/sbin/update-grub
  when: grub2.changed == True

- name: networking.service eta ifup@.service karpetak sortu.
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/etc/systemd/system/ifup@.service.d/"
    - "/etc/systemd/system/networking.service.d/"
  when: ansible_distribution == 'Debian'

- name: Itzali aurretik sarea ez kendu.
  copy:
    src: "{{ role_path }}/files/etc/systemd/system/networking.service.d/override.conf"
    dest: "{{ item }}"
    mode: 0644
  with_items:
    - "/etc/systemd/system/networking.service.d/override.conf"
    - "/etc/systemd/system/ifup@.service.d/override.conf"
  when: ansible_distribution == 'Debian'

- name: Gure zerbitzuak kopiatu.
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/{{ item }}"
    mode: 0644
  with_items:
    - "etc/systemd/system/dhclient.service"
    - "etc/systemd/system/getnamebymac.service"
    - "etc/systemd/system/swapiness.service"
    - "etc/systemd/system/ocsclient.service"

- name: Gure zerbitzuak aktibatu.
  file:
    src: /etc/systemd/system/{{ item }}
    dest: /etc/systemd/system/multi-user.target.wants/{{ item }}
    state: link
  with_items:
    - "dhclient.service"
    - "getnamebymac.service"
    - "swapiness.service"
    - "ocsclient.service"

- name: OCS konfiguratu.
  lineinfile:
    dest: /etc/ocsinventory/ocsinventory-agent.cfg
    regexp: 'local=/var/lib/ocsinventory-agent/reports'
    line: 'server=http://192.168.0.107/ocsinventory'
    backrefs: yes

- name: Botoia sakatzean sistema itzali.
  replace:
    dest: /etc/systemd/logind.conf
    regexp: '#HandlePowerKey=poweroff'
    replace: 'HandlePowerKey=poweroff'

- name: Systemd egunerokoa ez gorde.
  replace:
    dest: /etc/systemd/journald.conf
    regexp: '#Storage=auto'
    replace: 'Storage=volatile'

- name: auto update kendu
  file:
    path: /etc/systemd/system/timers.target.wants/apt-daily.timer
    state: absent

- name: auto upgrade kendu
  file:
    path: /etc/systemd/system/timers.target.wants/apt-daily-upgrade.timer
    state: absent


#ln -s /lib/systemd/system/apt-daily.timer /etc/systemd/system/timers.target.wants/apt-daily.timer
#ln -s /lib/systemd/system/apt-daily-upgrade.timer /etc/systemd/system/timers.target.wants/apt-daily-upgrade.timer
