#Gure konfigurazio batzuk
---
- name: Begiratu grub konfigurazioa existitzen den.
  stat:
    path: "/etc/default/grub"
  register: grub

- name: plymouth desaktibatu.
  replace:
    dest: "/etc/default/grub"
    regexp: 'GRUB_CMDLINE_LINUX_DEFAULT="splash quiet"'
    replace: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet"'
  register: grub2
  when: grub.stat.exists == True

- name: grub eguneratu.
  command: /usr/sbin/update-grub
  when: grub2.changed == True

- name: Botoia sakatzean sistema itzali.
  replace:
    dest: /etc/systemd/logind.conf
    regexp: '#HandlePowerKey=poweroff'
    replace: 'HandlePowerKey=poweroff'

#Defektuz Ubuntun Network-manager-ek wifia baino ez du kudeatzen
- name: Network manager ethernet kudeatzeko erabili.
  file:
    path: /usr/lib/NetworkManager/conf.d/10-globally-managed-devices.conf
    state: absent
  when: ansible_distribution == 'Ubuntu'
