#Gure konfigurazio batzuk
---
- name: networking.service eta ifup@.service karpetak sortu.
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/etc/systemd/system/ifup@.service.d/"
    - "/etc/systemd/system/networking.service.d/"
  when: ansible_distribution == 'Debian'

- name: Itzali aurretik sarea ez kendu.
  copy:
    src: "{{ role_path }}/files/etc/systemd/system/networking.service.d/override.conf"
    dest: "{{ item }}"
    mode: 0644
  with_items:
    - "/etc/systemd/system/networking.service.d/override.conf"
    - "/etc/systemd/system/ifup@.service.d/override.conf"
  when: ansible_distribution == 'Debian'

#- name: OpenNIC dns-ak erabili. Ubuntu. 
#  template:
#    src: "{{ role_path }}/templates/etc/systemd/resolved.j2"
#    dest: "/etc/systemd/resolved.conf"
#  when: ansible_distribution == 'Ubuntu'

- name: DHCP lortzeko zerbitzua kopiatu.
  copy:
    src: "{{ role_path }}/files/etc/systemd/system/dhclient.service"
    dest: "/etc/systemd/system/dhclient.service"
    mode: 0644

- name: DHCP lortzeko zerbitzua aktibatu.
  file:
    src: /etc/systemd/system/dhclient.service
    dest: /etc/systemd/system/multi-user.target.wants/dhclient.service
    state: link

- name: Botoia sakatzean sistema itzali.
  replace:
    dest: /etc/systemd/logind.conf
    regexp: '#HandlePowerKey=poweroff'
    replace: 'HandlePowerKey=poweroff'

- name: Systemd egunerokoa ez gorde.
  replace:
    dest: /etc/systemd/journald.conf
    regexp: '#Storage=auto'
    replace: 'Storage=volatile'

- name: Izena lortzeko zerbitzua kopiatu.
  copy:
    src: "{{ role_path }}/files/etc/systemd/system/getnamebymac.service"
    dest: "/etc/systemd/system/getnamebymac.service"
    mode: 0644

- name: Izena lortzeko zerbitzua aktibatu.
  file:
    src: /etc/systemd/system/getnamebymac.service
    dest: /etc/systemd/system/multi-user.target.wants/getnamebymac.service
    state: link

- name: auto update kendu
  file:
    path: /etc/systemd/system/timers.target.wants/apt-daily.timer
    state: absent

- name: auto upgrade kendu
  file:
    path: /etc/systemd/system/timers.target.wants/apt-daily-upgrade.timer
    state: absent


#ln -s /lib/systemd/system/apt-daily.timer /etc/systemd/system/timers.target.wants/apt-daily.timer
#ln -s /lib/systemd/system/apt-daily-upgrade.timer /etc/systemd/system/timers.target.wants/apt-daily-upgrade.timer



