#gure script batzuk
---
- name: Instalatzaileak kopiatu
  copy:
    src: "{{ role_path }}/files/root/{{ item }}"
    dest: "/root/{{ item }}"
    mode: 0755
  with_items:
     - formatallbios
     - formatalluefi
     - formatalllive
     - eguneratuefi
     - eguneratubios

- name: Gure scriptak kopiatu
  copy:
    src: "{{ role_path }}/files/usr/local/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
  with_items:
     - gethardinfo
     - getnamebymac
     - mute
     - unmute
     - wifion
     - kendui386
     - update_hosts
     - disableswap

- name: Copy basic syslinux_local.cfg
  copy:
    src: "{{ role_path }}/files/root/{{ item }}"
    dest: "/root/{{ item }}"
    mode: 0644
  with_items:
     - syslinux_local.cfg
     - syslinux_live.cfg
