#gure script batzuk
---
- name: Instalatzaileak kopiatu
  copy:
    src: "{{ role_path }}/files/root/{{ item }}"
    dest: "/root/{{ item }}"
    mode: 0755
  with_items:
     - formatallbios
     - formatallbios1
     - formatallbios2
     - formatallbios3
     - formatalluefi
     - formatalluefi1
     - formatalluefi2
     - formatalluefi3

- name: Gure scriptak kopiatu
  copy:
    src: "{{ role_path }}/files/usr/local/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
  with_items:
     - gethardinfo
     - getnamebymac
     - mute
     - unmute
     - wifion
     - kendui386
     - update_hosts

- name: Copy basic syslinux_local.cfg
  copy:
    src: "{{ role_path }}/files/root/syslinux_local.cfg"
    dest: "/root/syslinux_local.cfg"
    mode: 0644
