#erabiltzaile bat sortzen du. izena "usuario" eta pasahitza "usuario"
#pasahitzak sortzeko 'mkpasswd --method=sha-512' (whois programa instalatu behar da).
---
  - name: root erabiltzailearen pasahitza jarri.
    user:
       name: root
       password: $6$fih0C7ah.ro$zZM9yfBEDSfgvknXo5HU0cXZZ1WBvpZiC/dOOKnJHxAqLCw1nOGoFfabyBx/KsgrCsR6wJEqcCmzCglpBBhXM.

  - name: Erabiltzailea sortu. Debian.
    user:
       name: usuario
       password: $6$HLUn1tmi0$vwX4J58XjnZMDTcXVEK1ARpwKo2bkehuyz00ozx.phKrrzgsGAABoD94gaFCSPKvk/EkWM9wrB03Lp8TZKd9x1
       shell: /bin/bash
       createhome: no
       groups: cdrom,floppy,audio,dip,video,plugdev,netdev
    when: ansible_distribution == 'Debian'

  - name: Erabiltzailea sortu. Ubuntu.
    user:
       name: usuario
       password: $6$HLUn1tmi0$vwX4J58XjnZMDTcXVEK1ARpwKo2bkehuyz00ozx.phKrrzgsGAABoD94gaFCSPKvk/EkWM9wrB03Lp8TZKd9x1
       shell: /bin/bash
       createhome: no
       groups: adm,cdrom,dip,plugdev
    when: ansible_distribution == 'Ubuntu'

  - name: Etxeko karpeta lehen aldiz sartzerakoan sortu.
    replace:
      dest: /usr/share/pam-configs/mkhomedir
      regexp: 'Default: no'
      replace: 'Default: yes'

  - name: pam-auth-update
    command: pam-auth-update --package --enable mkhomedir
    args:
      warn: no
