#erabiltzaile bat sortzen du. izena "usuario" eta pasahitza "usuario"
#pasahitzak sortzeko 'mkpasswd --method=sha-512' (whois programa instalatu behar da).
---
  - name: root erabiltzailearen pasahitza jarri.
    user:
       name: root
       password: $6$eSQfQkmP8HL7/$GvI8IufQjSBxP5QJMLve7zpYzs87N23Lk7Zg9EzAW23Pj4OsP/nmBnSmLnnduameDderQb9oGvYMyXjCTEzq4/
    register: root

  - name: Erabiltzailea sortu. Debian.
    user:
       name: usuario
       password: $6$HLUn1tmi0$vwX4J58XjnZMDTcXVEK1ARpwKo2bkehuyz00ozx.phKrrzgsGAABoD94gaFCSPKvk/EkWM9wrB03Lp8TZKd9x1
       shell: /bin/bash
       createhome: no
       groups: cdrom,floppy,audio,dip,video,plugdev,netdev
    register: usuario
    when: ansible_distribution == 'Debian'

  - name: Erabiltzailea sortu. Ubuntu.
    user:
       name: usuario
       password: $6$HLUn1tmi0$vwX4J58XjnZMDTcXVEK1ARpwKo2bkehuyz00ozx.phKrrzgsGAABoD94gaFCSPKvk/EkWM9wrB03Lp8TZKd9x1
       shell: /bin/bash
       createhome: no
       groups: adm,cdrom,dip,plugdev
    register: usuario
    when: ansible_distribution == 'Ubuntu'

  - name: Etxeko karpeta lehen aldiz sartzerakoan sortu.
    replace:
      dest: /usr/share/pam-configs/mkhomedir
      regexp: 'Default: no'
      replace: 'Default: yes'
    register: pam

  - name: pam-auth-update
    command: pam-auth-update --package --enable mkhomedir
    when: (root.changed  == true) or (usuario.changed  == true) or (pam.changed  == true)
