#!/bin/sh
diska=`lsblk | grep disk | awk 'FNR == 1 {print $1}'`
for n in /dev/$diska* ; do umount $n ; done
swapoff --all
dd if=/dev/zero of=/dev/$diska bs=1024 count=1
parted -s /dev/$diska mklabel msdos
parted -s /dev/$diska mkpart primary ext4 1 200
parted -s /dev/$diska mkpart extended 200 100%
parted -s /dev/$diska mkpart logical ext4 201 20200 
parted -s /dev/$diska mkpart logical ext4 20201 40200
parted -s /dev/$diska mkpart logical ext4 40201 60200
parted -s /dev/$diska mkpart logical linux-swap 60201 64200
parted -s /dev/$diska mkpart logical ext4 64201 100%
parted -s /dev/$diska set 1 boot on
