#!/bin/sh
#dependentziak
apt-get purge libnspr4:i386 libudev1:i386 libcurl4:i386 libfontconfig1:i386 libfreetype6:i386 libgl1-mesa-glx:i386 libglib2.0-0:i386 libice6:i386 libsm6:i386 libstdc++6:i386 libx11-6:i386 libxext6:i386 libxml2:i386 libxrender1:i386 libasound2:i386 libgtk2.0-0:i386 libxinerama1:i386 libxkbfile1:i386 libxtst6:i386 libxslt1.1:i386 libltdl7:i386 libffi6:i386 libusb-1.0-0:i386 libbluetooth3:i386
apt-get purge smart-activation:i386 smart-common:i386 smart-gallerysetup:i386 smart-hwr:i386 smart-languagesetup:i386 smart-notebook:i386 smart-product-drivers:i386
rm /lib/i386-linux-gnu/libudev.so.0
rm -R /opt/SMART\ Technologies/
