#!/bin/sh
#instalatzaileak jaitsi
wget http://downloads.smarttech.com/software/nb/11linux/11sp2/smart_software_deb_files.tar.gz
#erauzi
tar -xvzf smart_software_deb_files.tar.gz 
#instalatzaileak konpondu
dpkg-deb -R ./smart-common_10.3.2171.1-1_i386.deb ./common
sed -i -e 's/libnspr4-0d/libnspr4/g' ./common/DEBIAN/control
sed -i -e 's/libcurl3/libcurl4/g' ./common/DEBIAN/control
dpkg-deb -b ./common ./smart-common.deb
dpkg-deb -R ./smart-languagesetup_2.2.2060.4-1_i386.deb ./language
sed -i -e 's/libnspr4-0d/libnspr4/g' ./language/DEBIAN/control
sed -i -e 's/libcurl3/libcurl4/g' ./language/DEBIAN/control
dpkg-deb -b ./common ./smart-language.deb
dpkg-deb -R ./smart-product-drivers_11.3.2121.1-1_i386.deb ./drivers
sed -i -e 's/libnspr4-0d/libnspr4/g' ./drivers/DEBIAN/control
sed -i -e 's/libcurl3/libcurl4/g' ./drivers/DEBIAN/control
dpkg-deb -b ./common ./smart-drivers.deb
dpkg-deb -R ./smart-activation_1.1.2066.1-1_i386.deb ./activation
sed -i -e 's/libnspr4-0d/libnspr4/g' ./activation/DEBIAN/control
sed -i -e 's/libcurl3/libcurl4/g' ./activation/DEBIAN/control
dpkg-deb -b ./common ./smart-activation.deb
dpkg-deb -R ./smart-gallerysetup_1.3.6235.1-1_i386.deb ./gallery
sed -i -e 's/libnspr4-0d/libnspr4/g' ./gallery/DEBIAN/control
sed -i -e 's/libcurl3/libcurl4/g' ./gallery/DEBIAN/control
dpkg-deb -b ./common ./smart-gallery.deb
dpkg-deb -R ./smart-notebook_11.0.7511.0-1_i386.deb ./notebook
sed -i -e 's/libnspr4-0d/libnspr4/g' ./notebook/DEBIAN/control
sed -i -e 's/libcurl3/libcurl4/g' ./notebook/DEBIAN/control
dpkg-deb -b ./common ./smart-notebook.deb
#dependentziak
apt-get update
apt-get install libgl1-mesa-glx libcurl4 libnspr4 libudev1
ln -s /lib/i386-linux-gnu/libudev.so.1 /lib/i386-linux-gnu/libudev.so.0
#instalatu
dpkg -i smart-common.deb
dpkg -i smart-hwr_11.3.2121.1-1_i386.deb
dpkg -i smart-language.deb
dpkg -i smart-drivers.deb
dpkg -i smart-activation.deb
dpkg -i smart-gallery.deb
dpkg -i smart-notebook.deb
