#kodi konfiguratzeko
---
  - name: programak
    apt:
      name: "{{ packages }}"
    vars:
      packages:
       - sddm
       - kodi

  - name: Autologin.
    blockinfile:
      dest: "/etc/sddm.conf.d/autologin.conf"
      create: yes
      block: |
        [Autologin]
        User=usuario
        Session=kodi.desktop

  - name: fitxategientzako karpetak sortu
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - "/etc/skel/.kodi/userdata/keymaps"
      - "/etc/udev/hwdb.d"

  - name: OSMC mandoa konfiguratu
    copy:
      src: "{{ role_path }}/files/{{ item }}"
      dest: "/{{ item }}"
      mode: 0644
    with_items:
      - "etc/skel/.kodi/userdata/keymaps/keyboard.xml"
      - "etc/skel/.kodi/userdata/keymaps/guisettings.xml"
      - "etc/udev/hwdb.d/osmcrf.hwdb"
      - "etc/udev/hwdb.d/mele_F10.hwdb"

