#gutxieneko zerbitzari grafikoa instalatzen du honek
---
- name: Xorg paketeak debian.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - xorg
    - mesa-utils
  when: ansible_distribution == 'Debian'

- name: Xorg paketeak ubuntu.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - xorg
    - mesa-utils
    - xserver-xorg-video-all
    - xserver-xorg-video-amdgpu
    - xserver-xorg-video-ati
    - xserver-xorg-video-radeon
    - xserver-xorg-video-dummy
    - xserver-xorg-video-fbdev
    - xserver-xorg-video-intel
    - xserver-xorg-video-nouveau
    - xserver-xorg-video-qxl
    - xserver-xorg-video-vesa
    - xserver-xorg-video-vmware
    - xserver-xorg-video-mga
    - xserver-xorg-video-openchrome
  when: ansible_distribution == 'Ubuntu'
