#erabiltzaile bat sortzen du. izena "auto" eta pasahitza "auto"
#pasahitzak sortzeko 'mkpasswd --method=sha-512' (whois programa instalatu behar da).
---
  - name: Erabiltzailea sortu. Debian.
    user:
       name: auto
       password: $6$52zCOlRKyeLw1OKS$fvK7Bp4vvlH0EXEY3lSWF2xc4SFnyBgbL6Q0Y2iSN2JcHRD6CfMkzRn8DYfLeOfM2X.gNVGac5EDfmHW11ZaN0
       shell: /bin/bash
       groups: cdrom,floppy,audio,dip,video,plugdev,netdev
    register: auto
    when: ansible_distribution == 'Debian'

  - name: Erabiltzailea sortu. Ubuntu.
    user:
       name: auto
       password: $6$52zCOlRKyeLw1OKS$fvK7Bp4vvlH0EXEY3lSWF2xc4SFnyBgbL6Q0Y2iSN2JcHRD6CfMkzRn8DYfLeOfM2X.gNVGac5EDfmHW11ZaN0
       shell: /bin/bash
       groups: adm,cdrom,dip,plugdev
    register: auto
    when: ansible_distribution == 'Ubuntu'
