#Idazmahai minimo bat instalatu eta euskeraz konfiguratu. Debian eta Ubbuntu.
---

  - include: 00-minimal.yml

  - include: 01-locales.yml

  - include: 02-openbox.yml

  - include: 03-autologin.yml

  - include: 04-users.yml

  - include: 05-firefox.yml

  - include: 06-wifia.yml
