---
- name: Ziurtatu policies karpeta existitzen dela
  file:
    path: "{{ bi }}/etc/chromium-browser/policies/managed/"
    state: directory

- name: Chromeren politikak kopiatzen
  copy:
    src: "{{ bat }}/etc/chromium-browser/policies/managed/test_policy.json"
    dest: "{{ bi }}/etc/chromium-browser/policies/managed/test_policy.json"
    mode: 0644
