---
- name: LDAP konexiorako paketeak
  apt:
    name: "{{ packages }}"
  vars:
    packages:
     - libnss-ldapd 
     - libpam-ldapd 
     - libpam-mount 
     - cifs-utils
- name: LDAP offline konexiorako paketeak
  apt:
    name: "{{ packages }}"
  vars:
    packages:
     - nss-updatedb 
     - libnss-db 
     - libpam-ccreds
