---
- name: Eguneratu paketeak azken bertsiora
  apt:
    upgrade: dist

- name: Tasksel oinarrizko paketeak
  command: /usr/bin/tasksel --new-install install standard

- name: Beste paketeak instalatu
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - live-boot
    - screen
    - firmware-linux-nonfree
    - nfs-common
    - watchdog
    - syslinux
    - syslinux-efi
    - extlinux
    - pv
    - wget
    - squashfs-tools
    - parted
