---
- name: Eguneratu paketeak azken bertsiora
  apt:
    upgrade: dist

- name: Beste paketeak instalatu
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - linux-image-amd64
    - live-boot
    - screen
    - firmware-linux-nonfree
    - xorg
    - openbox
    - lightdm
    - retroarch
    - tint2
    - pulseaudio

- name: openbox autostart
  blockinfile:
    dest: "/etc/xdg/openbox/autostart"
    block: |
      retroarch &

- name: retroarch.cfg
  blockinfile:
    create: yes
    dest: "/etc/retroarch.cfg"
    block: |
      video_fullscreen = "true"
      video_windowed_fullscreen = "true"
      video_smooth = "false"
      menu_show_core_updater = "true"

- name: Sortu euskerako lokala
  lineinfile:
    dest: /etc/lightdm/lightdm.conf
    regexp: '#autologin-user='
    line: 'autologin-user=arcade'
    backrefs: yes
