---
- name: Network manager instalatu
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - network-manager

- name: network-manager zerbitzua kendu
  service:
    name: network-manager
    enabled: no

- name: NetworkManager zerbitzua kendu
  service:
    name: NetworkManager
    enabled: no

- name: NetworkManager-wait-online.service zerbitzua kendu
  service:
    name: NetworkManager-wait-online.service
    enabled: no

