---
- name: ziurtatu smart karpeta existitzen dela
  file:
    path: /root/smart
    state: directory

- name: Deskargatu eta erauzi guresmart
  unarchive:
    src: https://drive.google.com/uc?export=download&id=1FguJAnLWh5usYb_uqMRelKc0_EibgdMr
    dest: /root/smart
    remote_src: yes

- name: Deskargatu eta erauzi smart
  unarchive:
    src: http://downloads.smarttech.com/software/nb/11linux/11sp2/smart_software_deb_files.tar.gz
    dest: /root/smart
    remote_src: yes

- name: Dependentzik instalatu
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - libcurl3
    - libnspr4 
    - libudev1

- name: libudev0 instalatu
  apt:
    deb: /root/smart/libudev0.deb

- name: libudev1 eta libudev0 lotu
  file:
    src: /lib/i386-linux-gnu/libudev.so.1
    dest: /lib/i386-linux-gnu/libudev.so.0
    state: link

- name: libnspr4-0d instalatu
  apt:
    deb: /root/smart/libnspr4-0d.deb

- name: smart-common instalatu
  apt:
    deb: /root/smart/smart-common_10.3.2171.1-1_i386.deb

- name: smart-hwr instalatu
  apt:
    deb: /root/smart/smart-hwr_11.3.2121.1-1_i386.deb

- name: smart-languagesetup instalatu
  apt:
    deb: /root/smart/smart-languagesetup_2.2.2060.4-1_i386.deb

- name: smart-product-drivers instalatu
  apt:
    deb: /root/smart/smart-product-drivers_11.3.2121.1-1_i386.deb

- name: smart-activation instalatu
  apt:
    deb: /root/smart/smart-activation_1.1.2066.1-1_i386.deb

- name: smart-gallerysetup instalatu
  apt:
    deb: /root/smart/smart-gallerysetup_1.3.6235.1-1_i386.deb

- name: smart-notebook instalatu
  apt:
    deb: /root/smart/smart-notebook_11.0.7511.0-1_i386.deb

- name: kendu instalatzaileak
  file:
    path: "/root/smart"
    state: absent

