---
- name: Ziurtatu karpeta existitzen dela
  file:
    path: "{{ bi }}/etc/skel/.config/smplayer"
    state: directory

- name: smplayer konfigurazioa ezartzen
  copy:
    src: "{{ bat }}/etc/skel/.config/smplayer/smplayer.ini"
    dest: "{{ bi }}/etc/skel/.config/smplayer/smplayer.ini"
    mode: 0644
