---
- name: Mahaigaineko irudia kopiatzen
  copy:
    src: "{{ bat }}/usr/share/backgrounds/xfce/ikastola.jpg"
    dest: "{{ bi }}/usr/share/backgrounds/xfce/ikastola.jpg"
    mode: 0644

- name: xfwm lehio kudeatzailea konfiguratzen
  copy:
    src: "{{ bat }}/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml"
    dest: "{{ bi }}/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml"
    mode: 0644

- name: energia kudeatzailea konfiguratzen
  copy:
    src: "{{ bat }}/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml"
    dest: "{{ bi }}/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml"
    mode: 0644

- name: ikonoak eta gaia konfiguratzen
  copy:
    src: "{{ bat }}/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml"
    dest: "{{ bi }}/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml"
    mode: 0644

- name: panela konfiguratzen
  copy:
    src: "{{ bat }}/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml"
    dest: "{{ bi }}/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml"
    mode: 0644

- name: panela konfiguratzen2
  copy:
    src: "{{ bat }}/etc/xdg/xfce4/panel/default.xml"
    dest: "{{ bi }}/etc/xdg/xfce4/panel/default.xml"
    mode: 0644

- name: teklatu lasterbideak konfiguratzen
  copy:
    src: "{{ bat }}/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml"
    dest: "{{ bi }}/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml"
    mode: 0644

- name: mahaigaina konfiguratzen
  copy:
    src: "{{ bat }}/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml"
    dest: "{{ bi }}/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml"
    mode: 0644

- name: teklatuan blocknum jartzen
  copy:
    src: "{{ bat }}/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/keyboards.xml"
    dest: "{{ bi }}/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/keyboards.xml"
    mode: 0644

- name: whisker menua konfiguratzen
  copy:
    src: "{{ bat }}/etc/xdg/xfce4/panel/whiskermenu-1.rc"
    dest: "{{ bi }}/etc/xdg/xfce4/panel/whiskermenu-1.rc"
    mode: 0644

- name: ziurtatu kiosk karpeta existitzen dela
  file:
    path: "{{ bi }}/etc/xdg/xfce4/kiosk"
    state: directory

- name: kiosk ezarpenak jartzen
  copy:
    src: "{{ bat }}/etc/xdg/xfce4/kiosk/kioskrc"
    dest: "{{ bi }}/etc/xdg/xfce4/kiosk/kioskrc"
    mode: 0644

- name: erabiltzaile karpetak ezartzen
  copy:
    src: "{{ bat }}/etc/xdg/user-dirs.defaults"
    dest: "{{ bi }}/etc/xdg/user-dirs.defaults"
    mode: 0644

- name: fitxategi motak programekin lotzen
  copy:
    src: "{{ bat }}/etc/xdg/mimeapps.list"
    dest: "{{ bi }}/etc/xdg/mimeapps.list"
    mode: 0644

- name: QT aplikazioak konfiguratzen
  copy:
    src: "{{ bat }}/etc/xdg/Trolltech.conf"
    dest: "{{ bi }}/etc/xdg/Trolltech.conf"
    mode: 0644

- name: eseki politika jartzen
  copy:
    src: "{{ bat }}/etc/polkit-1/localauthority/50-local.d/eseki.pkla"
    dest: "{{ bi }}/etc/polkit-1/localauthority/50-local.d/eseki.pkla"
    mode: 0644

- name: lightdm erabiltzaileak eskuz sartzeko prestatu
  blockinfile:
    create: yes
    dest: "{{ bi }}/etc/lightdm/lightdm.conf"
    block: |
      [SeatDefaults]
      greeter-hide-users=true
      greeter-show-manual-login=true 

- name: lightdm itxura aldatu
  blockinfile:
    dest: "{{ bi }}/etc/lightdm/lightdm-gtk-greeter.conf"
    block: |
      background=/usr/share/backgrounds/xfce/ikastola.jpg
      indicators=~host;~spacer;~session;~clock;~power;
