---
- name: Mahaigaineko irudia kopiatzen
  copy:
    src: "{{ bat }}/usr/share/backgrounds/xfce/ikastola.jpg"
    dest: "{{ bi }}/usr/share/backgrounds/xfce/ikastola.jpg"
    mode: 0644

- name: xfwm lehio kudeatzailea konfiguratzen
  copy:
    src: "{{ bat }}/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml"
    dest: "{{ bi }}/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml"
    mode: 0644

- name: energia kudeatzailea konfiguratzen
  copy:
    src: "{{ bat }}/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml"
    dest: "{{ bi }}/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml"
    mode: 0644

- name: ikonoak eta gaia konfiguratzen
  copy:
    src: "{{ bat }}/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml"
    dest: "{{ bi }}/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml"
    mode: 0644

- name: panela konfiguratzen
  copy:
    src: "{{ bat }}/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml"
    dest: "{{ bi }}/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml"
    mode: 0644

- name: panela konfiguratzen2
  copy:
    src: "{{ bat }}/etc/xdg/xfce4/panel/default.xml"
    dest: "{{ bi }}/etc/xdg/xfce4/panel/default.xml"
    mode: 0644

- name: whisker panela konfiguratzen
  copy:
    src: "{{ bat }}/etc/xdg/xfce4/panel/whiskermenu-1.rc"
    dest: "{{ bi }}/etc/xdg/xfce4/panel/whiskermenu-1.rc"
    mode: 0644

- name: teklatu lasterbideak konfiguratzen
  copy:
    src: "{{ bat }}/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml"
    dest: "{{ bi }}/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml"
    mode: 0644

- name: mahaigaina konfiguratzen
  copy:
    src: "{{ bat }}/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml"
    dest: "{{ bi }}/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml"
    mode: 0644

- name: teklatuan blocknum jartzen
  copy:
    src: "{{ bat }}/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/keyboards.xml"
    dest: "{{ bi }}/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/keyboards.xml"
    mode: 0644

- name: whisker menua konfiguratzen
  copy:
    src: "{{ bat }}/etc/xdg/xfce4/panel/whiskermenu-1.rc"
    dest: "{{ bi }}/etc/xdg/xfce4/panel/whiskermenu-1.rc"
    mode: 0644

- name: ziurtatu terminal karpeta existitzen dela
  file:
    path: "{{ bi }}/etc/xdg/xfce4/terminal"
    state: directory

- name: xfce terminala konfiguratzen
  copy:
    src: "{{ bat }}/etc/xdg/xfce4/terminal/terminalrc"
    dest: "{{ bi }}/etc/xdg/xfce4/terminal/terminalrc"
    mode: 0644

- name: ziurtatu kiosk karpeta existitzen dela
  file:
    path: "{{ bi }}/etc/xdg/xfce4/kiosk"
    state: directory

- name: kiosk ezarpenak jartzen
  copy:
    src: "{{ bat }}/etc/xdg/xfce4/kiosk/kioskrc"
    dest: "{{ bi }}/etc/xdg/xfce4/kiosk/kioskrc"
    mode: 0644

- name: erabiltzaile karpetak ezartzen
  copy:
    src: "{{ bat }}/etc/xdg/user-dirs.defaults"
    dest: "{{ bi }}/etc/xdg/user-dirs.defaults"
    mode: 0644

- name: fitxategi motak programekin lotzen
  copy:
    src: "{{ bat }}/etc/xdg/mimeapps.list"
    dest: "{{ bi }}/etc/xdg/mimeapps.list"
    mode: 0644

- name: QT aplikazioak konfiguratzen
  copy:
    src: "{{ bat }}/etc/xdg/Trolltech.conf"
    dest: "{{ bi }}/etc/xdg/Trolltech.conf"
    mode: 0644

- name: eseki politika jartzen
  copy:
    src: "{{ bat }}/etc/polkit-1/localauthority/50-local.d/eseki.pkla"
    dest: "{{ bi }}/etc/polkit-1/localauthority/50-local.d/eseki.pkla"
    mode: 0644

- name: lightdm erabiltzaileak eskuz sartzeko prestatu
  blockinfile:
    create: yes
    dest: "{{ bi }}/etc/lightdm/lightdm.conf"
    block: |
      [SeatDefaults]
      greeter-hide-users=true
      greeter-show-manual-login=true 

- name: lightdm itxura aldatu
  blockinfile:
    dest: "{{ bi }}/etc/lightdm/lightdm-gtk-greeter.conf"
    block: |
      background=/usr/share/backgrounds/xfce/ikastola.jpg
      indicators=~host;~spacer;~session;~clock;~power;

- name: Ziurtatu firefoxen policies karpeta existitzen dela
  file:
    path: "{{ bi }}/usr/share/firefox-esr/distribution"
    state: directory

- name: firefox politikak ezarri
  copy:
    src: "{{ bat }}/usr/share/firefox-esr/distribution/policies.json"
    dest: "{{ bi }}/usr/share/firefox-esr/distribution/policies.json"
    mode: 0644

- name: libreofficen fitxateki blokeoa kentzen
  copy:
    src: "{{ bat }}/usr/lib/libreoffice/share/registry/disable-file-locking.xcd"
    dest: "{{ bi }}/usr/lib/libreoffice/share/registry/disable-file-locking.xcd"
    mode: 0644

- name: Ziurtatu .config/smplayer karpeta existitzen dela
  file:
    path: "{{ bi }}/etc/skel/.config/smplayer"
    state: directory

- name: smplayer konfigurazioa ezartzen
  copy:
    src: "{{ bat }}/etc/skel/.config/smplayer/smplayer.ini"
    dest: "{{ bi }}/etc/skel/.config/smplayer/smplayer.ini"
    mode: 0644

- name: proiektorearen kudeatzailea instalatzen
  copy:
    src: "{{ bat }}/usr/local/bin/proiektorea"
    dest: "{{ bi }}/usr/local/bin/proiektorea"
    mode: 0755

- name: proiektorearen kudeatzailea instalatzen
  copy:
    src: "{{ bat }}/etc/xdg/autostart/proiektorea.desktop"
    dest: "{{ bi }}/etc/xdg/autostart/proiektorea.desktop"
    mode: 0644

- name: hosts eguneratzailea instalatzen
  copy:
    src: "{{ bat }}/usr/local/bin/update_hosts"
    dest: "{{ bi }}/usr/local/bin/update_hosts"
    mode: 0755

- name: Kendu screen-saver
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ bi }}/etc/xdg/autostart/xscreensaver.desktop"

- name: proiektorearen kudeatzailea instalatzen
  copy:
    src: "{{ bat }}/../scriptak/smart32kendu"
    dest: "{{ bi }}/root/smart32kendu"
    mode: 0644

- name: proiektorearen kudeatzailea instalatzen
  copy:
    src: "{{ bat }}/../scriptak/smart32"
    dest: "{{ bi }}/root/smart"
    mode: 0644

- name: proiektorearen kudeatzailea instalatzen
  copy:
    src: "{{ bat }}/../scriptak/smart64kendu"
    dest: "{{ bi }}/root/smart64kendu"
    mode: 0644

- name: proiektorearen kudeatzailea instalatzen
  copy:
    src: "{{ bat }}/../scriptak/smart64"
    dest: "{{ bi }}/root/smart64"
    mode: 0644
