#bezeroa windows domeinuan sartzeko konfiguratu sssd eta ldap erabiliz
---
  - name: LDAP dependentziak instalatu.
    apt:
      name: "{{ packages }}"
    vars:
      packages:
       - realmd
       - libpam-mount
       - cifs-utils
       - sssd-tools
       - sssd
       - libnss-sss
       - libpam-sss
       - adcli
       - packagekit
       - nss-updatedb

#sss_obfuscate -d <domain_name>
  - name: sssd konfiguratu.
    template:
      src: "{{ role_path }}/templates/etc/sssd/sssd.j2"
      dest: "/etc/sssd/sssd.conf"
      mode: 0600
    register: sssd

#  - name: sssd aldatu. Debian.
#    replace:
#      dest: "/etc/sssd/sssd.conf"
#      regexp: '#services = nss, pam'
#      replace: 'services = nss, pam'
#    when: ansible_distribution == 'Debian'

  - name: pam_mount konfiguratu
    lineinfile:
      path: /etc/security/pam_mount.conf.xml
      insertafter: '<!-- Volume definitions -->'
      line: '{{ item }}'
    with_items:
      - '<volume user="ordezkoa" server="fitxategiak" path="Multimedia" mountpoint="/media/%(USER)/multimedia" fstype="cifs" options="domain=lizarraikastola,vers=3.0" />'
      - '<volume sgrp="Lizarra Ikastola" server="fitxategiak" path="Multimedia" mountpoint="/media/%(USER)/multimedia" fstype="cifs" options="domain=lizarraikastola,vers=3.0" />'
      - '<volume sgrp="Lizarra Ikastola" server="fitxategiak" path="Eskanerra" mountpoint="/media/%(USER)/eskanerra" fstype="cifs" options="domain=lizarraikastola,vers=3.0" />'
      - '<volume sgrp="Orientazioa" server="fitxategiak" path="Orientazioa" mountpoint="/media/%(USER)/orientazioa" fstype="cifs" options="domain=lizarraikastola,vers=3.0" />'
      - '<volume sgrp="Orientazioa" server="fitxategiak" path="EFQM" mountpoint="/media/%(USER)/EFQM" fstype="cifs" options="domain=lizarraikastola,vers=3.0" />'
      - '<volume sgrp="Administrazioa" server="fitxategiak" path="EFQM" mountpoint="/media/%(USER)/EFQM" fstype="cifs" options="domain=lizarraikastola,vers=3.0" />'
      - '<volume sgrp="Administrazioa" server="fitxategiak" path="Administrazioa" mountpoint="/media/%(USER)/Administrazioa" fstype="cifs" options="domain=lizarraikastola,vers=3.0" />'
      - '<volume sgrp="Irakasleak" server="fitxategiak" path="EFQM" mountpoint="/media/%(USER)/EFQM" fstype="cifs" options="domain=lizarraikastola,vers=3.0" />'
      - '<!--   EFQM   -->'
      - '<volume sgrp="Irakasleak" server="fitxategiak" path="Irakasleak/%(USER)" mountpoint="/media/%(USER)/ira/%(USER)" fstype="cifs" options="domain=lizarraikastola,vers=3.0" />'
      - '<volume sgrp="Orientazioa" server="fitxategiak" path="Orientazioa/%(USER)" mountpoint="/media/%(USER)/ori/%(USER)" fstype="cifs" options="domain=lizarraikastola,vers=3.0" />'
      - '<volume sgrp="Administrazioa" server="fitxategiak" path="Administrazioa/%(USER)" mountpoint="/media/%(USER)/adm/%(USER)" fstype="cifs" options="domain=lizarraikastola,vers=3.0" />'
      - '<!--   Karpeta pertsonalak   -->'

#  - name: Lehen aldiz sartzean karpeta sortu.
#    replace:
#      dest: /usr/share/pam-configs/mkhomedir
#      regexp: 'Default: no'
#      replace: 'Default: yes'
#    register: mkhomedir

  - name: Lehen aldiz sartzean karpeta sortu eta pam_mount baino lehentasun handiagoarekin.
    replace:
      dest: /usr/share/pam-configs/mkhomedir
      regexp: "{{ item.bat }}"
      replace: "{{ item.bi }}"
    with_items:
       - { bat: 'Default: no', bi: 'Default: yes' }
       - { bat: 'Priority: 0', bi: 'Priority: 130' }
    register: mkhomedir

  - name: Update pam configuration.
    command: pam-auth-update --package --enable mkhomedir
    args:
    when: (sssd.changed  == true) or (mkhomedir.changed == true)
