#bezeroa windows domeinuan sartzeko konfiguratu sssd eta ldap erabiliz
---
  - name: LDAP dependentziak instalatu.
    apt:
      name: "{{ packages }}"
    vars:
      packages:
       - realmd
       - libpam-mount 
       - cifs-utils
       - sssd-tools
       - sssd
       - libnss-sss
       - libpam-sss
       - adcli
       - packagekit

  - name: dnsmasq konfiguratu.
    template:
      src: "{{ role_path }}/templates/sssd.j2"
      dest: "/etc/sssd/sssd.conf"
      mode: 0600

#  - name: pam_mount konfiguratu.
#    copy:
#      src: "{{ role_path }}/files/etc/security/pam_mount.conf.xml"
#      dest: "/etc/security/pam_mount.conf.xml"
#      mode: 0644

  - name: pam_mount konfiguratu
    lineinfile:
      path: /etc/security/pam_mount.conf.xml
      insertafter: '<!-- Volume definitions -->'
      line: '<volume sgrp="Orientazioa" server="fitxategiak" path="EFQM" mountpoint="/media/%(USER)/EFQM" fstype="cifs" options="vers=3.0" />'

  - name: Domeinuko erabiltzaileak sudoers fitxategian gehitu.
    blockinfile:
      create: yes
      dest: "/etc/sudoers"
      marker: "#Domeinuko erabiltzaileak"
      block: |
        {{ domeinua }} ALL=(ALL) ALL

#  - name: Lehen aldiz sartzean karpeta sortu.
#    replace:
#      dest: /usr/share/pam-configs/mkhomedir
#      regexp: 'Default: no'
#      replace: 'Default: yes'

  - name: Update pam configuration.
    command: pam-auth-update --package --enable mkhomedir
    args:
      warn: no

  - name: Gure DNS-ak jarri.
    replace:
      dest: /etc/systemd/resolved.conf
      regexp: '#DNS='
      replace: 'DNS={{ gure_dns }}'
    when: ansible_distribution == 'Ubuntu'

  - name: Gure domeinua gehitu.
    replace:
      dest: /etc/systemd/resolved.conf
      regexp: '#Domains='
      replace: 'Domains={{ domain_name }}'
    when: ansible_distribution == 'Ubuntu'
