---
- name: Sortu gaztelerako lokala
  locale_gen:
    name: es_ES.UTF-8
    state: present

- name: Sortu euskerako lokala
  locale_gen:
    name: eu_ES.UTF-8
    state: present

- name: Dpkg-reconfigure
  command: /usr/sbin/dpkg-reconfigure --frontend=noninteractive locales 
  register: out

- name: Update-locale
  command: /usr/sbin/update-locale LANG=eu_ES.UTF-8 LANGUAGE=eu:es
