---
- name: updates repositorioa gehitu 
  apt_repository:
    repo: deb {{ repo }} {{ suite }}-updates {{ compo }}
    state: present

- name: backports repositorioa gehitu 
  apt_repository:
    repo: deb {{ repo }} {{ suite }}-backports {{ compo }}
    state: present

- name: debian security repositorioa gehitu 
  apt_repository:
    repo: deb http://security.debian.org/debian-security {{ suite }}/updates {{ compo }}
    state: present
  when: ansible_os_family == 'Debian'

- name: ubuntu security repositorioa gehitu 
  apt_repository:
    repo: deb http://security.ubuntu.com/ubuntu {{ suite }}-security {{ compo }}
    state: present
  when: ansible_os_family == 'Ubuntu'

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
