---
- name: Eguneratu paketeak azken bertsiora
  apt:
    upgrade: dist

- name: Tasksel oinarrizko paketeak
  command: /usr/bin/tasksel --new-install install standard

- name: Beste paketeak instalatu
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - live-boot
    - screen
    - nfs-common
    - watchdog
    - syslinux
    - syslinux-efi
    - extlinux
    - pv
    - wget
    - squashfs-tools
    - parted
    - atool
    - dosfstools
    - ipxe
    - network-manager
    - sudo
    - inxi
    - haveged
    - clonezilla
    - ntfs-3g

- name: Beste paketeak instalatu
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - firmware-linux-nonfree
    - firmware-atheros
  when: ansible_distribution == 'Debian'

