---
- name: Kernela instalatu
  apt: name=linux-image-amd64

- name: Kernela instalatu
  apt: name=grub-efi-amd64-signed

- name: pcspeaker ez-gaitu
  blockinfile:
    create: yes
    dest: "/etc/modprobe.d/nobeep"
    block: |
      blacklist pcspkr

- name: smart-activation instalatu
  command: update-initramfs -u
  args:
    warn: no
