---
- name: ziurtatu ifup@.service.d karpeta existitzen dela
  file:
    path: "/etc/systemd/system/ifup@.service.d/"
    state: directory

- name: ziurtatu networking.service.d karpeta existitzen dela
  file:
    path: "/etc/systemd/system/networking.service.d/"
    state: directory

- name: override.conf kopiatzen
  copy:
    src: "{{ role_path }}/files/etc/systemd/system/networking.service.d/override.conf"
    dest: "/etc/systemd/system/networking.service.d/override.conf"
    mode: 0644

- name: override.conf kopiatzen
  copy:
    src: "{{ role_path }}/files/etc/systemd/system/networking.service.d/override.conf"
    dest: "/etc/systemd/system/ifup@.service.d/override.conf"
    mode: 0644

- name: botoia sakatzean itzali
  replace:
    dest: /etc/systemd/logind.conf
    regexp: '#HandlePowerKey=poweroff'
    replace: 'HandlePowerKey=poweroff'

- name: systemd journal fitxategiak memorian gorde
  replace:
    dest: /etc/systemd/journald.conf
    regexp: '#Storage=auto'
    replace: 'Storage=volatile'

- name: ocsinventory.service kopiatzen
  copy:
    src: "{{ role_path }}/files/etc/systemd/system/ocsinventory.service"
    dest: "/etc/systemd/system/ocsinventory.service"
    mode: 0644

- name: lortuizena.service kopiatzen
  copy:
    src: "{{ role_path }}/files/etc/systemd/system/lortuizena.service"
    dest: "/etc/systemd/system/lortuizena.service"
    mode: 0644

- name: enable lortuizena 
  file:
    src: /etc/systemd/system/lortuizena.service
    dest: /etc/systemd/system/multi-user.target.wants/lortuizena.service
    state: link

- name: enable ocsinventory
  file:
    src: /etc/systemd/system/ocsinventory.service
    dest: /etc/systemd/system/multi-user.target.wants/ocsinventory.service
    state: link

- name: Remove default local option from ocsinventory-agent.cfg
  lineinfile: 
    dest: /etc/ocsinventory/ocsinventory-agent.cfg
    regexp: '^local='
    line: 'server=192.168.0.107'
