---
- name: ziurtatu ifup@.service.d karpeta existitzen dela
  file:
    path: "/etc/systemd/system/ifup@.service.d/"
    state: directory

- name: ziurtatu networking.service.d karpeta existitzen dela
  file:
    path: "/etc/systemd/system/networking.service.d/"
    state: directory

- name: override.conf kopiatzen
  copy:
    src: "{{ role_path }}/files/etc/systemd/system/networking.service.d/override.conf"
    dest: "/etc/systemd/system/networking.service.d/override.conf"
    mode: 0644

- name: override.conf kopiatzen
  copy:
    src: "{{ role_path }}/files/etc/systemd/system/networking.service.d/override.conf"
    dest: "/etc/systemd/system/ifup@.service.d/override.conf"
    mode: 0644

- name: botoia sakatzean itzali
  replace:
    dest: /etc/systemd/logind.conf
    regexp: '#HandlePowerKey=poweroff'
    replace: 'HandlePowerKey=poweroff'

- name: systemd journal fitxategiak memorian gorde
  replace:
    dest: /etc/systemd/journald.conf
    regexp: '#Storage=auto'
    replace: 'Storage=volatile'

- name: rc.local fitxategia sortu
  blockinfile:
    create: yes
    dest: "/etc/rc.local"
    block: |
      bash /usr/local/bin/lortuizena
      /usr/bin/ocsinventory-agent
      exit 0
