---
- name: formateatu kopiatzen
  copy:
    src: "{{ role_path }}/files/root/prestatu"
    dest: "/root/prestatu"
    mode: 0744

- name: formateatudena kopiatzen
  copy:
    src: "{{ role_path }}/files/root/formateatudena"
    dest: "/root/formateatudena"
    mode: 0744

- name: formateatudenados kopiatzen
  copy:
    src: "{{ role_path }}/files/root/formateatudenados"
    dest: "/root/formateatudenados"
    mode: 0744

- name: instalatu kopiatzen
  copy:
    src: "{{ role_path }}/files/root/instalatu"
    dest: "/root/instalatu"
    mode: 0744

- name: eguneratu kopiatzen
  copy:
    src: "{{ role_path }}/files/root/eguneratu"
    dest: "/root/eguneratu"
    mode: 0744

- name: syslinux.cfg kopiatzen
  copy:
    src: "{{ role_path }}/files/root/syslinux.cfg"
    dest: "/root/syslinux.cfg"
    mode: 0644

- name: syslinux_local.cfg kopiatzen
  copy:
    src: "{{ role_path }}/files/root/syslinux_local.cfg"
    dest: "/root/syslinux_local.cfg"
    mode: 0644

- name: Sortu irudien karpeta
  file:
    path: /erab/irudiak
    state: directory
    mode: 0755

- name: lortudena kopiazen
  copy:
    src: "{{ role_path }}/files/usr/local/bin/lortudena"
    dest: "/usr/local/bin/lortudena"
    mode: 0755

- name: lortumac kopiatzen
  copy:
    src: "{{ role_path }}/files/usr/local/bin/lortumac"
    dest: "/usr/local/bin/lortumac"
    mode: 0755

- name: lortuizena kopiatzen
  copy:
    src: "{{ role_path }}/files/usr/local/bin/lortuizena"
    dest: "/usr/local/bin/lortuizena"
    mode: 0755

- name: katxe kopiatzen
  copy:
    src: "{{ role_path }}/files/usr/local/bin/katxe"
    dest: "/usr/local/bin/katxe"
    mode: 0755
