---
- name: formateatu kopiatzen
  copy:
    src: "{{ role_path }}/files/root/prestatu"
    dest: "/root/prestatu"
    mode: 0744

- name: formateatudena kopiatzen
  copy:
    src: "{{ role_path }}/files/root/formateatudena"
    dest: "/root/formateatudena"
    mode: 0744

- name: instalatu kopiatzen
  copy:
    src: "{{ role_path }}/files/root/eguneratu"
    dest: "/root/eguneratu"
    mode: 0744

- name: syslinux.cfg kopiatzen
  copy:
    src: "{{ role_path }}/files/root/syslinux.cfg"
    dest: "/root/syslinux.cfg"
    mode: 0644

- name: syslinux_local.cfg kopiatzen
  copy:
    src: "{{ role_path }}/files/root/syslinux_local.cfg"
    dest: "/root/syslinux_local.cfg"
    mode: 0644

- name: Sortu irudien karpeta
  file:
    path: /erab/irudiak
    state: directory
    mode: 0755

