#this task installs wine
---
- name: Add i386 packages
  command: /usr/bin/dpkg --add-architecture i386
  when: ansible_architecture == 'x86_64'

- name: apt-get update
  apt:
    update_cache: yes
  when: ansible_architecture == 'x86_64'

- name: Install wine and wine32
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - wine
    - wine32

- name: wineren konfigurazioa aldatu fitxategi elkartzeak ez egiteko
  replace:
    dest: "/usr/share/wine/wine/wine.inf"
    regexp: 'winemenubuilder.exe -a -r'
    replace: 'winemenubuilder.exe -r'

