#this task installs wine
---
- name: Add i386 packages
  command: /usr/bin/dpkg --add-architecture i386
  when: ansible_architecture == 'x86_64'

- name: apt-get update
  apt:
    update_cache: yes
  when: ansible_architecture == 'x86_64'

- name: Install wine and wine32
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - wine
    - wine32

#xvfb-run winesudo exit
#xvfb-run wine exit
