#portatilak konfiguratzeko
---
  - name: Hau portatil bat dela esan.
    file:
      path: /root/portatila
      state: touch
      mode: 0600

  - name: laptop atazako programak.
    apt:
      name: "{{ packages }}"
    vars:
      packages:
       - avahi-autoipd
       - bluetooth
       - powertop
       - iw
       - wireless-tools
       - wpasupplicant

#tlp eta pm-utils bateria hobetzeko dira
  - name: Portatilen progrmak instalatu.
    apt:
      name: "{{ packages }}"
    vars:
      packages:
       - network-manager
       - tlp
       - pm-utils

  - name: Firmwareak instalatu. Debian.
    apt:
      name: "{{ packages }}"
    vars:
      packages:
       - firmware-iwlwifi
       - firmware-atheros
    when: ansible_distribution == 'Debian'

#  - name: Firmwareak instalatu. Ubuntu.
#    apt:
#      name: "{{ packages }}"
#    vars:
#      packages:
#       - backport-iwlwifi-dkms
#       - firmware-ath9k-htc
#    when: ansible_distribution == 'Ubuntu'

  - name: Defektuz bloknum kendu.
    copy:
      src: "{{ role_path }}/files/keyboards.xml"
      dest: "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/keyboards.xml"
      mode: 0644

  - name: Erlojuaren ondoan bateriaren ikonoa jarri.
    copy:
      src: "{{ role_path }}/files/xfce4-power-manager.xml"
      dest: "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml"
      mode: 0644

  - name: Tapa ixterakoan portatila itzali dadila.
    replace:
      dest: /etc/systemd/logind.conf
      regexp: '#HandleLidSwitch=suspend'
      replace: 'HandleLidSwitch=poweroff'

  - name: Gure wifia konfiguratu.
    template:
      src: "{{ role_path }}/templates/wifia.j2"
      dest: /etc/NetworkManager/system-connections/wifia.nmconnection
      owner: root
      mode: '0600'

  - name: Jarri nm-applet hasieran.
    copy:
      src: /usr/share/applications/nm-applet.desktop
      dest: /etc/xdg/autostart/nm-applet.desktop
      mode: 0644
      remote_src: yes

