---
- hosts: all
  connection: local

  vars:
    - tftp: /home/cesar/irudiak/{{ izen_motza }}

  tasks:

    - name: cleanup | sparse files
      shell: /bin/rm -rf {{ inventory_hostname }}/var/cache/apt/archives/*.deb
      args:
        warn: no

    - name: cleanup | sparse files
      shell: /bin/rm -rf {{ inventory_hostname }}/var/cache/apt/archives/partial/*
      args:
        warn: no

    - name: cleanup | sparse files
      shell: /bin/rm -rf {{ inventory_hostname }}/var/cache/debconf/*-old
      args:
        warn: no

    - name: cleanup | sparse files
      shell: /bin/rm -rf {{ inventory_hostname }}/var/lib/apt/lists/*
      args:
        warn: no

    - name: ziurtatu isolinux karpeta existitzen dela
      file:
        path: "{{ tftp }}/isolinux"
        state: directory

    - name: kopiatu initrd
      copy:
        src: "{{ inventory_hostname }}/initrd.img"
        dest: "{{ tftp }}/live/initrd.img"
        mode: 0644

    - name: kopiatu vmlinuz
      copy:
        src: "{{ inventory_hostname }}/vmlinuz"
        dest: "{{ tftp }}/live/vmlinuz"
        mode: 0644

    - name: kopiatu isolinux.bin
      copy:
        src: /usr/lib/ISOLINUX/isolinux.bin
        dest: "{{ tftp }}/isolinux/isolinux.bin"
        mode: 0644

    - name: kopiatu ldlinux.c32
      copy:
        src: /usr/lib/syslinux/modules/bios/ldlinux.c32
        dest: "{{ tftp }}/isolinux/ldlinux.c32"
        mode: 0644

    - name: kopiatu isohdpfx.bin
      copy:
        src: /usr/lib/ISOLINUX/isohdpfx.bin
        dest: "{{ tftp }}/isolinux/isohdpfx.bin"
        mode: 0644

    - name: menua prestatu
      blockinfile:
        path: "{{ tftp }}/isolinux/isolinux.cfg"
        create: yes
        block: |
          default live
          label live
          kernel /live/vmlinuz
          initrd /live/initrd.img
          append boot=live quiet

    - name: filesystem.squashfs sortu
      command: chdir={{ inventory_hostname }}/../ mksquashfs squashfs-root filesystem.squashfs

    - name: kendu squashfs-root karpeta
      file: 
        path="{{ inventory_hostname }}"
        state=absent

    - name: livecd sortu
      command: xorriso -as mkisofs \
              -iso-level 3 \  
              -full-iso9660-filenames \
              -volid "{{ izen_motza }}" \
              -eltorito-boot isolinux/isolinux.bin \
              -eltorito-catalog isolinux/boot.cat \
              -no-emul-boot -boot-load-size 4 -boot-info-table \
              -isohybrid-mbr {{ tftp }}/isolinux/isohdpfx.bin \
              -output {{ tftp }}/../{{ izen_motza }}.iso {{ tftp }}

