---
- hosts: all
  connection: local
  vars:
    - smart: "{{ 'smart64.yml' if arch == 'amd64' else 'smart32.yml' }}"

  tasks:
  - include: tasks/prestatu.yml ansible_connection=chroot

  - include: tasks/{{ smart }} ansible_connection=chroot

  - include: tasks/irten.yml ansible_connection=chroot
