---
- hosts: buster
  connection: local
  vars:
    - repo: http://ftp.fr.debian.org/debian
    - include_packages: openssh-server,python,python-apt,locales,keyboard-configuration,console-setup
    - helbidea: /home/irudiak/{{ izen_motza }}/live
    - nora: "{{ inventory_hostname }}"
    - nondik: /home/scriptak/konfigurazioak
    - kernel: "{{ 'kernel64.yml' if arch == 'amd64' else 'kernel32.yml' }}"

  tasks:
  - name: begiratu aurretik instalazio bat egina dagoen
    stat:
      path: "{{ helbidea }}/filesystem.squashfs"
    register: stat_result

  - name: Existizen da!
    fail: msg="Existitzen da"
    when: stat_result.stat.exists == True

  - name: Instalazio berria sortu deboostrap erabiliz
    command: /usr/sbin/debootstrap
             --arch={{ arch }}
             --include={{ include_packages }}
             --components=main,contrib,non-free
             {{ suite }} {{ inventory_hostname }} {{ repo }}
    when: stat_result.stat.exists == False 

  - include: tasks/lokala.yml ansible_connection=chroot

  - include: tasks/teklatua.yml ansible_connection=chroot

  - include: tasks/erabiltzaileak.yml ansible_connection=chroot

  - include: tasks/ordua.yml ansible_connection=chroot

  - include: tasks/repobuster.yml ansible_connection=chroot repoa={{ repo }}

  - include: tasks/prestatu.yml ansible_connection=chroot

  - include: tasks/{{ kernel }} ansible_connection=chroot

  - include: tasks/paketeakbuster.yml ansible_connection=chroot

  - include: tasks/scriptak.yml bat={{ nondik }} bi={{ nora }}

  - include: tasks/irten.yml ansible_connection=chroot

  - name: pcspeaker ez-gaitu
    blockinfile:
      create: yes
      dest: "{{ inventory_hostname }}/etc/modprobe.d/nobeep"
      block: |
        blacklist pcspkr
