---
- hosts: sortu
  connection: local
  vars:
    - repo: http://192.168.0.1:3142/debian
    - include_packages: locales,lsb-release,openssh-server,python,python-apt,sudo,console-setup,keyboard-configuration
    - kernel: "{{ 'linux-image-amd64' if arch == 'amd64' else 'linux-image-686-pae' }}"
    - tftp: /home/irudiak/tftp/{{ izen_motza }}
    - helbidea: /home/irudiak/{{ izen_motza }}/live

  tasks:
  - name: begiratu aurretik instalazio bat egina dagoen
    stat:
      path: "{{ helbidea }}/filesystem.squashfs"
    register: stat_result

  - name: Existizen da!
    fail: msg="Existitzen da"
    when: stat_result.stat.exists == True

  - name: Instalazio berria sortu deboostrap erabiliz
    command: /usr/sbin/debootstrap
             --arch={{ arch }}
             --include={{ include_packages }}
             --components=main,contrib,non-free
             {{ suite }} {{ inventory_hostname }} {{ repo }}
    when: stat_result.stat.exists == False 

  - include: tasks/lokala.yml ansible_connection=chroot

  - include: tasks/teklatua.yml ansible_connection=chroot

  - include: tasks/erabiltzaileak.yml ansible_connection=chroot

  - include: tasks/ordua.yml ansible_connection=chroot

  - include: tasks/i386.yml ansible_connection=chroot

  - include: tasks/prestatu.yml ansible_connection=chroot

  - include: tasks/kernel.yml ansible_connection=chroot paketea={{ kernel }}

  - include: tasks/paketeak.yml ansible_connection=chroot

  - include: tasks/irten.yml ansible_connection=chroot

  - name: pcspeaker ez-gaitu
    blockinfile:
      create: yes
      dest: "{{ inventory_hostname }}/etc/modprobe.d/nobeep"
      block: |
        blacklist pcspkr
