---
- hosts: sortu
  connection: local

  vars:
    - tftp: /home/irudiak/tftp/{{ izen_motza }}

  tasks:

    - name: cleanup | sparse files
      shell: /bin/rm -rf {{ inventory_hostname }}/var/cache/apt/archives/*.deb
      args:
        warn: no

    - name: cleanup | sparse files
      shell: /bin/rm -rf {{ inventory_hostname }}/var/cache/apt/archives/partial/*
      args:
        warn: no

    - name: cleanup | sparse files
      shell: /bin/rm -rf {{ inventory_hostname }}/var/cache/debconf/*-old
      args:
        warn: no

    - name: cleanup | sparse files
      shell: /bin/rm -rf {{ inventory_hostname }}/var/lib/apt/lists/*
      args:
        warn: no

    - name: ziurtatu tftp karpeta existitzen dela
      file:
        path: "{{ tftp }}"
        state: directory

    - name: kopiatu initrd
      copy:
        src: "{{ inventory_hostname }}/initrd.img"
        dest: "{{ tftp }}/initrd.img"
        mode: 0644

    - name: kopiatu vmlinuz
      copy:
        src: "{{ inventory_hostname }}/vmlinuz"
        dest: "{{ tftp }}/vmlinuz"
        mode: 0644

    - name: filesystem.squashfs sortu
      command: chdir={{ inventory_hostname }}/../ mksquashfs squashfs-root filesystem.squashfs

    - name: kendu squashfs-root karpeta
      file: 
        path="{{ inventory_hostname }}"
        state=absent
