#gutxieneko zerbitzari grafikoa instalatzen du honek
---
- name: Xorg paketeak debian.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - xorg
    - mesa-utils
  when: ansible_distribution == 'Debian'

- name: Xorg paketeak ubuntu.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - xorg
    - mesa-utils
    - xserver-xorg-video-all
    - xserver-xorg-video-amdgpu
    - xserver-xorg-video-ati
    - xserver-xorg-video-radeon
    - xserver-xorg-video-dummy
    - xserver-xorg-video-fbdev
    - xserver-xorg-video-intel
    - xserver-xorg-video-nouveau
    - xserver-xorg-video-qxl
    - xserver-xorg-video-vesa
    - xserver-xorg-video-vmware
    - xserver-xorg-video-mga
    - xserver-xorg-video-openchrome
  when: ansible_distribution == 'Ubuntu'

#- name: Tearfree aukera gehitu.
#  copy:
#    src: "{{ role_path }}/files/{{ item }}"
#    dest: "/{{ item }}"
#    mode: 0644
#  with_items:   
#     - "usr/share/X11/xorg.conf.d/20-intel.conf"
#     - "usr/share/X11/xorg.conf.d/10-amdgpu.conf"
#  when: ansible_distribution_release == 'focal'

- name: Proiektorearentzako script-ak kopiatu.
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/{{ item }}"
    mode: 0755
  with_items:
    - "usr/local/bin/bikoiztu"
    - "usr/local/bin/ezker"
    - "usr/local/bin/eskubi"
    - "usr/local/bin/betipiztuta"

- name: i3lock-fancy instalatu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - i3lock
    - i3lock-fancy

- name: Prestatu i3lock-fancy2
  file:
    path: /usr/share/i3lock-fancy2
    state: directory

- name: Jaitsi i3lock-fancy2
  get_url:
    url: https://github.com/guimeira/i3lock-fancy-multimonitor/raw/master/lock
    dest: /usr/local/bin/i3lock-fancy2
    mode: '0755'

- name: Jaitsi i3lock-fancy2 irudia1
  get_url:
    url: https://github.com/guimeira/i3lock-fancy-multimonitor/raw/master/lock.png
    dest: /usr/share/i3lock-fancy2/lock.png
    mode: '0644'

- name: i3lock-fancy2 irudia kopiatu
  copy:
    src: "{{ role_path }}/files/usr/share/i3lock-fancy2/text.png"
    dest: "/usr/share/i3lock-fancy2/text.png"
    mode: '0644'

- name: i3lock-fancy2 konfiguratu
  lineinfile:
    dest: /usr/local/bin/i3lock-fancy2
    regexp: '^(.*)FOLDER=(.*)$'
    line: 'FOLDER="/usr/share/i3lock-fancy2"'

- name: i3lock-fancy2 konfiguratu
  lineinfile:
    dest: /usr/local/bin/i3lock-fancy2
    regexp: '1x1'
    line: 'BLURTYPE="5x5"'
