#gutxieneko zerbitzari grafikoa instalatzen du honek
---
- name: Xorg paketeak no-recommends.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - xorg
    - xserver-xorg-video-all
    - xserver-xorg-video-amdgpu
    - xserver-xorg-video-ati
    - xserver-xorg-video-radeon
    - xserver-xorg-video-dummy
    - xserver-xorg-video-fbdev
    - xserver-xorg-video-intel
    - xserver-xorg-video-nouveau
    - xserver-xorg-video-qxl
    - xserver-xorg-video-vesa
    - xserver-xorg-video-vmware
    - xserver-xorg-video-mga
    - xserver-xorg-video-openchrome
    - autorandr

- name: Tearfree aukera gehitu.
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/{{ item }}"
    mode: 0644
  with_items:   
     - "usr/share/X11/xorg.conf.d/20-intel.conf"
     - "usr/share/X11/xorg.conf.d/10-amdgpu.conf"

