#gutxieneko idazmaia instalatzen du honek. xfce ubuntu edo debian-entzat
---
- name: Xfce paketeak no-recommends.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - xorg
    - xserver-xorg-video-intel
    - xserver-xorg-video-all
    - lightdm
    - xfce4
    - atril
    - network-manager-gnome
    - kfind
    - policykit-1-gnome
    - gmessage

- name: Xfce paketeak recommends.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - xfce4-goodies
    - pulseaudio
    - pavucontrol
    - avahi-daemon
    - libu2f-udev
    - lxtask
    - gparted
    - usermode
    - gpicview
    - smplayer
    - tango-icon-theme
    - gnome-themes-extra
    - ssh 
    - sshfs 
    - nfs-common
    - cifs-utils
    - gvfs-backends 
    - gvfs-fuse
    - file-roller
    - dconf-cli
    - xdg-user-dirs

- name: File-roller konfiguratu
  copy:
    src: "{{ role_path }}/files/etc/dconf"
    dest: "/etc"

- name: Dconf eguneratu
  command: "dconf update"

- name: Gtk3-enginges-xfce Debian.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - gtk3-engines-xfce
  when: ansible_distribution == 'Debian'

- name: Adwaita Ubuntu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - adwaita-icon-theme-full
  when: ansible_distribution == 'Ubuntu'

- name: xfc4-terminal lehenetsi.
  alternatives:
    name: x-terminal-emulator
    path: /usr/bin/xfce4-terminal.wrapper
  when: ansible_distribution == 'Ubuntu'

- name: Gaia eta ikonoak ezarri.
  copy:
    src: "{{ role_path }}/files/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml"
    dest: "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml"
    mode: 0644

- name: xfce4-terminal konfigurazio karpeta sortu.
  file:
    path: "/etc/xdg/xfce4/terminal"
    state: directory

- name: xfce4-terminal konfiguratu.
  copy:
    src: "{{ role_path }}/files/etc/xdg/xfce4/terminal/terminalrc"
    dest: "/etc/xdg/xfce4/terminal/terminalrc"
    mode: 0644

- name: Screen-saver kendu.
  file:
    path: "/etc/xdg/autostart/xscreensaver.desktop"
    state: absent

- name: light-locker kendu.
  file:
    path: "/etc/xdg/autostart/light-locker.desktop"
    state: absent

- name: nm-applet ikonoa kendu, bezeroek ez dute behar.
  file:
    path: "/etc/xdg/autostart/nm-applet.desktop"
    state: absent

- name: Eseki edo suspenditzeko aukera kendu.
  copy:
    src: "{{ role_path }}/files/etc/polkit-1/localauthority/50-local.d/suspend.pkla"
    dest: "/etc/polkit-1/localauthority/50-local.d/suspend.pkla"
    mode: 0644

- name: Kiosk konfigurazio karpeta sortu.
  file:
    path: "/etc/xdg/xfce4/kiosk"
    state: directory

- name: Kiosk konfiguratu konfiguratu, saioa ez gordetzeko.
  copy:
    src: "{{ role_path }}/files/etc/xdg/xfce4/kiosk/kioskrc"
    dest: "/etc/xdg/xfce4/kiosk/kioskrc"
    mode: 0644

- name: kfind abiarazlea kopiatu.
  copy:
    src: "{{ role_path }}/files/usr/share/applications/kfind.desktop"
    dest: "/usr/share/applications/kfind.desktop"
    mode: 0644

- name: xorg konfiguratu intel txartelentzat. tearfree.
  copy:
    src: "{{ role_path }}/files/usr/share/X11/xorg.conf.d/20-intel.conf"
    dest: "/usr/share/X11/xorg.conf.d/20-intel.conf"
    mode: 0644

- name: Audioa gaitu haiseran.
  copy:
    src: "{{ role_path }}/files/usr/share/applications/unmute.desktop"
    dest: "/etc/xdg/autostart/unmute.desktop"
    mode: 0644

- name: QT programen itxura konfiguratu.
  copy:
    src: "{{ role_path }}/files/etc/xdg/Trolltech.conf"
    dest: "/etc/xdg/Trolltech.conf"
    mode: 0644

- name: smplayer karpeta sortu skel barruan.
  file:
    path: /etc/skel/.config/smplayer
    state: directory
    mode: 0755

- name: smplayer konfiguratu.
  copy:
    src: "{{ role_path }}/files/etc/skel/.config/smplayer/smplayer.ini"
    dest: /etc/skel/.config/smplayer/smplayer.ini
    mode: 0644

- name: Kendu youtube-dl bertsio zaharra.
  apt:
    name: youtube-dl
    state: absent

- name: Instalatu youtube-dl bertsio berria.
  get_url:
    url: https://yt-dl.org/downloads/latest/youtube-dl
    dest: /usr/local/bin/youtube-dl
    mode: 0755
