---
- name: Minimo no-recommends
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - xorg
    - lightdm
    - lightdm-gtk-greeter
    - xfce4
    - atril
    - network-manager-gnome
    - kfind

- name: Minimo recommends
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - xfce4-goodies
    - pulseaudio
    - avahi-daemon
    - libu2f-udev
    - lxtask
    - gparted
    - usermode
    - gpicview
    - smplayer
    - tango-icon-theme
    - gnome-themes-extra

- name: Extra Debian
  apt:
    name: "{{ packages }}"
  vars:
    packages:
#    - xserver-xorg-video-all
#    - xserver-xorg-input-all
    - gtk3-engines-xfce
  when: ansible_distribution == 'Debian'

- name: Extra Ubuntu
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - adwaita-icon-theme-full
  when: ansible_distribution == 'Ubuntu'

- name: lightdm itxura aldatu ubuntu
  blockinfile:
    dest: "/etc/lightdm/lightdm-gtk-greeter.conf"
    block: |
      background=/usr/share/backgrounds/xfce/xfce-stripes.png
      indicators=~host;~spacer;~session;~clock;~power;
  when: ansible_distribution == 'Ubuntu'

- name: lightdm itxura erabiltzaileak ubuntu
  blockinfile:
    dest: "/usr/share/lightdm/lightdm.conf.d/50-greeter-hide-users.conf"
    create: yes
    block: |
      [Seat:*]
      greeter-hide-users=true
  when: ansible_distribution == 'Ubuntu'

- name: lightdm itxura aldatu debian
  blockinfile:
    dest: "/etc/lightdm/lightdm-gtk-greeter.conf"
    block: |
      background=/usr/share/backgrounds/xfce/xfce-teal.jpg
      indicators=~host;~spacer;~session;~clock;~power;
  when: ansible_distribution == 'Debian'

- name: erabiltzaile karpetak ezartzen
  copy:
    src: "{{ role_path }}/files/etc/xdg/user-dirs.defaults"
    dest: "/etc/xdg/user-dirs.defaults"
    mode: 0644

- name: eseki politika jartzen
  copy:
    src: "{{ role_path }}/files/etc/polkit-1/localauthority/50-local.d/eseki.pkla"
    dest: "/etc/polkit-1/localauthority/50-local.d/eseki.pkla"
    mode: 0644

- name: proiektorearen kudeatzailea instalatzen
  copy:
    src: "{{ role_path }}/files/usr/local/bin/proiektorea"
    dest: "/usr/local/bin/proiektorea"
    mode: 0755

- name: proiektorearen kudeatzailea instalatzen
  copy:
    src: "{{ role_path }}/files/usr/local/bin/proiektorea2"
    dest: "/usr/local/bin/proiektorea2"
    mode: 0755

- name: kendu toggle instalatzen
  copy:
    src: "{{ role_path }}/files/usr/local/bin/kendutoggle"
    dest: "/usr/local/bin/kendutoggle"
    mode: 0755

- name: ziurtatu applications karpeta existitzen dela
  file:
    path: "/usr/local/share/applications"
    state: directory
