---
- name: Minimo no-recommends
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - xorg
    - lightdm
    - lightdm-gtk-greeter
    - xfce4
    - atril
    - network-manager-gnome
    - kfind

- name: Minimo recommends
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - xfce4-goodies
    - pulseaudio
    - avahi-daemon
    - libu2f-udev
    - lxtask
    - gparted
    - usermode
    - gpicview
    - smplayer
    - tango-icon-theme
    - gnome-themes-extra

- name: Extra Debian
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - gtk3-engines-xfce
  when: ansible_distribution == 'Debian'

- name: Extra Ubuntu
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - adwaita-icon-theme-full
  when: ansible_distribution == 'Ubuntu'

- name: default terminal in ubuntu
  alternatives:
    name: x-terminal-emulator
    path: /usr/bin/xfce4-terminal.wrapper
  when: ansible_distribution == 'Ubuntu'

- name: lightdm itxura aldatu ubuntu
  blockinfile:
    dest: "/etc/lightdm/lightdm-gtk-greeter.conf"
    block: |
      background=/usr/share/backgrounds/xfce/xfce-stripes.png
      indicators=~host;~spacer;~session;~clock;~power;
  when: ansible_distribution == 'Ubuntu'

- name: lightdm ezkutatu erabiltzaileak ubuntu
  blockinfile:
    dest: "/usr/share/lightdm/lightdm.conf.d/50-greeter-hide-users.conf"
    create: yes
    block: |
      [Seat:*]
      greeter-hide-users=true
  when: ansible_distribution == 'Ubuntu'

- name: lightdm itxura aldatu debian
  blockinfile:
    dest: "/etc/lightdm/lightdm-gtk-greeter.conf"
    block: |
      background=/usr/share/backgrounds/xfce/xfce-teal.jpg
      indicators=~host;~spacer;~session;~clock;~power;
  when: ansible_distribution == 'Debian'

- name: ikonoak eta gaia konfiguratzen ubuntu
  copy:
    src: "{{ role_path }}/files/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml"
    dest: "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml"
    mode: 0644
  when: ansible_distribution == 'Ubuntu'

- name: erabiltzaile karpetak ezartzen
  copy:
    src: "{{ role_path }}/files/etc/xdg/user-dirs.defaults"
    dest: "/etc/xdg/user-dirs.defaults"
    mode: 0644

- name: eseki politika jartzen
  copy:
    src: "{{ role_path }}/files/etc/polkit-1/localauthority/50-local.d/eseki.pkla"
    dest: "/etc/polkit-1/localauthority/50-local.d/eseki.pkla"
    mode: 0644

- name: proiektorearen kudeatzailea instalatzen
  copy:
    src: "{{ role_path }}/files/usr/local/bin/proiektorea"
    dest: "/usr/local/bin/proiektorea"
    mode: 0755

- name: proiektorearen kudeatzailea instalatzen
  copy:
    src: "{{ role_path }}/files/usr/local/bin/proiektorea2"
    dest: "/usr/local/bin/proiektorea2"
    mode: 0755

- name: kendu toggle instalatzen
  copy:
    src: "{{ role_path }}/files/usr/local/bin/kendutoggle"
    dest: "/usr/local/bin/kendutoggle"
    mode: 0755

- name: ziurtatu applications karpeta existitzen dela
  file:
    path: "/usr/local/share/applications"
    state: directory

- name: ziurtatu terminal karpeta existitzen dela
  file:
    path: "/etc/xdg/xfce4/terminal"
    state: directory

- name: xfce terminala konfiguratzen
  copy:
    src: "{{ role_path }}/files/etc/xdg/xfce4/terminal/terminalrc"
    dest: "/etc/xdg/xfce4/terminal/terminalrc"
    mode: 0644

- name: Kendu screen-saver
  file:
    path: "/etc/xdg/autostart/xscreensaver.desktop"
    state: absent

- name: Kendu light-locker
  file:
    path: "/etc/xdg/autostart/light-locker.desktop"
    state: absent

- name: ziurtatu kiosk karpeta existitzen dela
  file:
    path: "/etc/xdg/xfce4/kiosk"
    state: directory

- name: kiosk ezarpenak jartzen
  copy:
    src: "{{ role_path }}/files/etc/xdg/xfce4/kiosk/kioskrc"
    dest: "/etc/xdg/xfce4/kiosk/kioskrc"
    mode: 0644

- name: kfind abiarazlea kopiatu
  copy:
    src: "{{ role_path }}/files/usr/share/applications/kfind.desktop"
    dest: "/usr/share/applications/kfind.desktop"
    mode: 0644

- name: QT aplikazioen gaia aldatu
  copy:
    src: "{{ role_path }}/files/etc/xdg/Trolltech.conf"
    dest: "/etc/xdg/Trolltech.conf"
    mode: 0644
