#sddm instalatu greeter sinple batekin debian eta ubuntu
---
- name: sddm instalatu.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - sddm
    - qml-module-qtgraphicaleffects
    - qml-module-qtquick-controls2
    - autorandr
#    - git

- name: Kendu plasma sesioa.
  file:
    path: "/usr/share/xsessions/plasma.desktop"
    state: absent

- name: Sortu sddm-ren konfigurazioen karpeta.
  file:
    path: "/etc/sddm.conf.d"
    state: directory

- name: Sortu sddm-ren gaientzako karpeta.
  file:
    path: "/usr/share/sddm/themes/sddm-theme-dialog"
    state: directory

- name: Deskargatu gai sinple bat.
  unarchive:
    src: https://github.com/joshuakraemer/sddm-theme-dialog/archive/main.zip
    dest: /usr/share/sddm/themes/sddm-theme-dialog
    remote_src: yes

#https://github.com/joshuakraemer/sddm-theme-dialog theme
#- name: Deskargatu gai sinple bat.
#  git:
#    repo: 'https://github.com/joshuakraemer/sddm-theme-dialog'
#    dest: /usr/share/sddm/themes/sddm-theme-dialog

- name: sddm konfigurazioak kopiatu.
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/{{ item }}"
    mode: 0644
  with_items:
    - "etc/sddm.conf.d/tty.conf"
    - "etc/sddm.conf.d/theme.conf"

- name: Tearfree aukera gehitu.
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/{{ item }}"
    mode: 0644
  with_items:   
     - "usr/share/X11/xorg.conf.d/20-intel.conf"
     - "usr/share/X11/xorg.conf.d/10-amdgpu.conf"
