#sddm instalatu greeter sinple batekin debian eta ubuntu
---
- name: sddm instalatu.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - sddm
    - qml-module-qtgraphicaleffects
    - qml-module-qtquick-controls2
    - unzip
    - sddm-theme-maldives

- name: gaia pixkat aldatu sinpleago egiteko.
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/{{ item }}"
    mode: 0644
  with_items:
    - "/usr/share/sddm/themes/maldives/Main.qml"

- name: Jarri xfce-ren mahaigaineko irudia hemen ere
  replace:
    dest: "/usr/share/sddm/themes/maldives/theme.conf"
    regexp: '^(.*)background=(.*)$'
    replace: 'background=/usr/share/backgrounds/xfce/xfce-verticals.png'
  when: ansible_distribution_release == 'bullseye'

- name: Jarri xfce-ren mahaigaineko irudia hemen ere
  replace:
    dest: "/usr/share/sddm/themes/maldives/theme.conf"
    regexp: '^(.*)background=(.*)$'
    replace: 'background=/usr/share/backgrounds/xfce/xfce-shapes.svg'
  when: ansible_distribution_release == 'bookworm'

#sudo update-alternatives --install /usr/share/sddm/themes/ubuntu-theme sddm-ubuntu-theme /usr/share/sddm/themes/sddm-theme-dialog-main 1

#bullseye default
#/usr/share/backgrounds/xfce/xfce-verticals.png

#focal default
#/usr/share/backgrounds/xfce/xfce-stripes.png
