#sddm instalatu greeter sinple batekin debian eta ubuntu
---
- name: sddm instalatu.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - sddm
    - qml-module-qtgraphicaleffects
    - qml-module-qtquick-controls2
    - unzip
    - sddm-theme-maldives

- name: sddm euskerazko itzulpena kopiatu.
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/{{ item }}"
    mode: 0644
  with_items:
    - "usr/share/sddm/translations/eu.qm"
  when: ansible_distribution_release == 'focal'

- name: gaia pixkat aldatu sinpleago egiteko.
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/{{ item }}"
    mode: 0644
  with_items:
    - "/usr/share/sddm/themes/maldives/Main.qml"

- name: Jarri xfce-ren mahaigaineko irudia hemen ere. Debian.
  replace:
    dest: "/usr/share/sddm/themes/maldives/theme.conf"
    regexp: '^(.*)background=(.*)$'
    replace: 'background=/usr/share/backgrounds/xfce/xfce-teal.jpg'
  when: ansible_distribution_release == 'buster'

- name: Jarri xfce-ren mahaigaineko irudia hemen ere. Ubuntu.
  replace:
    dest: "/usr/share/sddm/themes/sddm-theme-dialog-main/theme.conf"
    regexp: '^(.*)background=(.*)$'
    replace: 'background=/usr/share/backgrounds/xfce/xfce-stripes.png'
  when: ansible_distribution_release != 'buster'

#sudo update-alternatives --install /usr/share/sddm/themes/ubuntu-theme sddm-ubuntu-theme /usr/share/sddm/themes/sddm-theme-dialog-main 1

