#sddm instalatu greeter sinple batekin debian eta ubuntu
---
- name: sddm instalatu.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - sddm
    - qml-module-qtgraphicaleffects
    - qml-module-qtquick-controls2
    - unzip

#- name: Kendu plasma sesioa.
#  file:
#    path: "/usr/share/xsessions/plasma.desktop"
#    state: absent

- name: Sortu sddm-ren konfigurazioen karpeta.
  file:
    path: "/etc/sddm.conf.d"
    state: directory

- name: Sortu sddm-ren gaientzako karpeta.
  file:
    path: "/usr/share/sddm/themes"
    state: directory

#https://github.com/joshuakraemer/sddm-theme-dialog theme
- name: Deskargatu gai sinple bat.
  unarchive:
    src: https://github.com/cesetxeberria/sddm-theme-dialog/archive/main.zip
    dest: /usr/share/sddm/themes
    remote_src: yes

- name: sddm konfigurazioak eta euskerazko itzulpena kopiatu.
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/{{ item }}"
    mode: 0644
  with_items:
    - "etc/sddm.conf.d/theme.conf"
    - "usr/share/sddm/translations/eu.qm"
    - "etc/xdg/autostart/bikoiztu.desktop"

- name: Estiloa aldatu.
  replace:
    dest: "/usr/share/sddm/themes/sddm-theme-dialog-main/theme.conf"
    regexp: 'style=Fusion'
    replace: 'style=Imagine'

- name: Jarri xfce-ren mahaigaineko irudia hemen ere. Debian.
  replace:
    dest: "/usr/share/sddm/themes/sddm-theme-dialog-main/theme.conf"
    regexp: '^(.*)backgroundImage=(.*)$'
    replace: 'backgroundImage=/usr/share/backgrounds/xfce/xfce-teal.jpg'
  when: ansible_distribution == 'Debian'

- name: Jarri xfce-ren mahaigaineko irudia hemen ere. Ubuntu.
  replace:
    dest: "/usr/share/sddm/themes/sddm-theme-dialog-main/theme.conf"
    regexp: '^(.*)backgroundImage=(.*)$'
    replace: 'backgroundImage=/usr/share/backgrounds/xfce/xfce-stripes.png'
  when: ansible_distribution == 'Ubuntu'
