---
- name: xfwm lehio kudeatzailea konfiguratzen
  copy:
    src: "{{ role_path }}/files/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml"
    dest: "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml"
    mode: 0644

- name: energia kudeatzailea konfiguratzen
  copy:
    src: "{{ role_path }}/files/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml"
    dest: "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml"
    mode: 0644

- name: ikonoak eta gaia konfiguratzen
  copy:
    src: "{{ role_path }}/files/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml"
    dest: "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml"
    mode: 0644

- name: thunar konfiguratzen
  copy:
    src: "{{ role_path }}/files/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/thunar.xml"
    dest: "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/thunar.xml"
    mode: 0644

- name: panela konfiguratzen
  copy:
    src: "{{ role_path }}/files/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml"
    dest: "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml"
    mode: 0644

- name: panela konfiguratzen2
  copy:
    src: "{{ role_path }}/files/etc/xdg/xfce4/panel/default.xml"
    dest: "/etc/xdg/xfce4/panel/default.xml"
    mode: 0644

- name: whisker panela konfiguratzen
  copy:
    src: "{{ role_path }}/files/etc/xdg/xfce4/panel/whiskermenu-1.rc"
    dest: "/etc/xdg/xfce4/panel/whiskermenu-1.rc"
    mode: 0644

- name: teklatu lasterbideak konfiguratzen
  copy:
    src: "{{ role_path }}/files/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml"
    dest: "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml"
    mode: 0644

- name: mahaigaina konfiguratzen
  copy:
    src: "{{ role_path }}/files/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml"
    dest: "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml"
    mode: 0644

- name: teklatuan blocknum jartzen
  copy:
    src: "{{ role_path }}/files/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/keyboards.xml"
    dest: "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/keyboards.xml"
    mode: 0644
