---
- name: Hizkuntzak instalatu
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - aspell-eu
    - aspell-es
    - ispanish
    - wspanish
    - debian-reference-es
    - util-linux-locales
    - myspell-es

- name: Hizkuntzak instalatu kde ubuntu
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - manpages-es-extra
    - language-pack-kde-eu
    - language-pack-kde-es
  when: ansible_distribution == 'Ubuntu'

- name: Hizkuntzak instalatu kde debian
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - manpages-es
    - kde-l10n-es
    - kde-l10n-eu
  when: ansible_distribution == 'Debian'

