#gutxieneko idazmaia instalatzen du honek. dwm ubuntu edo debian-entzat.
---
- name: dwm eta dependentziak.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - dwm 
    - suckless-tools
    - x11-xserver-utils 
    - stterm
    - atril
    - network-manager-gnome
    - policykit-1-gnome
    - gmessage

- name: Beste paketeak recommends.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - fonts-liberation
    - pulseaudio
    - pavucontrol
    - volumeicon-alsa
    - gparted
    - mpv
    - ssh 
    - sshfs 
    - nfs-common
    - cifs-utils
    - gvfs-backends 
    - gvfs-fuse
    - xdg-user-dirs
    - numlockx

- name: Kendu youtube-dl bertsio zaharra.
  apt:
    name: youtube-dl
    state: absent

- name: Instalatu youtube-dl bertsio berria.
  get_url:
    url: https://yt-dl.org/downloads/latest/youtube-dl
    dest: /usr/local/bin/youtube-dl
    mode: 0755

- name: Beharrezko konfigurazioak kopiatu.
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/{{ item }}"
    mode: 0644
  with_items:
     - "etc/xdg/Trolltech.conf"
     - "etc/xdg/user-dirs.defaults"
     - "etc/skel/.xinitrc"
     - "etc/skel/.bash_profile"
     - "etc/skel/.inputrc"
     - "etc/skel/.gtkrc-2.0"

- name: Gure scriptak kopiatu
  copy:
    src: "{{ role_path }}/files/usr/local/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
  with_items:
     - ikusionline
     - kendutoggle
     - proiektorea
     - xrandreset

- name: konpilatzeko prestatu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - git
    - build-essential
    - libx11-dev
    - libxft-dev
    - libxinerama-dev

- name: dwm iturriak jaitsi
  git:
    repo: 'https://git.suckless.org/dwm'
    dest: /opt/dwm

- name: Download tray patch using wget
  command: /usr/bin/wget -O /opt/dwm/tray.diff "https://dwm.suckless.org/patches/systray/dwm-systray-20200914-61bb8b2.diff"
  args:
    warn: false

- name: Apply tray patch
  patch:
    src: /opt/dwm/tray.diff
    basedir: /opt/dwm
    strip: 1

- name: dwm konpilatu eta instalatu
  make:
    chdir: /opt/dwm
    target: install

- name: stterm iturriak jaitsi
  git:
    repo: 'https://git.suckless.org/st'
    dest: /opt/st

- name: stterm konpilatu eta instalatu
  make:
    chdir: /opt/st
    target: install
