---
- name: Firefox instalatu Debian
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - firefox-esr
    - firefox-esr-l10n-eu
    - firefox-esr-l10n-es-es
  when: ansible_distribution == 'Debian'

- name: Sortu firefox lotura abiarazleetan
  file:
    src: /usr/share/applications/firefox-esr.desktop
    dest: /usr/share/applications/firefox.desktop
    state: link
  when: ansible_distribution == 'Debian'

- name: Firefox instalatu Ubuntu
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - firefox
    - firefox-locale-eu
    - firefox-locale-es
  when: ansible_distribution == 'Ubuntu'

- name: Ziurtatu firefoxen policies karpeta existitzen dela debian
  file:
    path: "/usr/share/firefox-esr/distribution"
    state: directory
  when: ansible_distribution == 'Debian'

- name: Ziurtatu firefoxen policies karpeta existitzen dela ubuntu
  file:
    path: "/usr/lib/firefox/distribution"
    state: directory
  when: ansible_distribution == 'Ubuntu'

- name: firefox politikak ezarri debian
  copy:
    src: "{{ role_path }}/files/usr/share/firefox-esr/distribution/policies.json.nirea"
    dest: "/usr/share/firefox-esr/distribution/policies.json"
    mode: 0644
  when: ansible_distribution == 'Debian'

- name: firefox politikak ezarri ubuntu
  copy:
    src: "{{ role_path }}/files/usr/share/firefox-esr/distribution/policies.json.nirea"
    dest: "/usr/lib/firefox/distribution/policies.json"
    mode: 0644
  when: ansible_distribution == 'Ubuntu'

- name: Redirect gehigarria jaitsi
  get_url:
    url: https://addons.mozilla.org/firefox/downloads/file/3025806/
    dest: /opt/redirect.xpi
    mode: 0644

- name: Ublock gehigarria jaitsi
  get_url:
    url: https://addons.mozilla.org/firefox/downloads/file/3392439/
    dest: /opt/ublock.xpi
    mode: 0644

- name: ffreszoom gehigarria jaitsi
  get_url:
    url: https://addons.mozilla.org/firefox/downloads/file/1712974/
    dest: /opt/ffreszoom.xpi
    mode: 0644

- name: duckduckgo gehigarria jaitsi
  get_url:
    url: https://addons.mozilla.org/firefox/downloads/file/3467553/
    dest: /opt/duckduckgo.xpi
    mode: 0644
