#gutxieneko idazmaia instalatzen du honek. xfce ubuntu edo debian-entzat.
---
- name: Xfce paketeak no-recommends.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - xfce4
    - atril
    - network-manager-gnome
    - kfind
    - policykit-1-gnome
    - dbus-x11
    - gmessage

- name: Xfce paketeak recommends.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - xfce4-goodies
    - pulseaudio
    - pavucontrol
    - avahi-daemon
    - libu2f-udev
    - lxtask
    - gparted
    - usermode
    - shotwell
    - qimgv
    - smplayer
    - tango-icon-theme
    - gnome-brave-icon-theme
    - gnome-themes-extra
    - ssh 
    - sshfs 
    - nfs-common
    - cifs-utils
    - gvfs-backends 
    - gvfs-fuse
    - file-roller
    - dconf-cli
    - xdg-user-dirs
    - suckless-tools
    - qt5ct
    - adwaita-qt
#    - indicator-sensors
#    - xfce4-indicator-plugin

- name: Adwaita Ubuntu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - adwaita-icon-theme-full
  when: ansible_distribution == 'Ubuntu'

- name: Kendu youtube-dl bertsio zaharra. SMPlayer-ekin instalatu da.
  apt:
    name: youtube-dl
    state: absent

- name: Instalatu youtube-dl bertsio berria.
  get_url:
    url: https://yt-dl.org/downloads/latest/youtube-dl
    dest: /usr/local/bin/youtube-dl
    mode: 0755

- name: Instalatu yt-dlp.
  get_url:
    url: https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp
    dest: /usr/local/bin/yt-dlp
    mode: 0755

- name: xfc4-terminal lehenetsi. Ubuntu.
  alternatives:
    name: x-terminal-emulator
    path: /usr/bin/xfce4-terminal.wrapper
  when: ansible_distribution == 'Ubuntu'

- name: Sortu konfigurazioen karpetak.
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "/etc/dconf/profile"
    - "/etc/dconf/db/local.d"
    - "/etc/xdg/xfce4/terminal"
    - "/etc/xdg/xfce4/kiosk"
    - "/etc/skel/.config/smplayer"
    - "/etc/skel/.config/qt5ct"
    - "/etc/systemd/sleep.conf.d"

- name: Beharrezko konfigurazioak kopiatu.
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/{{ item }}"
    mode: 0644
  with_items:
     - "etc/dconf/profile/user"
     - "etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml"
     - "etc/xdg/xfce4/terminal/terminalrc"
     - "etc/systemd/sleep.conf.d/sleep.conf"
     - "etc/xdg/xfce4/kiosk/kioskrc"
     - "usr/share/applications/kfind.desktop"
     - "usr/share/applications/unmute.desktop"
     - "etc/xdg/Trolltech.conf"
     - "etc/skel/.config/smplayer/smplayer.ini"
     - "etc/skel/.config/qt5ct/qt5ct.conf"
     - "etc/xdg/user-dirs.defaults"

- name: Kendu erabiltzen ez ditugun programak.
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/xdg/autostart/xscreensaver.desktop"
    - "/etc/xdg/autostart/light-locker.desktop"
    - "/etc/xdg/autostart/nm-applet.desktop"

- name: Hasieran automatikoki exekutatuko dena
  copy:
    src: "{{ role_path }}/files/usr/share/applications/{{ item }}"
    dest: "/etc/xdg/autostart/{{ item }}"
    mode: 0644
  with_items:
     - unmute.desktop
     - bikoiztu.desktop

- name: Begiratu file-roller konfiguratuta dagoen.
  stat:
    path: "/etc/dconf/db/local.d/00-file-roller"
  register: fileroller

- name: File-roller konfiguratu. Defektuz zip erabili nahi dugu.
  copy:
    src: "{{ role_path }}/files/etc/dconf/db/local.d/00-file-roller"
    dest: "/etc/dconf/db/local.d/00-file-roller"
    mode: 0644
  when: fileroller.stat.exists == False

- name: Dconf eguneratu
  command: "dconf update"
  when: fileroller.stat.exists == False

- name: xfce konfigurazio fitxategiak kopiatu.
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/{{ item }}"
    mode: 0644
  with_items:
    - "etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml"
    - "etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml"
    - "etc/xdg/xfce4/xfconf/xfce-perchannel-xml/keyboards.xml"
    - "etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml"
    - "etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml"
    - "etc/xdg/xfce4/xfconf/xfce-perchannel-xml/thunar.xml"
    - "etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml"
    - "etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml"
    - "etc/xdg/xfce4/panel/whiskermenu-1.rc"

- name: Panelaren konfigurazioa bi tokitan jarri behar da. Lotu.
  copy:
    src: "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml"
    dest: "/etc/xdg/xfce4/panel/default.xml"
    mode: 0644
    remote_src: yes

- name: Thunar custom actions. PDF-ak batu eta bereizteko scriptak.
  blockinfile:
    path: /etc/xdg/Thunar/uca.xml
    insertbefore: '</actions>'
    block: |
      <action>
        <icon></icon>
        <patterns>*.pdf;*.PDF</patterns>
        <name>Pdf-ak bereiztu</name>
        <command>/usr/local/bin/pdfakbereiztu %N</command>
        <description></description>
        <other-files/>
      </action>
      <action>
        <icon></icon>
        <patterns>*.pdf;*.PDF</patterns>
        <name>Pdf-ak batu</name>
        <command>/usr/local/bin/pdfakbatu %N</command>
        <description></description>
        <other-files/>
      </action>

- name: Thunar custom actions garbitu. Ansiblek gehitutako testua kendu.
  lineinfile: 
    dest: /etc/xdg/Thunar/uca.xml
    state: absent 
    regexp: "ANSIBLE"
