#Gure xfce konfigurazioak jarri. Debian eta Ubuntu.
---
- name: xfce konfigurazio fitxategiak kopiatu.
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ item }}"
    mode: 0644
  with_items:
    - "etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml"
    - "etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml"
    - "etc/xdg/xfce4/xfconf/xfce-perchannel-xml/keyboards.xml"
    - "etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml"
    - "etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml"
    - "etc/xdg/xfce4/xfconf/xfce-perchannel-xml/thunar.xml"
    - "etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml"
    - "etc/xdg/xfce4/panel/whiskermenu-1.rc"

- name: Panelaren konfigurazioa bi tokitan jarri behar da. Lotu.
  file:
    src: "etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml"
    dest: "/etc/xdg/xfce4/panel/default.xml"
    state: link
