---
- name: Chromium nabigatzailea
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - chromium
    - chromium-l10n

- name: Sortu chrome lotura abiarazleetan
  file:
    src: /usr/share/applications/chromium.desktop
    dest: /usr/share/applications/chrome.desktop
    state: link

- name: chromium aukerak ezarri
  copy:
    src: "{{ role_path }}/files/etc/chromium/master_preferences"
    dest: "/etc/chromium/master_preferences"
    mode: 0644

- name: chromium abiatzailea aldatu
  blockinfile:
    dest: "/etc/chromium.d/default-flags"
    block: |
      # Aldatu chromek pasahitzak gordetzeko modua
      export CHROMIUM_FLAGS="$CHROMIUM_FLAGS --password-store=basic"

- name: Create policies directory
  file:
    path: /etc/chromium/policies/managed
    state: directory
    mode: 0755

- name: chromium politikak ezarri
  copy:
    src: "{{ role_path }}/files/etc/chromium/policies/managed/policies.json.nirea"
    dest: "/etc/chromium/policies/managed/policies.json"
    mode: 0644

- name: default browser is firefox
  alternatives:
    name: x-www-browser
    path: /usr/bin/firefox

- name: default gnome-browser is firefox
  alternatives:
    name: gnome-www-browser
    path: /usr/bin/firefox
