#Firefox euskeraz instalatu. Politiken bidez konfiguratu eta gehigarri batzuk jarri.
---
- name: Firefox eta euskerazko lokala instalatu. Debian.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - firefox-esr
    - firefox-esr-l10n-eu
  when: ansible_distribution == 'Debian'

- name: Firefox eta euskerazko lokala instalatu. Ubuntu.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - firefox
    - firefox-locale-eu
  when: ansible_distribution == 'Ubuntu'

#Hau ez da beharrezkoa. Desktop fitxategiari Ubuntun duen izen berdina jartzen diot xfce panela bientzat berdin konfiguratzeko.
- name: Begiratu fitxategi originala existitzen den.
  stat:
    path: "/usr/share/applications/firefox-esr.desktop"
  register: desktop

- name: Desktop fitxategiaren izena aldatu.
  command: mv /usr/share/applications/firefox-esr.desktop /usr/share/applications/firefox.desktop
  when:
    - ansible_distribution == 'Debian'
    - desktop.stat.exists == True

- name: Politikak gordetzeko karpeta sortu. Debian.
  file:
    path: "/usr/share/firefox-esr/distribution"
    state: directory
  when: ansible_distribution == 'Debian'

- name: Politikak gordetzeko karpeta sortu. Ubuntu.
  file:
    path: "/usr/lib/firefox/distribution"
    state: directory
  when: ansible_distribution == 'Ubuntu'

- name: Firefox-en politikak ezarri. Debian.
  copy:
    src: "{{ role_path }}/files/usr/share/firefox-esr/distribution/policies.json"
    dest: "/usr/share/firefox-esr/distribution/policies.json"
    mode: 0644
  when: ansible_distribution == 'Debian'

- name: Firefox-en politikak ezarri. Ubuntu.
  copy:
    src: "{{ role_path }}/files/usr/share/firefox-esr/distribution/policies.json"
    dest: "/usr/lib/firefox/distribution/policies.json"
    mode: 0644
  when: ansible_distribution == 'Ubuntu'

- name: Ublock konfiguratzeko karpeta sortu. Ubuntu.
  file:
    path: "/usr/lib/mozilla/managed-storage"
    state: directory
  when: ansible_distribution == 'Ubuntu'

- name: Ublock konfigurazioa ezarri. Ubuntu.
  copy:
    src: "{{ role_path }}/files/usr/lib/mozilla/managed-storage/uBlock0@raymondhill.net.json"
    dest: "/usr/lib/mozilla/managed-storage/uBlock0@raymondhill.net.json"
    mode: 0644
  when: ansible_distribution == 'Ubuntu'
