#Firefox euskeraz instalatu. Politiken bidez konfiguratu eta gehigarri batzuk jarri.
---
- name: Firefox eta euskerako lokala instalatu. Debian.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - firefox-esr
    - firefox-esr-l10n-eu
  when: ansible_distribution == 'Debian'

- name: Firefox eta euskerako lokala instalatu. Ubuntu.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - firefox
    - firefox-locale-eu
  when: ansible_distribution == 'Ubuntu'

#Hau ez da beharrezkoa. Desktop fitxategiari Ubuntun duen izen berdina jartzen diot xfce panela bientzat berdin konfiguratzeko.
- name: Desktop fitxategiaren izena aldatu. Debian.
  command: mv /usr/share/applications/firefox-esr.desktop /usr/share/applications/firefox.desktop
  when: ansible_distribution == 'Debian'

- name: Politikak gordetzeko karpeta sortu. Debian.
  file:
    path: "/usr/share/firefox-esr/distribution"
    state: directory
  when: ansible_distribution == 'Debian'

- name: Politikak gordetzeko karpeta sortu. Ubuntu.
  file:
    path: "/usr/lib/firefox/distribution"
    state: directory
  when: ansible_distribution == 'Ubuntu'

- name: Firefox-en politikak ezarr. Debian.
  copy:
    src: "{{ role_path }}/files/usr/share/firefox-esr/distribution/policies.json"
    dest: "/usr/share/firefox-esr/distribution/policies.json"
    mode: 0644
  when: ansible_distribution == 'Debian'

- name: Firefox-en politikak ezarr. Ubuntu.
  copy:
    src: "{{ role_path }}/files/usr/share/firefox-esr/distribution/policies.json"
    dest: "/usr/lib/firefox/distribution/policies.json"
    mode: 0644
  when: ansible_distribution == 'Ubuntu'

- name: Ublock gehigarria jaitsi. Gero politiken fitxategiarekin instalatuko da.
  get_url:
    url: https://addons.mozilla.org/firefox/downloads/file/3392439/
    dest: /opt/ublock.xpi
    mode: 0644

- name: Duckduckgo gehigarria jaitsi. Gero politiken fitxategiarekin instalatuko da.
  get_url:
    url: https://addons.mozilla.org/firefox/downloads/file/3467553/
    dest: /opt/duckduckgo.xpi
    mode: 0644
