#Google chrome instalatu eta politikak ezarri.
#Ubuntun chromium paketea snap bidez instalatzen da eta ez zait gustatzen.
#Debianen meet-en funtzio batzuk desaktibatuta daude chromium instalatzerakoan.
---
- name: Dependentziak instalatu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - fonts-liberation

- name: Chrome paketea instalatu internetetik.
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

#Script bat erabiltzen dut irekitzerakoan aukerak gehituz.
- name: Nire script-a kopiatu.
  copy:
    src: "{{ role_path }}/files/usr/local/bin/chrome"
    dest: "/usr/local/bin/chrome"
    mode: 0755

#Hau ez da beharrezkoa. Desktop fitxategi berdina jartzen dut Ubuntu eta Debianen, xfce panela bientzat berdin konfiguratzeko.
- name: Desktop izena aldatu.
  command: mv /usr/share/applications/google-chrome.desktop /usr/share/applications/chrome.desktop

- name: Chrome esteka sortu /usr/bin barruan
  file:
    src: /usr/local/bin/chrome
    dest: /usr/bin/google-chrome-stable
    state: link

- name: Eguneratzailea kendu
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/cron.daily/google-chrome"
    - "/opt/google/chrome/cron"

#Firefox nahiago dudanez
- name: Lehenetsitako nabigatzailea firefox jarri.
  alternatives:
    name: "{{ item }}"
    path: /usr/bin/firefox
  with_items:
    - x-www-browser
    - gnome-www-browser

- name: Politiken karpeta sortu.
  file:
    path: /etc/opt/chrome/policies/managed
    state: directory
    mode: 0755

- name: Politikak ezarri.
  copy:
    src: "{{ role_path }}/files/etc/chromium/policies/managed/policies.json"
    dest: "/etc/opt/chrome/policies/managed/policies.json"
    mode: 0644

- name: Skel barruan chrome-ren karpeta sortu.
  file:
    path: /etc/skel/.config/google-chrome
    state: directory
    mode: 0755

#Fitxategi honekin chromek ez du galdetuko lehenetsitako nabigatzailea izatea nahi dugun.
- name: First run fitxategia sortu.
  copy:
    content: ""
    dest: "/etc/skel/.config/google-chrome/First Run"
    force: no
    owner: root
    mode: 0644
