#Chromium instalatu eta politikak ezarri.
---
- name: Chromium instalatu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - chromium
    - chromium-l10n

#Hau ez da beharrezkoa. Desktop fitxategi berdina jartzen dut Ubuntu eta Debianen, xfce panela bientzat berdin konfiguratzeko.
- name: Begiratu fitxategi originala existitzen den.
  stat:
    path: "/usr/share/applications/chromium.desktop"
  register: desktop

- name: Desktop izena aldatu.
  command: mv /usr/share/applications/chromium.desktop /usr/share/applications/chrome.desktop
  when: desktop.stat.exists == True 

- name: Chrome esteka sortu /usr/bin barruan
  file:
    src: /usr/bin/chromium
    dest: /usr/bin/chrome
    state: link

- name: Aukerak gehitu.
  blockinfile:
    dest: "/etc/chromium.d/default-flags"
    block: |
      # Change password store to basic, so it doesn't complain at start
      export CHROMIUM_FLAGS="$CHROMIUM_FLAGS --password-store=basic"

- name: Politiken karpeta sortu.
  file:
    path: /etc/chromium/policies/managed
    state: directory
    mode: 0755

- name: Politikak ezarri.
  copy:
    src: "{{ role_path }}/files/etc/chromium/policies/managed/policies.json"
    dest: "/etc/chromium/policies/managed/policies.json"
    mode: 0644

#Firefox nahiago dudanez
- name: Lehenetsitako nabigatzailea firefox jarri.
  alternatives:
    name: "{{ item }}"
    path: /usr/bin/firefox
  with_items:
    - x-www-browser
    - gnome-www-browser

- name: master_preferences fitxategia kendu
  file:
    path: /etc/chromium/master_preferences
    state: absent

#/opt/google/chrome/master_preferences
- name: Nabigatzailea konfiguratu.
  copy:
    src: "{{ role_path }}/files/etc/chromium/master_preferences"
    dest: "/etc/chromium/master_preferences"
    mode: 0644
