---
- name: Requisites
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - fonts-liberation

- name: Install a deb package from the internet.
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

- name: Sortu chrome lotura abiarazleetan
  file:
    src: /usr/share/applications/google-chrome.desktop
    dest: /usr/share/applications/chrome.desktop
    state: link

- name: Sortu chrome lotura /usr/bin barruan            
  file:
    src: /usr/bin/google-chrome
    dest: /usr/bin/chrome
    state: link

- name: Delete chrome updater
  file:
    path: /etc/cron.daily/google-chrome 
    state: absent

- name: Delete chrome updater
  file:
    path: /opt/google/chrome/cron
    state: absent

- name: default browser is firefox
  alternatives:
    name: x-www-browser
    path: /usr/bin/firefox

- name: default gnome-browser is firefox
  alternatives:
    name: gnome-www-browser
    path: /usr/bin/firefox

- name: chrome aukerak ezarri
  copy:
    src: "{{ role_path }}/files/etc/chromium/master_preferences"
    dest: "/opt/google/chrome/master_preferences"
    mode: 0644

- name: Create policies directory
  file:
    path: /etc/opt/chrome/policies/managed
    state: directory
    mode: 0755

- name: chromium politikak ezarri
  copy:
    src: "{{ role_path }}/files/etc/chromium/policies/managed/policies.json.nirea"
    dest: "/etc/opt/chrome/policies/managed/policies.json"
    mode: 0644

- name: Create skel directory
  file:
    path: /etc/skel/.config/google-chrome
    state: directory
    mode: 0755

- name: Create first run file
  copy:
    content: ""
    dest: "/etc/skel/.config/google-chrome/First Run"
    force: no
    owner: root
    mode: 0644

- name: aldatu chrome abiarazlea
  replace:
    dest: "/usr/share/applications/google-chrome.desktop"
    regexp: 'Exec=/usr/bin/google-chrome-stable'
    replace: 'Exec=/usr/bin/google-chrome-stable --password-store=basic'

