#Libreoffice instalatu eta konfigurazio batzuk jarri. Ubuntu eta Debian.
---
- name: Libreoffice instalatu.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - libreoffice
    - libreoffice-l10n-eu
    - libreoffice-l10n-es
    - libreoffice-help-en-us
    - libreoffice-help-es
    - libreoffice-help-eu
    - libreoffice-gtk2
    - libreoffice-gtk3
    - mythes-en-us
    - mythes-es
    - hunspell-en-us
    - hunspell-es
    - hunspell-eu
    - hunspell-eu-es
    - hyphen-en-us
    - hyphen-es

#Honekin bi erabiltzailek fitxategi berdina aldi berean irekitzea posible da.
- name: Fitxategien blokeoa kendu.
  copy:
    src: "{{ role_path }}/files/usr/lib/libreoffice/share/registry/disable-file-locking.xcd"
    dest: "/usr/lib/libreoffice/share/registry/disable-file-locking.xcd"
    mode: 0644

- name: "whats new" mezua kendu.
  copy:
    src: "{{ role_path }}/files/usr/lib/libreoffice/share/registry/lastver.xcd"
    dest: "/usr/lib/libreoffice/share/registry/lastver.xcd"
    mode: 0644

- name: "tip of the day" mezua kendu.
  copy:
    src: "{{ role_path }}/files/usr/lib/libreoffice/share/registry/tipoftheday.xcd"
    dest: "/usr/lib/libreoffice/share/registry/tipoftheday.xcd"
    mode: 0644

- name: F4 teklarekin formulak jartzeko menua ireki.
  copy:
    src: "{{ role_path }}/files/usr/lib/libreoffice/share/registry/f4formula.xcd"
    dest: "/usr/lib/libreoffice/share/registry/f4formula.xcd"
    mode: 0644
