#Libreoffice instalatu eta konfigurazio batzuk jarri. Ubuntu eta Debian.
---
- name: Libreoffice instalatu.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - libreoffice
    - libreoffice-l10n-eu
    - libreoffice-l10n-es
    - libreoffice-help-en-us
    - libreoffice-help-es
    - libreoffice-help-eu
    - libreoffice-gtk3
    - mythes-en-us
    - mythes-es
    - hunspell-en-us
    - hunspell-es
    - hunspell-eu
    - hunspell-eu-es
    - hyphen-en-us
    - hyphen-es

- name: Libreoffice instalatu.
  apt:
    name: libreoffice-gtk2
    install_recommends: no
  when: ansible_distribution_release in ['buster', 'focal']

#Honekin bi erabiltzailek fitxategi berdina aldi berean irekitzea posible da.
- name: libreoffice konfigurazio fitxategiak kopiatu.
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/{{ item }}"
    mode: 0644
  with_items:
    - "usr/lib/libreoffice/share/registry/disable-file-locking.xcd"
    - "usr/lib/libreoffice/share/registry/lastver.xcd"
    - "usr/lib/libreoffice/share/registry/tipoftheday.xcd"
    - "usr/lib/libreoffice/share/registry/f4formula.xcd"

- name: Txantiloiak kopiatu.
  copy:
    src: "{{ role_path }}/files/etc/skel/.Templates"
    dest: "/etc/skel"
    mode: 0755

- name: auto accept licence for msttcorefonts
  debconf: 
    name: ttf-mscorefonts-installer 
    question: msttcorefonts/accepted-mscorefonts-eula 
    vtype: boolean
    value: 'true'

- name: Microsoft-en letrak instalatu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - ttf-mscorefonts-installer
    - fonts-crosextra-caladea
    - fonts-crosextra-carlito
