---
- name: libreoffice instalatu
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - libreoffice
    - libreoffice-l10n-eu
    - libreoffice-l10n-es
    - libreoffice-help-en-us
    - libreoffice-help-es
    - libreoffice-help-eu
    - libreoffice-gtk2
    - libreoffice-gtk3
    - mythes-en-us
    - mythes-es
    - hunspell-en-us
    - hunspell-es
    - hunspell-eu
    - hunspell-eu-es
    - hyphen-en-us
    - hyphen-es

- name: libreofficen fitxateki blokeoa kentzen
  copy:
    src: "{{ role_path }}/files/usr/lib/libreoffice/share/registry/disable-file-locking.xcd"
    dest: "/usr/lib/libreoffice/share/registry/disable-file-locking.xcd"
    mode: 0644

- name: disable "whats new" message
  copy:
    src: "{{ role_path }}/files/usr/lib/libreoffice/share/registry/lastver.xcd"
    dest: "/usr/lib/libreoffice/share/registry/lastver.xcd"
    mode: 0644

- name: disable "tip of the day" wizard
  copy:
    src: "{{ role_path }}/files/usr/lib/libreoffice/share/registry/tipoftheday.xcd"
    dest: "/usr/lib/libreoffice/share/registry/tipoftheday.xcd"
    mode: 0644

