#Libreoffice instalatu eta konfigurazio batzuk jarri. Ubuntu eta Debian.
---
- name: Libreoffice instalatu.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - libreoffice
    - libreoffice-l10n-eu
    - libreoffice-l10n-es
    - libreoffice-help-en-us
    - libreoffice-help-es
    - libreoffice-help-eu
    - libreoffice-gtk3
    - mythes-en-us
    - mythes-es
    - hunspell-en-us
    - hunspell-es
    - hunspell-eu
    - hunspell-eu-es
    - hyphen-en-us
    - hyphen-es

#Honekin bi erabiltzailek fitxategi berdina aldi berean irekitzea posible da.
- name: libreoffice konfigurazio fitxategiak kopiatu.
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/{{ item }}"
    mode: 0644
  with_items:
    - "usr/lib/libreoffice/share/registry/disable-file-locking.xcd"
    - "usr/lib/libreoffice/share/registry/lastver.xcd"
    - "usr/lib/libreoffice/share/registry/tipoftheday.xcd"
    - "usr/lib/libreoffice/share/registry/f4formula.xcd"
    - "usr/lib/libreoffice/share/registry/tango.xcd"

#- name: tango ikonoak kopiatu.
#  copy:
#    src: "{{ role_path }}/files/usr/lib/libreoffice/share/config/images_tango.zip"
#    dest: "/{{ item }}"
#    mode: 0644
#  with_items:
#    - "usr/lib/libreoffice/share/config/images_tango.zip"
#    - "usr/share/libreoffice/share/config/images_tango.zip"

- name: Txantiloiak kopiatu.
  copy:
    src: "{{ role_path }}/files/etc/skel/.Templates"
    dest: "/etc/skel"
    mode: 0755

#debconf-show ttf-mscorefonts-installer
- name: auto accept licence for msttcorefonts
  debconf: 
    name: ttf-mscorefonts-installer 
    question: msttcorefonts/accepted-mscorefonts-eula 
    vtype: boolean
    value: 'true'

- name: Microsoft-en letrak instalatu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - ttf-mscorefonts-installer
    - fonts-crosextra-caladea
    - fonts-crosextra-carlito

- name: Xuxen deskargatu
  get_url:
    url: https://extensions.libreoffice.org/assets/downloads/2704/1701702834/xuxen_5.4.10_libreoffice.oxt
    dest: /opt/xuxen.oxt

- name: Xuxen instalatu
  command: /usr/bin/unopkg add --shared /opt/xuxen.oxt

- name: Xuxen instalatzailea kendu
  file:
    path: /opt/xuxen.oxt
    state: absent
