#Erabiltzen ditugun programa extra batzuk instalatzeko. 
---
- name: Multimedia programak instalatu.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - jclic
    - audacity
    - skanlite
    - sound-juicer
    - cheese
    - vlc
    - winff
    - aegisub
    - aegisub-l10n
    - texlive-extra-utils
    - pdftk
    - cups-pdf
    - inkscape
    - gimp
    - gthumb
    - xournal
    - galculator
    - kazam
    - kdenlive
    - breeze-icon-theme
    - frei0r-plugins
    - gromit-mpx
    - obs-studio
    - calibre

- name: Kolourpaint Ubuntu.
  apt:
    name: kolourpaint
    install_recommends: no
  when: ansible_distribution == 'Ubuntu'

- name: Kolourpaint Debian eta openshot.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - kolourpaint4
    - openshot
  when: ansible_distribution == 'Debian'

- name: Kanpotik lan egiteko programak.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - rdesktop
    - freerdp2-x11
    - zenity
    - network-manager-openvpn-gnome

- name: Remotedesk aplikazioaren abiarazlea kopiatu.
  copy:
    src: "{{ role_path }}/files/usr/share/applications/remotedesk.desktop"
    dest: "/usr/share/applications/remotedesk.desktop"
    mode: 0644

#(xdg-utils programarekin) xdg-mime default gpicview.desktop `grep 'MimeType=' /usr/share/applications/gpicview.desktop | sed -e 's/.*=//' -e 's/;/ /g'`
- name: Fitxategi motak programekin lotu.
  copy:
    src: "{{ role_path }}/files/etc/xdg/mimeapps.list"
    dest: "/etc/xdg/mimeapps.list"
    mode: 0644

- name: xournal karpeta sortu skel barruan.
  file:
    path: /etc/skel/.xournal
    state: directory
    mode: 0755

- name: xournal konfiguratu.
  copy:
    src: "{{ role_path }}/files/etc/skel/.xournal/config"
    dest: /etc/skel/.xournal/config
    mode: 0644

- name: Gure scriptak kopiatu
  copy:
    src: "{{ role_path }}/files/usr/local/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
  with_items:
     - pdfakbatu
     - pdfakbereiztu
     - pdfakzenbatu
     - ikusionline
     - inpresorakkendu
     - remotedesk

- name: Educan erabili ahal izateko java instalatu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - icedtea-netx

#debconf-show libdvd-pkg
#- name: auto accept licence for msttcorefonts
#  debconf: 
#    name: libdvd-pkg
#    question: libdvd-pkg/build 
#    question: libdvd-pkg/post-invoke_hook-install
#    vtype: boolean
#    value: 'true'

- name: DVD-ak ikusteko liburutegiak instalatu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - libdvd-pkg

- name: Dpkg-reconfigure libdvd-pkg.
  command: /usr/sbin/dpkg-reconfigure --frontend=noninteractive libdvd-pkg
