#Erabiltzen ditugun programa extra batzuk instalatzeko. 
---
- name: Multimedia programak instalatu.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - jclic
    - audacity
    - skanlite
    - kolourpaint4
    - sound-juicer
    - cheese
    - vlc
    - winff
    - aegisub
    - aegisub-l10n
    - texlive-extra-utils
    - pdftk
    - cups-pdf
    - inkscape
    - gimp
    - xournal
    - openshot
    - galculator
    - kazam
    - kdenlive
    - frei0r-plugins
    - gromit-mpx

- name: OBS instalatu, bakarrik ubuntun.
  apt:
    name: obs-studio
    install_recommends: no
  when: ansible_distribution == 'Ubuntu'

- name: gthumb programaren gai iluna kedu.
  replace:
    dest: "/usr/share/applications/org.gnome.gThumb.desktop"
    regexp: 'Exec=gthumb %U'
    replace: 'Exec=env GTK_THEME=Adwaita gthumb %U'

- name: Kanpotik lan egiteko programak.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - rdesktop
    - network-manager-openvpn-gnome

- name: Fitxategi motak programekin lotu.
  copy:
    src: "{{ role_path }}/files/etc/xdg/mimeapps.list"
    dest: "/etc/xdg/mimeapps.list"
    mode: 0644

- name: xournal karpeta sortu skel barruan.
  file:
    path: /etc/skel/.xournal
    state: directory
    mode: 0755

- name: xournal konfiguratu.
  copy:
    src: "{{ role_path }}/files/etc/skel/.xournal/config"
    dest: /etc/skel/.xournal/config
    mode: 0644

- name: Gure scriptak kopiatu
  copy:
    src: "{{ role_path }}/files/usr/local/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
  with_items:
     - pdfakbatu
     - pdfakbereiztu
     - pdfakzenbatu
     - ikusionline

- name: Educan erabili ahal izateko java instalatu.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - icedtea-netx
