#Xfce-ren fitxategiak blokeatzen ditugu, erabiltzaileek aldaketarik ez egiteko.
---
- name: Xfce blokeatu.
  replace:
    dest: "{{ item }}"
    regexp: 'version="1.0">'
    replace: 'version="1.0" locked="*" unlocked="root;@wheel">'
  with_items:
    - "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml"
    - "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml"
    - "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml"
    - "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml"
    - "/etc/xdg/xfce4/panel/default.xml"
    - "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml"
    - "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/keyboards.xml"
    - "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/thunar.xml"
    - "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml"
