#Zoom programa instalatu.
---
- name: Begiratu zoom instalatuta dagoen.
  stat:
    path: /usr/bin/zoom
  register: zoom

- name: Zoom karpeta sortu.
  file:
    path: /root/zoom
    state: directory
  when: zoom.stat.exists == False

#- name: i386 instalatzailea deskargatu.
#  get_url:
#    url: "https://zoom.us/client/latest/zoom_i386.deb"
#    dest: "/root/zoom/zoom.deb"
#    mode: 0644
#  when:
#    - zoom.stat.exists == False
#    - ansible_architecture == 'i386'

- name: amd64 instalatzailea deskargatu.
  get_url:
    url: "https://zoom.us/client/latest/zoom_amd64.deb"
    dest: "/root/zoom/zoom.deb"
    mode: 0644
  when:
    - zoom.stat.exists == False
    - ansible_architecture == 'x86_64'

- name: Instalatzailea erauzi.
  command: dpkg-deb -R /root/zoom/zoom.deb /root/zoom/zoom
  args:
    warn: no
  when: zoom.stat.exists == False

- name: Dependentziak aldatu, ibus ez instalatzeko.
  replace:
    dest: /root/zoom/zoom/DEBIAN/control
    regexp: ', ibus'
    replace: ' '
  when: zoom.stat.exists == False

- name: Instalatzaile berria prestatu.
  command: dpkg-deb -b /root/zoom/zoom /root/zoom/zoom2.deb
  args:
    warn: no
  when: zoom.stat.exists == False

- name: Zoom instalatu.
  apt:
    deb: "/root/zoom/zoom2.deb"
  when: zoom.stat.exists == False

- name: Fitxategiak ezabatu.
  file:
    path: "/root/zoom"
    state: absent
