#Zoom programa instalatu.
---
- name: Zoom karpeta sortu.
  file:
    path: /root/zoom
    state: directory

- name: i386 instalatzailea deskargatu.
  get_url:
    url: "https://zoom.us/client/latest/zoom_i386.deb"
    dest: "/root/zoom/zoom.deb"
    mode: 0644
  when: ansible_architecture == 'i386'

- name: amd64 instalatzailea deskargatu.
  get_url:
    url: "https://zoom.us/client/latest/zoom_amd64.deb"
    dest: "/root/zoom/zoom.deb"
    mode: 0644
  when: ansible_architecture == 'x86_64'

#- name: Instalatzailea erauzi.
#  command: dpkg-deb -R /root/zoom/zoom.deb /root/zoom/zoom
#  args:
#    warn: no

#- name: Dependentziak aldatu, ibus ez instalatzeko.
#  replace:
#    dest: /root/zoom/zoom/DEBIAN/control
#    regexp: ', ibus'
#    replace: ' '

#- name: Instalatzaile berria prestatu.
#  command: dpkg-deb -b /root/zoom/zoom /root/zoom/zoom2.deb
#  args:
#    warn: no

#- name: Zoom instalatu.
#  apt:
#    deb: "/root/zoom/zoom2.deb"

- name: Zoom instalatu.
  apt:
    deb: "/root/zoom/zoom.deb"

- name: Fitxategiak ezabatu.
  file:
    path: "/root/zoom"
    state: absent
