---
- name: Mahaigaineko irudia kopiatzen
  copy:
    src: "{{ role_path }}/files/usr/share/backgrounds/xfce/ikastola.jpg"
    dest: "/usr/share/backgrounds/xfce/ikastola.jpg"
    mode: 0644

- name: mahaigaina konfiguratzen
  copy:
    src: "{{ role_path }}/files/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml"
    dest: "/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml"
    mode: 0644

- name: lightdm itxura aldatu
  lineinfile:
    dest: "/etc/lightdm/lightdm-gtk-greeter.conf"
    regexp: '^background'
    line: 'background=/usr/share/backgrounds/xfce/ikastola.jpg'
    backrefs: yes

- name: ziurtatu desktop-directories karpeta existitzen dela
  file:
    path: "/usr/local/share/desktop-directories"
    state: directory

- name: txanelako menua gehitzen
  copy:
    src: "{{ role_path }}/files/usr/local/share/desktop-directories/txanela.directory"
    dest: "/usr/local/share/desktop-directories/txanela.directory"
    mode: 0644

- name: cups-browsed konfiguratu
  blockinfile:
    create: yes
    dest: "/etc/cups/cups-browsed.conf"
    block: |
      BrowsePoll 10.10.0.21
      LocalQueueNamingRemoteCUPS RemoteName

- name: firefox politikak ezarri debian
  copy:
    src: "{{ role_path }}/files/usr/share/firefox-esr/distribution/policies.json.ikastola"
    dest: "/usr/share/firefox-esr/distribution/policies.json"
    mode: 0644
  when: ansible_distribution == 'Debian'

- name: firefox politikak ezarri ubuntu
  copy:
    src: "{{ role_path }}/files/usr/share/firefox-esr/distribution/policies.json.ikastola"
    dest: "/usr/lib/firefox/distribution/policies.json"
    mode: 0644
  when: ansible_distribution == 'Ubuntu'

- name: chromium politikak ezarri
  copy:
    src: "{{ role_path }}/files/etc/chromium/policies/managed/policies.json.ikastola"
    dest: "/etc/chromium/policies/managed/policies.json"
    mode: 0644
  when: ansible_distribution == 'Debian'

- name: chrome politikak ezarri
  copy:
    src: "{{ role_path }}/files/etc/chromium/policies/managed/policies.json.ikastola"
    dest: "/etc/opt/chrome/policies/managed/policies.json"
    mode: 0644
  when: ansible_distribution == 'Ubuntu'

