#virt-viewer programa instalatzen dugu eta OpenSSL-ren konfigurazioa aldatzen dugu, gure oVirt zerbitzaria zaharra delako.
---
- name: Spice zerbitzari eta bezero paketeak.
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
    - virt-viewer
    - spice-vdagent
    - libspice-server1

#debian
- name: OpenSSL konfiguratu.
  lineinfile:
    dest: /etc/ssl/openssl.cnf
    regexp: 'CipherString = DEFAULT@SECLEVEL=2'
    line: 'CipherString = DEFAULT@SECLEVEL=1'
    backrefs: yes
  when: ansible_distribution_release == 'buster'

#ubuntu
- name: OpenSSL konfiguratu.
  lineinfile:
    path: /etc/ssl/openssl.cnf
    insertbefore: BOF
    line: 'openssl_conf = openssl_conf_sect'
  when: ansible_distribution_release != 'buster'

- name: OpenSSL konfiguratu.
  lineinfile:
    path: /etc/ssl/openssl.cnf
    insertafter: EOF
    line: '{{ item }}'
  with_items:
    - '[openssl_conf_sect]'
    - 'ssl_conf = ssl_sect'
    - ''
    - '[ssl_sect]'
    - 'system_default = system_default_sect'
    - ''
    - '[system_default_sect]'
    - 'CipherString = DEFAULT@SECLEVEL=1'
  when: ansible_distribution_release != 'buster'
