#virt-viewer programa instalatzen dugu eta OpenSSL-ren konfigurazioa aldatzen dugu, gure oVirt zerbitzaria zaharra delako.
---
- name: virt-viewer instalatu.
  apt:
    name: virt-viewer

- name: OpenSSL konfiguratu.
  lineinfile:
    dest: /etc/ssl/openssl.cnf
    regexp: 'CipherString = DEFAULT@SECLEVEL=2'
    line: 'CipherString = DEFAULT@SECLEVEL=1'
    backrefs: yes
