- name: Check if it's already installed
  stat:
    path: "/usr/local/bin/fsearch"
  register: fsearch_bin

- name: Install fsearch build dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - git
    - build-essential
    - libopengl0
    - automake
    - autopoint
    - autoconf
    - libtool
    - pkg-config
    - intltool
    - autoconf-archive
    - libicu-dev
    - libpcre3-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libxml2-utils
  when: not fsearch_bin.stat.exists

- name: Download fsearch git
  git:
    repo: 'https://github.com/cboxdoerfer/fsearch.git'
    dest: /home/fsearch
  when: not fsearch_bin.stat.exists

- name: Autogen fsearch
  command: "sh autogen.sh"
  args:
    chdir: "/home/fsearch"
  when: not fsearch_bin.stat.exists

- name: Configure fsearch
  command: "sh configure"
  args:
    chdir: "/home/fsearch"
  when: not fsearch_bin.stat.exists

- name: Build fsearch
  make:
    chdir: /home/fsearch
    params:
      NUM_THREADS: 4
  when: not fsearch_bin.stat.exists

- name: Build install fsearch
  make:
    chdir: /home/fsearch
    target: install
  when: not fsearch_bin.stat.exists

- name: Clean fsearch sources
  file:
    path: /home/fsearch
    state: absent
  when: not fsearch_bin.stat.exists

- name: Remove fsearch build dependencies
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - git
    - build-essential
    - libopengl0
    - automake
    - autopoint
    - autoconf
    - libtool
    - pkg-config
    - intltool
    - autoconf-archive
    - libicu-dev
    - libpcre3-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libxml2-utils
  when: not fsearch_bin.stat.exists
