#this task downloads and installs java
---
- name: Begiratu ea aurretik instalatuta dagoen
  stat:
    path: "/opt/jre1.8.0_333"
  register: opt_java

- name: jre jaitsi
  get_url:
    url: https://javadl.oracle.com/webapps/download/AutoDL?BundleId=246464_2dee051a5d0647d5be72a7c0abff270e
    dest: /opt/jre-8u333-linux-x64.tar.gz
    mode: '0440'
  when: not opt_java.stat.exists

- name: jre erauzi
  unarchive:
    src: /opt/jre-8u333-linux-x64.tar.gz
    dest: /opt
    remote_src: yes
  when: not opt_java.stat.exists

- name: Kendu jaitsitako fitxategia
  file:
    path: /opt/jre-8u333-linux-x64.tar.gz
    state: absent
  when: not opt_java.stat.exists

- name: xfc4-terminal lehenetsi.
  alternatives:
    name: x-terminal-emulator
    path: /usr/bin/xfce4-terminal.wrapper
  when: ansible_distribution == 'Ubuntu'

#update-alternatives --install /usr/bin/javaws javaws /opt/jre-java/bin/javaws 1102
#update-alternatives --set javaws /opt/jre-java/bin/javaws
- name: Sisteman gehitu
  alternatives:
    name: javaws
    path: /opt/jre1.8.0_333/bin/javaws
    link: /usr/bin/javaws
    state: present


