#this task installs issu downloader script
---
- name: issuu-dl script-a deskargatu.
  get_url:
    url: "https://raw.githubusercontent.com/fluks/issuu-dl/master/issuu-dl"
    dest: "/usr/local/bin/issuu-dl"
    mode: 0755

- name: Imagemagick-en politika aldatu.
  replace:
    dest: "/etc/ImageMagick-6/policy.xml"
    regexp: '<policy domain="coder" rights="none" pattern="PDF" />'
    replace: '<!-- <policy domain="coder" rights="none" pattern="PDF" /> -->'
#    replace: '<policy domain="coder" rights="read|write" pattern="PDF" />'

- name: Awk komandoa aldatu.
  replace:
    dest: "/usr/local/bin/issuu-dl"
    regexp: '--assign=dir="$tmp_dir"'
    replace: '-v dir="$tmp_dir"'
