---

#  - include: 00-minimo.yml

#  - include: 01-xfce.yml

#  - include: 02-hizkuntza.yml

  - include: 03-firefox.yml

#  - include: 04-chromium.yml

#  - include: 05-libreoffice.yml

#  - include: 06-extra.yml

#  - include: 08-inpesora.yml

#  - include: 09-kiosk.yml

#  - include: 10-ikastola.yml

#  - include: 11-zoom.yml

#  - include: 12-ovirt.yml

