---
- name: Mendekoak
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - accountsservice 
    - libaccountsservice0 
    - python3-pexpect 
    - python3-ptyprocess

- name: mugshot instalatu
  apt:
    deb: http://ftp.fr.debian.org/debian/pool/main/m/mugshot/mugshot_0.4.2-1_all.deb
