---
- name: Xfce minimo
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - xubuntu-core
    - gtk2-engines-xfce 
    - gtk3-engines-xfce
    - tango-icon-theme
    - tango-icon-theme-extras
    - adwaita-icon-theme-full
    - mousepad
    - galculator
    - gpicview

- name: Chromium nabigatzailea
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - chromium-browser
    - chromium-browser-l10n

- name: Firefox nabigatzailea
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - firefox

- name: Kendu ubunturen gehigarria
  apt:
    name: xul-ext-ubufox
    state: absent

- name: Libreoffice
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - libreoffice
    - libreoffice-l10n-eu
    - libreoffice-help-eu
    - libreoffice-l10n-es
    - libreoffice-help-es
    - evince

- name: Multimedia
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - jclic
    - audacity
    - brasero
    - skanlite
    - gthumb
    - kolourpaint4
    - sound-juicer
    - cheese
    - kazam
    - openshot
    - smplayer
    - vlc
    - winff

- name: kendu xubunturen konfigurazioa
  file:
    path: "/etc/xdg/xdg-xubuntu"
    state: absent

- name: youtube-dl deskargatu
  get_url:
    url: https://yt-dl.org/downloads/latest/youtube-dl 
    dest: /usr/local/bin/youtube-dl
    mode: 755
