---
- name: Sortu smart erabiltzaile lokala
  user:
    name: smart
    shell: /bin/bash
    createhome: yes
    home: /erab/smart

- name: domeinuko erabiltzaileei utzi programak smart erabiltzailearen izenean exekutatzen
  blockinfile:
    create: yes
    dest: "/etc/sudoers"
    block: |
      %lizarra\ ikastola ALL=(smart) NOPASSWD: ALL
      usuario ALL=(smart) NOPASSWD: ALL

- name: smartsudo komandoa kopiatu
  copy:
    src: "{{ role_path }}/files/usr/local/bin/smartsudo"
    dest: "/usr/local/bin/smartsudo"
    mode: 0755

- name: polkit konfiguratu
  copy:
    src: "{{ role_path }}/files/usr/share/polkit-1/actions/org.freedesktop.policykit.smart.policy"
    dest: "/usr/share/polkit-1/actions/org.freedesktop.policykit.smart.policy"
    mode: 0644

- name: smartpkexec komandoa kopiatu
  copy:
    src: "{{ role_path }}/files/usr/local/bin/smartpkexec"
    dest: "/usr/local/bin/smartpkexec"
    mode: 0755

- name: Kendu autostart ofiziala
  file:
    path: /etc/xdg/autostart/smart_1-_Service.desktop
    state: absent

- name: Kendu autostart ofiziala
  file:
    path: /etc/xdg/autostart/smart_1-_Tools.desktop 
    state: absent
