---
- name: Dependentzik instalatu
  apt:
    name: "{{ packages }}"
    when: arch == 'i386'
  vars:
    packages:
    - libasound2 
    - libbluetooth3 
    - libc6 
    - libcurl4 
    - libfontconfig1 
    - libfreetype6 
    - libgcc1 
    - libgl1-mesa-glx 
    - libglib2.0-0 
    - libgtk2.0-0 
    - libice6 
    - libnspr4 
    - libsm6 
    - libstdc++6 
    - libudev1 
    - libuuid1 
    - libx11-6 
    - libxext6 
    - libxinerama1 
    - libxkbfile1 
    - libxml2 
    - libxrender1 
    - libxtst6 
    - zlib1g 
    - libxslt1.1 
    - libltdl7
    - libusb-1.0-0

- name: Gehitu i386 paketeak
  command: /usr/bin/dpkg --add-architecture i386
    when: arch == 'amd64'

- name: apt-get update
  apt:
    update_cache: yes
    when: arch == 'amd64'

- name: Dependentzik instalatu
  apt:
    name: "{{ packages }}"
    when: arch == 'amd64'
  vars:
    packages:
    - libasound2:i386
    - libbluetooth3:i386
    - libc6:i386
    - libcurl4:i386
    - libfontconfig1:i386
    - libfreetype6:i386
    - libgcc1:i386
    - libgl1-mesa-glx:i386
    - libglib2.0-0:i386
    - libgtk2.0-0:i386
    - libice6:i386
    - libnspr4:i386
    - libsm6:i386
    - libstdc++6:i386
    - libudev1:i386
    - libuuid1:i386
    - libx11-6:i386
    - libxext6:i386
    - libxinerama1:i386
    - libxkbfile1:i386
    - libxml2:i386
    - libxrender1:i386
    - libxtst6:i386
    - zlib1g:i386
    - libxslt1.1:i386 
    - libltdl7:i386
    - libusb-1.0-0:i386

- name: libudev1 eta libudev0 lotu
  file:
    src: /lib/i386-linux-gnu/libudev.so.1
    dest: /lib/i386-linux-gnu/libudev.so.0
    state: link

#hemendik aurrera dagoena 64 biteko bertsioan dagoen arazo bat konpontzeko da. domeinuko erabiltzaileek ezin dute smart ireki
- name: Sortu smart erabiltzaile lokala
  user:
    name: smart
    shell: /bin/bash
    createhome: yes
    home: /erab/smart
    when: arch == 'amd64'

- name: domeinuko erabiltzaileei utzi programak smart erabiltzailearen izenean exekutatzen
  blockinfile:
    create: yes
    dest: "/etc/sudoers"
    block: |
      %lizarra\ ikastola ALL=(smart) NOPASSWD: ALL
    when: arch == 'amd64'

- name: arbela komandoa kopiatu
  copy:
    src: "{{ role_path }}/files/usr/local/bin/arbela"
    dest: "/usr/local/bin/arbela"
    mode: 0755
    when: arch == 'amd64'

- name: smartzerbitzu komandoa kopiatu
  copy:
    src: "{{ role_path }}/files/usr/local/bin/smartzerbitzu"
    dest: "/usr/local/bin/smartzerbitzu"
    mode: 0755
    when: arch == 'amd64'
